### ISSUE TITLE
Gold Slime Core: it does nothing!

### ISSUE THREAD

**Issue by bear-irl** [SpadesNeil/VOREstation#100]
Bay commented out gold slime cores doing .. anything at all! No more xenos.

The solution begins to bubble.
  The the used slime extract's power is consumed in the reaction.
The slime core fizzles disappointingly,

Re-add the xenos or some other thing for gold cores?

**Comment by ArbyTheDragon** [comment]
Xeno effect was removed from bay code a long time ago, but re-adding would give medical something to do and security a reason to break out the firepower. I approve. Vagina dwelling xenomorphs sound fun... >w>

**Comment by SpadesNeil** [comment]
Indeed, we re-enabled this in the old code, and will re-enable it in the new. Just give me some time to mess with it. Certain mobs need to be blacklisted to avoid spawning things like drones.

**Comment by SpadesNeil** [comment]
All set. Xenobio page on the wiki also added.
