### ISSUE TITLE
Loyalty implants not being applied at round start

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#101]
Major issue since it gives permission to important head staff to ignore orders or just be flat out malicious.

**Comment by Arokha** [comment]
This is done except for HoP

**Comment by OrbisAnima** [comment]
I though HoP's didn't had loyalty implants?

**Comment by SpadesNeil** [comment]
Yes they do.

**Comment by SpadesNeil** [comment]
Also this was fixed.
