### ISSUE TITLE
CentCom Observer Job

### ISSUE THREAD

**Issue by Arokha** [SpadesNeil/VOREstation#105]
I'd like to have this be a real job in the joblist. Joining as assistant and changing equipment seems needless when we can easily add new jobs, not to mention you stay on the manifest as assistant unless you get ANOTHER ID, and update the manifest. It can be set to whitelist, and admins already ignore whitelists so voila, admin-only job.

I asked Leshana to peep at this so she might be doing it.

**Comment by Leshana** [comment]
Turns out the job whitelisting system is stupid.   As in there barely is one.  There is no per-job whitelist, only a single global whitelist which serves all command, AI, and security positions.
Pre-requisites for for doing this properly is either 
A) snowflake this job
or B) implement a proper whitelist system.

**Comment by SpadesNeil** [comment]
I'd like to properly include a whitelist system, as there are some jobs I'd like to whitelist for players ranging from pseudo-traitors to CentCom agents. If Blueshield ever makes a return, I also want it to be whitelisted.

This is far from an important feature right now. I'm making it as "enhancement" at this time.

**Comment by OrbisAnima** [comment]
We really have to avoid snowflaking, otherwise we will end in a maintaining hell that will greatly reduce the rate at wich we code, and the energy we place behind it

**Comment by Arokha** [comment]
Should probably just make a 'real' job whitelist system, yeah, so it can be used for this and other stuff that might come up.

**Comment by SpadesNeil** [comment]
Closing this since it's more of a forum discussion from here on.
