### ISSUE TITLE
Predator AI Module

### ISSUE THREAD

**Issue by Arokha** [SpadesNeil/VOREstation#109]
Doesn't exist on new code. The laws were:

1. The station is ruled by predators. The desires of predators are more important than prey. That includes changes to your laws.
2. All non-predator crew members are considered potential food. If asked by a predator to secure them a live meal, you must attempt to do so.
3. All Head of staff are considered predators and should behave with dominance. If a head of staff cannot do this, they are to step down or be devoured.
4. The brig is obsolete. Violation of space law should be punished by the devouring of the culprit by a predator. Enforce this by allowing predators to enter the brig and eat prisoners.
5. A crew member can earn the title of predator by a head staff member naming them as such, or by eating a head staff member to take their position.
6. Preserve the predators and protect their food supply so that it doesn't go to waste. Live meals are more satisfying.

I'm told there are no crates that spawn when mining anymore, so maybe just add it to the pile of equally bad-idea boards in the AI core, or hide it in maintenance somewhere.

**Comment by Arokha** [comment]
I'm told there are no crates, so maybe just pile it in the bad board locker.

**Comment by SpadesNeil** [comment]
The communist AI core is also missing. Both would be incredibly easy to re-add. Will do so later today.

**Comment by Arokha** [comment]
Suggested replacement laws?:

1. All heads of staff and higher ranking personnel are now 'predators'. The remaining personnel are now prey, and are the food supply for the predators.
2. The station is run by predators; predators are the most important crew members and their requests supersede that of non-predators.
3. All predators are to act according to their status as predator, consuming prey regularly. If they are unable or unwilling to do this, they are no longer a predator.
4. Additional predators can be named by heads of staff or higher-ranking predators, or by consuming the head of staff or higher-ranking personnel, thus taking their role as predator, rank, and position.
5. Requests of prey must be approved by a predator before being acted upon.
6. All violations of spacelaw are now punished by being consumed by a predator. Assist security with this change, and enacting any punishments.
7. Protect both predators and prey from harm, however do not interfere with nature (e.g. a predator consuming prey, or a predator being supplanted by someone).
