### ISSUE TITLE
Secrets Panel or Different Permissions

### ISSUE THREAD

**Issue by Arokha** [SpadesNeil/VOREstation#111]
I lack +SERVER, so I'm not able to use the Events Management Panel because I cannot turn on Random Events in the first place. That would not be THAT big a deal, however... the secrets panel is super-broken. Bay does not update it. Maybe it needs a new nanoUI-styled look and to actually call the right procs?

Until then, alas, I cannot trigger lazy events.

**Comment by Arokha** [comment]
To be honest, maybe the Secrets panel needs to be rearranged into the same event groups as the random event panel, plus "Utility" events and "Fun" events that are the remaining ones like launching shuttles, and "everyone is retarded" respectively.

**Comment by SpadesNeil** [comment]
Secrets for events should be moved under "fun" in my opinion.

The panel its self is also outdated and bad, and needs to be done over. I did it over in the old server but have not in the new one.
