### ISSUE TITLE
AI Vore

### ISSUE THREAD

**Issue by Arokha** [SpadesNeil/VOREstation#112]
Hardlight holograms! Features should be:

Hologram can harmlessly nom, or harmfully nom (I think it's fair to cheat and just have it be brute/burn, aka treat it like normal vore. The hologram could adjust the temperature and compress inwards to do this). Obviously laws need to be obeyed.

Person gets dumped out of hologram if it leaves the area, or just digitized completely if they 'digest' (this would alter the fatal fluff messages the pred gets).

**Comment by SpadesNeil** [comment]
This is a feature we have wanted for ages but no one knows where to get started.

**Comment by Arokha** [comment]
Well, I can think of a few things that would need to be done.

1) Holograms need some particular AI verb to vore people.
They do not have the UI, due to their mobby nature. I think it could be a verb that just lists people within 1 tile of the hologram. I /also/ think it could eat them instantly. Realistically the hologram could just move to be AROUND them rather fast. But, also, I think this is fine in the same sense that the AI having access above and beyond anyone else on the station is fine, because it has laws to follow and any violation of this isn't just an IC offense, but an OOC offense of roleplaying.

2) The hologram should probably look different when full.
There are a few things that could be done, but perhaps the two easiest: either set up a size difference between hologram and prey (hologram grows one size bigger than prey if prey is normal or larger, or prey is shrunk to fit into hologram) and then have the prey follow the hologram on the same tile, or, just have a similar-color-but-more-opaque 'stomach ball' that appears in the hologram (can be separate entity, 'hardlight stomach' or something) that follows it around, sort of like a micro container. Those are the only two ways I can think of since the thing can assume anyone's appearance.

3) The following mechanics need to be coded:
> The vore verb itself
> The 'stomach-like' object, or, the size-changing mechanic
> Stomach or prey set up to follow hologram
> Prey is dumped out when hologram leaves
> 'Lethal' mode for corrupt-laws AIs. Leaves ashes?
> A 'release' verb (if necessary? could just unsummon hologram)
> The AI can inspect people now right? If not, they need to be able to.

**Comment by SpadesNeil** [comment]
I don't want to make it possible for the AI to transport people around while voring as a hologram. Although a sort of trap in the AI chamber that transports you into a synth-stomach might also be neat.

But we can't let the hologram vore people I think because the hologram can go through walls and shouldn't be abused as a teleporting mechanic. When the light turns off, it should drop you, but that also means risk of getting dropped in bad spots.

**Comment by Arokha** [comment]
Well, having vore in the AI core is silly, nobody can get in there, so eh.

I was thinking maybe the AI gets a 'hardlight' button. It gives them normal body physics.

I mean right now the AI hologram is not even a real thing, it's just an effect that follows the AI eye. So, clicking that button makes the AI into a real mob (changes the appearance slightly?) and then gives them normal body physics. No wallwalking or standing inside machines.

How's that?

**Comment by SpadesNeil** [comment]
That might work.

**Comment by nightwingthedragon** [comment]
You guys, this has been on my list for ages. Remember what I said about not wanting people to take over things that I'm doing on my list? Yeah, this is one of those things.

**Comment by Arokha** [comment]
I'm not sure it's fair to simultaneously say "I've planned on doing this but haven't for a really long time" and also "Nobody else can do it". That is silly and very anti-progress.

**Comment by nightwingthedragon** [comment]
My plans are simple:

+An endo option for holograms that allow them to carry around mobs or humans until the hologram de-rezzes or passes through a wall
+A tron-style digitiser beam that functions as a simple "vore laser" for the AI core
+Later, when I've figured it out properly, a new Z-Level where the AI gets spawn permissions - ergo, a virtual reality for its prey.

**Comment by nightwingthedragon** [comment]
I'm not sure it's fair to say "why haven't you done this yet" given the sheer number of things I've got to do on my list. If other people wanna make it, go for it, but at least consult me about my plans for the thing.

**Comment by Arokha** [comment]
Didn't say "Why haven't you done this yet", said "Why isn't anyone else allowed to do this"

Since we're 'not allowed' to use Trello anymore, do you have a list somewhere of your plans for everything

**Comment by nightwingthedragon** [comment]
Trello isn't being taken down, therefore my list remains there.

**Comment by SpadesNeil** [comment]
Well Trello isn't being used by anyone anymore, and this is why. You can get help from other developers here, while in Trello, you're on your own.

**Comment by nightwingthedragon** [comment]
Back to the topic of the feature, if you wanna take a crack at it, my checklist is above, but I'd really appreciate it if you'd keep in touch with me during the process of adding it so we can work on the mechanics of it together. I'd love to take a stab at it myself, but ideally I'd want someone who knows what they're doing who I can go to in the mean time.

**Comment by SpadesNeil** [comment]
This doesn't seem to be going anywhere. Closing for now.
