### ISSUE TITLE
CC Fax Reply Formatting

### ISSUE THREAD

**Issue by Arokha** [SpadesNeil/VOREstation#114]
These don't appear to get formatting parsed at all. All newlines are removed, and things like [logo] are not honored.

**Comment by SpadesNeil** [comment]
You need to use normal HTML for the CC fax replies. We could change this probably.

**Comment by Arokha** [comment]
I mean... pretty sure it would be reasonable to have it like writing any other piece of paper. All the pretyped forms and whatnot are formatted for that, so it seems sensible. Like if you faxed CC and ask for them to send you a copy of some form, would be nice to have that work.

Also as far as I know, nowhere else in the game requires you to know HTML so this seems odd.

**Comment by SpadesNeil** [comment]
Yea, it's not consistent. Let's change it.

**Comment by Leshana** [comment]
This is possible to do, basically in order to do it. Easiest way would be to create a virtual paper and pen, and just write it, then send that. 100% code re-use in that case.
