### ISSUE TITLE
Steal /tg/ Cloner Upgrades

### ISSUE THREAD

**Issue by Arokha** [SpadesNeil/VOREstation#116]
Leshana looked at their code and said this would be easy to port, so maybe assign to her.

/tg/ can upgrade both cloner and scanner, and at the highest level it adds features to the console itself connected to them, such as auto-cloning people who died.

Right now in Bay, only the pod can be updated, to produce less damaged clones.

**Comment by OrbisAnima** [comment]
I remember commenting that feature to players before we had the chat and it brought quite a discussion, maybe this one should go to forums firsts. The stronger arguments said, and with some reason, that it would take work from medics...

**Comment by Arokha** [comment]
I've talked to a lot of people about this. It seems like a lot of people are EXPECTING us to have /tg/ autocloners and are confused/disappointed when I tell them we don't. I've gotten questions about it when playing medical.

I also think the job it would take... it would only take on some shifts where R&D isn't lazy, and even then we already have the full-heal clone upgrade with Bay. The only thing it'd add is auto, really. So it's saving them from pushing a button?

It's possible people don't realize we already have the ability to upgrade to fullheal cloners.

**Comment by SpadesNeil** [comment]
I thought we already had that too.

Autocloner plus fullheal cloner would be very nice considering the nature of our station.
