### ISSUE TITLE
Emergency messaging.

### ISSUE THREAD

**Issue by Tasald** [SpadesNeil/VOREstation#117]
Currently only the captain can send an emergency message to cent com, I tried as HoP and couldn't. I feel like all heads should have this access at least because there's not always a captian on board. I also think that the HoP and HoS should be able to raise and lower the status to blue, for the same reason as there's not always a Captain on board, granted a hop can just give them self's the accesses, so its more for the HoS

**Comment by SpadesNeil** [comment]
I agreed with this notion.

**Comment by Arokha** [comment]
I would agree with the HoS being able to do it to blue without talking to people. They are implanted, and would probably be the first to know of a 'credible threat to the station'. I think red should still require cards or a captain though.

The messaging though... why? Why not just send a fax? Every head already has a fax machine, and there's one on the bridge too (breakroom).

**Comment by Tasald** [comment]
Red should require cards but it's in the wall card reader isn't it still?

For the messaging, it takes much less time, last time I checked there was no cool down on it either unlike the fax machine where you have to type it out onto a piece of paper, then put the paper in, then your id, then send it, and then either wait for five mins for it to re calibrate or go find another fax machine. During an emergency situation, there would be should be at least one head near or on the bridge, so if needed they could send an update to CC at will with out needing to run around the station looking for a fax machine if there was an important update. I know as HoS I typically stay on the bridge, its centralized and has both cameras crew monitor, and a fax machine which I admit, would be the first device I'd use to tell CC if I thought we might need help with something, but then the thing goes to hell faster then the fax machine can calibrate and I'm stuck wanting to be able to send them an emergency request right there with out having to run all the way back into sec, doging what ever's in the hall possibly, to get to the office and type out a message that I could have sent fast via the computer. This goes the same for any of th heads.

**Comment by Arokha** [comment]
It looks like heads were ALWAYS supposed to be able to set the alert level, based on what I see in the file for this, but their check to see if you're a head isn't working.
