### ISSUE TITLE
Mouse pai

### ISSUE THREAD

**Issue by Tasald** [SpadesNeil/VOREstation#119]
For the mouse chassy, would it make sense for it to be able to vent crawl and walk under people like a mouse, or lore wise is it to big? This would make the pai more mobile, and able to get out of a room if their owner got incompasataed and the needed to lead the rescue team to it.

**Comment by Arokha** [comment]
Ventcrawl code is missing, so that will be very difficult right now. Walking under people probably should happen.

**Comment by SpadesNeil** [comment]
pAI are not intended to be able to vent crawl. This is intentional.
