### ISSUE TITLE
RC Mouse

### ISSUE THREAD

**Issue by Arokha** [SpadesNeil/VOREstation#120]
So there's the pAI mouse. That's pretty neat. I want a remote-controlled one. For spyin'.

Little card thing, unfolds into mouse, and puts your ckey into it. You get a verb to drop out of remote control and resume control of your body. Maybe a remote controller object goes with this to put you back into the mouse?

**Comment by SpadesNeil** [comment]
This belongs on the suggestion section of the forum. Add it here after sufficient discussion.
