### ISSUE TITLE
Shrinkrays (and supposedly tasers) can open crates.

### ISSUE THREAD

**Issue by Arokha** [SpadesNeil/VOREstation#129]
Noooo. Just, nooo.

Bad. No, bad.

I'm told tasers do as well.

**Comment by SpadesNeil** [comment]
I think this is something that can be solved by the on_hit proc. I'll investigate.

**Comment by Arokha** [comment]
After further testsing, I tested both eguns and tasers. Tasers seem unable to open crates, and eguns on stun seem also unable to open them. Eguns on lethal can open them (makes some sense).
