### ISSUE TITLE
Shink ray knockdown

### ISSUE THREAD

**Issue by Arokha** [SpadesNeil/VOREstation#132]
So shrink rays have a knockdown chance, same as eguns it seems. Makes things a bit awkward sometimes? Or maybe it should be left in? Don't know. Reporting as a bug because it probably wasn't intended.

**Comment by SpadesNeil** [comment]
That sounds like the beam still does damage which is not intended.

**Comment by Arokha** [comment]
If they do cause damage, it must be very little and heal instantly. It definitely doesn't do egun level damage.

**Comment by SpadesNeil** [comment]
Does this still happen? It should not.

**Comment by Arokha** [comment]
Doesn't appear to still happen after a bit of testing. Wasn't 800 shots but, didn't happen after twenty or so.
