### ISSUE TITLE
Escape pods don't make sense

### ISSUE THREAD

**Issue by Arokha** [SpadesNeil/VOREstation#134]
So, some things are a bit more realistic with the pods in newcode...

They are locked during normal station operations: Good
They have a manual control panel onboard them now: Good

Some things make zero sense with newcode...

The escape pods are locked even when the shuttle has been called. What? That means it's time to leave. So they should unlock.

The manual controller has both an 'Arm' and a 'Manual Eject' button. The 'Manual Eject' button never is available throughout the whole process of the shuttle being called, arriving, and departing. Additionally, the pods automatically ARM when they unlock as the shuttle arrives. The "ARM" button also opens the pod door. This is silly as I can only get this to work if I turf-teleport myself into the pod to click it. The AI can also click this, but I know not to what avail since the pod can't be launched at any point until it would automatically launch.

This pair of buttons makes no sense. Escape pods should be able to leave when somebody pushes the "time to go" button. I think this button should be enabled after the shuttle is called.

Also it should probably announce over the radio when a pod is launched manually, so one can know not to go to that one, and also to stifle people from trying to sneak off with them.

Some of that might be considered 'suggestion' but, at the very least there's a bug with the Manual Eject button never being available.

**Comment by SpadesNeil** [comment]
Escape pods only function during emergencies. I've used them just fine during emergency shuttle calls. This is not an issue of the doors not opening. They are intended to stay locked when the shift is changing and the station is not exploding.

The pods will not automatically launch unless there is an emergency. Marking wontfix unless you verify this is not the case. I've used them before during emergencies though so I am not sure why they would stop working suddenly.

**Comment by Arokha** [comment]
I am talking about in emergencies. I know they do not go with the shuttle at shift-end. I manually called the shuttle 20 minutes into a shift, red lights flashing everywhere. I would think at that point the pods should unlock so people can actually get in, but they do not. For some reason they have to wait 10 minutes, then wait 2 minutes for the shuttle to launch for the pods to also launch.

The 'Manual Eject' button never works. It seems like in an emergency, you would want to be removing people from danger as soon as possible (as soon as the evac is called). You don't wait for every lifeboat to be loaded before launching any lifeboats, on a ship.

**Comment by SpadesNeil** [comment]
The manual eject button does work. It becomes available after the shuttle leaves and is intended to pick up stragglers who missed the shuttle.

**Comment by Arokha** [comment]
All the pods launch when the shuttle leaves, though. I just tested this. Just start a new game, and call the emergency shuttle. The pods all automatically launch, empty or not, when the shuttle leaves.

**Comment by SpadesNeil** [comment]
Fiiiine, marking as bug. :P

**Comment by SpadesNeil** [comment]
I just tested this too. The escape pod doors open when the shuttle arrives in an emergency.
