### ISSUE TITLE
Forks icons are wrong

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#136]
Sprites are wrong directions.

**Comment by Leshana** [comment]
What do you mean sprites are wrong?

**Comment by SpadesNeil** [comment]
They face the wrong directions.

**Comment by SpadesNeil** [comment]
Keeping this issue open because the directional icons are still wrong.

**Comment by nightwingthedragon** [comment]
Eating soup with a fork tested and confirmed in issue #196
