### ISSUE TITLE
Mobs don't have a vore panel

### ISSUE THREAD

**Issue by Arokha** [SpadesNeil/VOREstation#137]
Let's say runtime eats someone. I jump into them. However, no vore panel! Can't release people or see who's inside or anything. Whynaw?

**Comment by nightwingthedragon** [comment]
Because I haven't added it yet! And also because mobs don't currently have the requisite verbs or variables to necessitate an inside panel. Runtime eating micros is actually automatic, and would get annoying if played by an actual player. This is why I have a big mob vore update planned.

**Comment by Arokha** [comment]
Not sure what you mean. Runtime has an internal_contents stomach organ like every player does.

Also Runtime does not seem to eat any micros automatically, just leer at them. I spent like ten minutes as a micro with Serkii in the CMO office and she didn't eat either of us, just made lewd stares. That's another issue though.

**Comment by nightwingthedragon** [comment]
I believe the chance was lowered due to how frequently it was happening before, but I can look at it again soon.

**Comment by SpadesNeil** [comment]
Is this still relevant?

**Comment by SpadesNeil** [comment]
@Arokha this is covered by another issue, I believe. Correct?
