### ISSUE TITLE
Full-size Reinforced Windows Suck

### ISSUE THREAD

**Issue by Arokha** [SpadesNeil/VOREstation#144]
Cost of single reinforced glass pane: 1 reinforced glass
Cost of fullsize reinforced glass window: 4 reinforced glass

HP of single reinforced glass pane: 40 HP
HP of fullsize reinforced glass window: ... 40 HP

Why does it take more glass, and is bigger, yet, is just as easy to break as the small one? It's like a square meter of glass vs 3" of glass. At least give it 80 HP, if not 4x due to the cost?

**Comment by SpadesNeil** [comment]
4x health seems reasonable to me.
