### ISSUE TITLE
suit storage slot incorrectly uses item_state instead of icon_state

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#145]
Suit storage slot gets sprites from belt_mirror.dmi, but for some stupid reason, it reads the variable for the icon from item_state instead of icon_state, which causes incorrect icons to appear!

I'm not sure where this is fixed. Perhaps @ShadowLarkens might know. It should be one simple change; I just can't find it!

**Comment by Leshana** [comment]
Can you give an example of what items cause this?  A way to reproduce it so it can be confirmed as fixed when testing.

**Comment by SpadesNeil** [comment]
If I am wearing a suit of armor, and I wear an item such as a double-barrel shotgun on my back, because the item_state is simply "shotgun", it incorrectly appears on my back using belt_mirror.dmi's sprite labeled "shotgun" instead of "dshotgun", and "dshotgun" is the correct icon_state.

This is inconsistent with all other wearable items in the game, which follow icon_state, and not item_state. item_state is only for what appears in your hands like a weapon held on your character.

**Comment by Arokha** [comment]
This doesn't appear to be the case anymore. It uses icon_state.
> overlays_standing[SUIT_STORE_LAYER]	= image("icon" = 'icons/mob/belt_mirror.dmi', "icon_state" = "[t_state]")
