### ISSUE TITLE
GPS Are Missing

### ISSUE THREAD

**Issue by Leshana** [SpadesNeil/VOREstation#154]
The little handheld GPS thingies are missing from the game! They were removed along with telescience.
These things have utility beyond telescience, and are important safety devices.

**Comment by SpadesNeil** [comment]
Well that's stupid. I'll see about re-adding them.

**Comment by OrbisAnima** [comment]
Add them to mining!

**Comment by Leshana** [comment]
Oh! I actually added them to the game.  I just have not added them to the map or anything because I've not acquired the map mutex.
