### ISSUE TITLE
IPCs can't repair themselves.

### ISSUE THREAD

**Issue by bear-irl** [SpadesNeil/VOREstation#158]
IPCs are unable to weld themselves (or repair burns with cables, I assume, but I haven't been burnt) since the update, it seems. They used to be able to, and, while borgs having to rely on a roboticist or other carbon makes sense because no arms, IPCs are arguably sentient and have arms and shouldn't have to hunt down someone else to weld them.

The message when attempting to repair yourself as an IPC:
You can't repair damage to your own body - it's against OH&S.

**Comment by SpadesNeil** [comment]
We're debating if this should indeed be fixed, because otherwise IPCs become their own walking medbays when they can very easily repair damages to themselves that would otherwise cripple a human.

**Comment by nightwingthedragon** [comment]
To be fair, that's only about the same issue as a human walking around with a beaker of DD and a syringe. If they start in medbay, it's easy to get hold of. Likewise, an IPC starting in robotics or engineering can easily get hold of the tools to repair itself. I don't see why this shouldn't be re-added.

**Comment by SpadesNeil** [comment]
That is a fair argument. Very well. It will be fixed. Eventually(TM).

So anyone who wants to mess with it, have at it. I might do it later today if I do some coding.
