### ISSUE TITLE
IPCs and genetic damage from slimes

### ISSUE THREAD

**Issue by ursamedium** [SpadesNeil/VOREstation#159]
I don't really know what to say about this or if it's something that can be repaired.
Prior to update, IPCs took general damage from slimes. Now they seem to take invisible genetic damage (no genetics to damage) that they can't count or feel and nobody else can see or repair and eventually if they are unaware of it they will simply suddenly die. Everyone else will see a perfectly healthy looking but dead IPC. There's no surgery or anything to be done on an IPC corpse so it just.. is dead.
Had this happen when I was playing my IPC in sec and helping handle a massive slime outbreak, assumed I would just get damage welded off if it got too bad but just sort of suddenly died to the confusion of many. 
(At the time it was agreed that CentComm was to send a replacement model in and I was to wait a few minutes after respawn timer and then spawn back in, as a 'solution', though my dead self was on the manifest the rest of the round.)

**Comment by SpadesNeil** [comment]
Well that makes no bloody sense. God damn it Bay. Yes, this is a nasty issue. We'll attempt to change it. I'm thinking fire damage, because slimes have electrical properties that could short-circuit the IPC's components when glomped.

**Comment by SpadesNeil** [comment]
Marking as important because it otherwise totally restricts IPC characters from doing Xenobio.
