### ISSUE TITLE
Window Tint / Shutters for QM Office

### ISSUE THREAD

**Issue by ursamedium** [SpadesNeil/VOREstation#160]
Most (all?) other office areas with a window have a button for window tint toggle or shutters for privacy.

Have seen some people having a scene in the QM office a few times now when I walk up for an order or whatnot and think the QM office not having that as an option is a pretty big oversight.

~~(Swear this is my last issue I'm submitting tonight)~~

**Comment by SpadesNeil** [comment]
I believe this was added. I forgot to close this.
