### ISSUE TITLE
Research Outpost SMES

### ISSUE THREAD

**Issue by Arokha** [SpadesNeil/VOREstation#162]
It does not even last half a shift. I'm all for making things require player upkeep but uh. This might be a bit of a thing. Can power consumption be reduced? Add more lightswitches and have them start off?

**Comment by SpadesNeil** [comment]
No it can't be reduced, but the starting power can be buffed.

**Comment by FirstSgtDan** [comment]
Or add a bigger stock of Phoron sheets for people to throw at those PACMAN.

**Comment by SpadesNeil** [comment]
All set in current version, plus we have a solar array now.
