### ISSUE TITLE
[Serious Bug] Shock from machines in Z level 7 causes crashing for all clients until shocked player disconnects.

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#165]
I have consistently reproduced this issue with airlocks and vending machines. I'm still trying to figure out why it's happening. Any time a shock is produced, even if you have gloves, the game immediately freezes until all players disconnect and it's given a few moments to recover. Logging back in displays sparks on the floor.

I had Scree connect to the server to see if it remains frozen after the player who got shocked disconnects.

The server hangs frozen until the shocked player disconnects, and then it continues playing. If the shocked player does not disconnect, the server remains frozen.

A wild guess, but I believe the server is getting caught in some kind of loop because it's trying to send a message to the client, and somehow, it's never getting beyond that step. The client disconnecting causes it to apparently give up and break that cycle, allowing the server to resume being playable.

**Comment by Screemonster** [comment]
From my end (walking around the corridors in Z1), the server simply stopped doing anything as though experiencing a lagspike. The connection came back with no further issues when Ace disconnected.

**Comment by nightwingthedragon** [comment]
Could this be to do with an infinite loop glitch somewhere, perhaps?

**Comment by SpadesNeil** [comment]
Removed "This crash bug has only so far been reproducible in areas with "requires_power = 0" at server start. Changing these variables mid-game seems to have no effect on resolving the crash."

I changed this variable and it still crashed.

I am wondering if the sheer number of doors and equipment in the area is having a negative impact on performance.

**Comment by SpadesNeil** [comment]
Nope. Reduced to 3 airlocks. Still having issues.

I now believe the freeze happens because the area is just too friggin huge. To ensure it wasn't the type of area being used, I changed it, but the problem still happens.

**Comment by OrbisAnima** [comment]
Maybe it has to do with the powernet in that area? I mean, does this has a real power apc somewhere? or just use the infinite powercell?

**Comment by SpadesNeil** [comment]
Made no difference. I added an APC and made it powered.

**Comment by OrbisAnima** [comment]
Wild guess here, try surrounding the place with reinforced walls, at least the shocking area, you should be able to use the CE's stations plans on it, then try it again, making sure that if the area is unpowered the door can't be open

**Comment by SpadesNeil** [comment]
I recompiled the map with a different area and it still happens.

However it does not happen in the smaller "cave" area.

**Comment by SpadesNeil** [comment]
My "fix" was done by splitting the larger area into smaller ones, and now it functions as intended.

It's still not ideal though, but I can't fix this now.
