### ISSUE TITLE
Xenomorphs icon updating broken

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#166]
When you rest as an alien, you just fall sideways on the floor. Alien sprites do not appear to update correctly anymore. They used to change with stance, even running or walking.

We used to have this super adorable sleep sprite and either bay removed or broke it. :\

**Comment by Arokha** [comment]
I remember the super-adorable sleep sprite!

**Comment by nightwingthedragon** [comment]
Bay has re-classified xenomorphs as humans, and therefore xenomorphs now use the human code for resting. It'd be a simple "if" statement in update_icons to patch the resting, but I don't know about changing stance.

**Comment by SpadesNeil** [comment]
The good news is our vore code works with the xenomorphs, and we no longer have problems biting monkeys trying to eat them. I think digestion has also been corrected with them.

**Comment by Arokha** [comment]
This appears to be a thing defined by each species, in the "prone_icon" variable. There's even accounting for it in update_icons.dm to NOT rotate the sprite if the "prone_icon" is set to something.

... then "prone_icon" is never used again. Nope. Not used a single other time other than the define file for /datum/species where it's declared as null, and then a single check in update_icons.dm where we don't rotate if it's set. It's never actually ... applied to the sprite or anything.

**Comment by SpadesNeil** [comment]
So it's an easy fix?

**Comment by SpadesNeil** [comment]
https://www.dropbox.com/s/uvxo397lbn7f8c5/update_icons.dm?dl=0 This is how the update icon file used to look in the old code.

**Comment by Arokha** [comment]
I'll look at this.

**Comment by Arokha** [comment]
I see why they don't have sleep sprites now. They went from being single-icon mobs to having a whole set of icons like the human races. So having them rest with their old icons might be possible, but it might look odd. If they were missing their hands or legs or something they'd suddenly be back, also wounds would stop showing while resting. I'd just have it stop drawing their hands, legs, head, torso, etc and just draw the single rest icon.

If this is what you want, I can see about doing it.

**Comment by SpadesNeil** [comment]
So just to clarify, they'd have the damage icons disappear when laying down. That's fine by me. I want my cute sleepy xenos back. :c

The limbs being missing is also an issue but that's such a rare issue I don't think it should be worried about currently. If the limbs magically re-appear when laying down, I don't mind.

**Comment by SpadesNeil** [comment]
Won't fix because this will be handled in the new code.
