### ISSUE TITLE
Aliens can use shuttle controls.

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#167]
This shouldn't be a thing.

**Comment by nightwingthedragon** [comment]
TBH, I don't see why not. There's never going to be any player xenos with access to that sort of thing who aren't admins, and we may decide to use it for an event at some point. I see no benefit to removing it.

**Comment by Arokha** [comment]
The dragon has a point. I also assume you meant Xenos specifically, as everybody but humans are classified as 'aliens'.

**Comment by SpadesNeil** [comment]
It's just a fine-manipulation check which exists for the same reason xenos can't use guns.

I don't want xenos restricted purely to admins. I want to allow players to participate in events like I did last night. That means preventing them from doing things they shouldn't be able to.

I consider it a bug but if you guys want to allow xenos to use shuttles I'll mark it as wontfix (or one of you can).

**Comment by Arokha** [comment]
If xenos have hands, they can do the same stuff people with hands can do. So, all the attack_hand procs that humans call when they mash their fists on consoles, carbon xenos can call too.

**Comment by SpadesNeil** [comment]
Xenos should be made unable to use computers.

**Comment by SpadesNeil** [comment]
Fuck it.
