### ISSUE TITLE
Satchel clips through spiderbutt

### ISSUE THREAD

**Issue by AliciaJewel** [SpadesNeil/VOREstation#168]
If you're a spidertaur with a satchel, the satchel will clip through your spider half if you're facing north as shown here: http://puu.sh/kPqRq/96e35a063f.png

**Comment by nightwingthedragon** [comment]
Not sure this issue can be fixed since the tail layer is apparently below the satchel layer for... Some... Reason. I'll look into it at some point.

**Comment by Arokha** [comment]
This is indeed what the issue is. You can swap the layers but then you end up with wings being rendered ontop of back items and other stuff. Basically you trade graphics glitches for other glitches. Maybe worth it though? Dunno. Could also tweak the spider sprites.

**Comment by SpadesNeil** [comment]
plz fix looks horrible

**Comment by SpadesNeil** [comment]
Was "fixed"
