### ISSUE TITLE
Mute (R)LOOC for Admins

### ISSUE THREAD

**Issue by Arokha** [SpadesNeil/VOREstation#170]
For the love of god, please. This is probably easy? Just a guess. BUT AAAH PLEASE. Just add a button for it!

**Comment by nightwingthedragon** [comment]
No idea how easy it is, but agree that it's important. However, (R)LOOC is, in some ways, more important to have on all the time because it's things that people say when they think nobody can hear them. Albeit rarely, it can catch meta-ing and such. I personally use it more frequently to help people with their in-game problems.

**Comment by Arokha** [comment]
I do too, but when people start doing squick things in LOOC and I basically have to sit there and read it while it spoils my mood, I'd like to be able to mute it for a few minutes.

**Comment by SpadesNeil** [comment]
fuck yes please have the ability to turn off remote LOOC.

**Comment by Leshana** [comment]
This issue cannot be properly implemented until we upgrade to Byond 509.1306 due to this bug which prevents using bitflags larger than 0xFFFF:  http://www.byond.com/forum/?post=1959790

**Comment by Leshana** [comment]
Implementing this properly will require us to upgrade to byond 509.1306 due to this bug: http://www.byond.com/forum/?post=1959790

**Comment by ShadowLarkens** [comment]
Well, not really, @Leshana , there are ways around that. Namely making a new flags variable on clients, which will be necessary if we ever want more than a single remaining pref.

**Comment by SpadesNeil** [comment]
Or we could just wait until 509.1306 comes out. Then fix it.

**Comment by Screemonster** [comment]
It wasn't so bad before the population explosion, but now we have biggish groups of people using it for actual OOC conversations as well that would be suited to the chat. It gets waaaay too spammy to pay attention to a scene.

**Comment by nightwingthedragon** [comment]
We could keep the forced (R)LOOC in as an incentive for admins to get people to join the chat! :P

**Comment by Arokha** [comment]
Leshana's fix makes it default to on every shift, so you have to turn it off whenever you NEED to rather than just turning it off for fun and leaving it off forever.

**Comment by SpadesNeil** [comment]
Yea, I want (R)LOOC to appear by default and turn it off only when spammy.

**Comment by Arokha** [comment]
This is in, from #184
