### ISSUE TITLE
UI customisation coloring is bad

### ISSUE THREAD

**Issue by nightwingthedragon** [SpadesNeil/VOREstation#173]
UI customisation is only per-character now instead of per-player. Not sure if that will need changing, but it's annoying trying to set each and every one to be how I want it.

Further, the intent box at the bottom-right renders strangely now when coloured. In the past, the green, blue, yellow and red would render over the colour, but now they seem to be underneath it, which results in weird blending.

**Comment by SpadesNeil** [comment]
I don't think these are issues. The ability to customize your UI per character is good for setting the mood of that character, and sounds like a deliberate feature.

The second issue, I've never noticed that problem.

Marking as wontfix for now.

**Comment by nightwingthedragon** [comment]
It's just annoying for me when you load up a new character, then suddenly realise you've forgotten to set the UI and do it in-game, and then forget again the next time.

As for the second issue, I'll attach a screen, because it certainly is a problem. It'll come in the next post.

**Comment by SpadesNeil** [comment]
Ooooohhhh I see. Okay yea. Taking away wontfix.
