### ISSUE TITLE
Sec Officer Limit

### ISSUE THREAD

**Issue by Arokha** [SpadesNeil/VOREstation#175]
The limit is two, less than the old server, and I keep having to open more slots for sec officers since this makes it a hard 5? 6? Limit on people in sec. 1 HoS, 1 Warden, 2 Sec Officers, 1 or 2 Detectives. Thasabboutit.

**Comment by SpadesNeil** [comment]
The original limit was 5. I nerfed it to 3 with the introduction of Blueshield. Blueshield is gone now. It should be at least 4.
