### ISSUE TITLE
Rigsuit Sprite Differentiation for Species

### ISSUE THREAD

**Issue by Arokha** [SpadesNeil/VOREstation#176]
Ok so there are two paths for sprites that I care about:

icons/obj - used for inventory sprites
icons/mob - used for on-character sprites

Under icons/mob/clothing and icons/obj/clothing we have a 'species' folder where override sprites can be stored based on species.

For rigsuits, only icons/mob/clothing/species is used, and icons/obj/clothing/species is ignored.

What I mean is, if you have a rigsuit that has ears when worn by a tajaran, the character sprite works fine, however the inventory sprite will be the normal human one.

**Comment by SpadesNeil** [comment]
I don't understand the issue.

**Comment by Arokha** [comment]
There are two sets of sprites, the ones for the little icons bottom-left when you're wearing the 4 pieces of a rigsuit, and then the on-character models.

There's a whole set of per-species sprites for both, but the bottom-left inventory icons that are species-specific are ignored. I assume it's an oversight that never came up because Bay doesn't have any species-specific rigs. I added the first one that looks different depending on your species.

The 'human' sprites get used regardless of who are wearing it, for the inventory items. The on-character sprites work properly.

**Comment by SpadesNeil** [comment]
I don't quite see the issue with this being the case, when they are inventory icons that will never be seen outside of one's inventory. I wouldn't waste time fixing this.

**Comment by Arokha** [comment]
It's a bit disconcerting when the onscreen one has big cat ears and the one in your inventory doesn't, but alright.
