### ISSUE TITLE
More uses for duct tape

### ISSUE THREAD

**Issue by Arokha** [SpadesNeil/VOREstation#183]
Enhancement!

Tape should do more. It should work as a muzzle and shitty 15-second resist cuffs!

Make it do a little HALLOSS when someone with fur (Taj, Srg) removes it! Ow, fur+tape. D:

**Comment by SpadesNeil** [comment]
I actually really like these ideas.

I already made tape a usable ingredient in building makeshift shotguns (which can potentially explode and horribly injure you).

**Comment by HawkerTheGreat** [comment]
I'd actually like to look at the tape functions if someone can give me a idea to where it's located.

**Comment by SpadesNeil** [comment]
It's less about the tape's functions, more about the objects it affects.

For instance, my pipegun code checks if you hit it with an object. If it's tape, it can do a thing. The tape doesn't check if it's hitting the pipegun.

**Comment by SpadesNeil** [comment]
Better discussed on forums.
