### ISSUE TITLE
Loyalty implants STILL not being applied at round start

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#187]
Only happens to HoP and Internal Affairs agent. This is not correct. Both should be implanted.

**Comment by Leshana** [comment]
That's because the return statement is in the wrong place.

**Comment by SpadesNeil** [comment]
oh derp

**Comment by Leshana** [comment]
Is dis fixed?

**Comment by Arokha** [comment]
This is fixed.
