### ISSUE TITLE
Indicator on HUD when you're picked up and turned into an object item thingie?

### ISSUE THREAD

**Issue by silveryferret** [SpadesNeil/VOREstation#190]
Just like... yanno, something on the HUD when you're being carried, or stuffed into a bag. Little indicator in the corner of the screen or something? Is that doable? I keep peeking over as I'm being carried around and like, it'd be really nice to just have something to glance at to see if I'm able to move of my own volition or if I'm being carried/in a bag/inside someone

**Comment by nightwingthedragon** [comment]
This is an interesting and good idea, methinks. I'm not sure how to do it myself.
