### ISSUE TITLE
Ghost ears is too easy to spam with several mobs.

### ISSUE THREAD

**Issue by OrbisAnima** [SpadesNeil/VOREstation#191]
It would be nice to add an option to mute the mobs as a ghost, but still keep the people chat. I believe this would be more of use to admins, but it's certainly helpfulp for those of us that observe the game when we can't join.

**Comment by Arokha** [comment]
I'd say we just always assume mobs only are heard when on-screen. Why would you care what mobs are saying in the distance? They are computer-controlled, say the same things over and over, I'm not sure what the benefit would ever be of hearing them far away.

**Comment by OrbisAnima** [comment]
Well, there is an interesting easter egg with the slimes, wich activates in a one in a millon chance, but aside from that, yeah, we don't have a really good reason to hear them everywhere

**Comment by Screemonster** [comment]
I can imagine this being hell if Scree sets off another stationwide monkeybombing campaign. The radio spam from the oblivion drones is annoying enough as a ghost.
To avoid complications with player-controlled mobs (rare as they are) maybe look for a ckey? If it's null then only send the messages locally.

**Comment by nightwingthedragon** [comment]
Isn't there the option to simply set your ghost ears to only show you local emotes and speech? Either in Ghost or in Preferences.
