### ISSUE TITLE
Prey in bellies!

### ISSUE THREAD

**Issue by nightwingthedragon** [SpadesNeil/VOREstation#197]
Whispers still can't be heard by predators! Prey can't privately whisper things to their predator. This should be a simple enough fix by checking whether the player's location is another player (or a micro holder object) and then if so, broadcasting the whisper from the mob holding it, or even just to the mob holding it and anyone else in its tile.

**Comment by SpadesNeil** [comment]
The bit about squirming is referenced in #99 but the rest is valid.

**Comment by nightwingthedragon** [comment]
Updated, then!

**Comment by Arokha** [comment]
Whispers fixed in #228, squirming covered in #99.
