### ISSUE TITLE
Bees kill plants

### ISSUE THREAD

**Issue by nightwingthedragon** [SpadesNeil/VOREstation#210]
```Someone add "bees kill plants" to the list of bugs. >_<;```

I did it! :D

**Comment by SpadesNeil** [comment]
Bay removed bees because Bay are assholes. We can't use bees right now. I'm not sure how to correct this.

**Comment by OrbisAnima** [comment]
There is also the chance the new Xenoflora code sent everything in the air, I will look at it eventually, but I don't see it as an easy change, maybe I am wrong though
