### ISSUE TITLE
New UB TF Options

### ISSUE THREAD

**Issue by Kligor** [SpadesNeil/VOREstation#224]
With the addition of Taur and Demi being genetics is it possible to have a new setup for UB that you can set it to 
Small Change:
-Hair color
-Skin color

Medium Change:
-Sex

Large Change:
-Demi
-Taur

All depending on the pred?

**Comment by SpadesNeil** [comment]
I'd be happier if we had like a checklist to determine what gets changed.

**Comment by SpadesNeil** [comment]
This was added recently by #406.
