### ISSUE TITLE
Can't use vore interactions with Cyborgs

### ISSUE THREAD

**Issue by OrbisAnima** [SpadesNeil/VOREstation#226]
You can't grab them, or grab yourself, even using a third party only hits the cyborg. Finally, using a micro and feeding it to the cyborg uses the micro as a weapon.

We could make a module that allows such an interaction, but I am not 100% sure on how to implement it. @nightwingthedragon ?

**Comment by SpadesNeil** [comment]
I don't think it's a good idea to let actual cyborgs do vore--or eating cyborgs. I actually quite dislike the idea.
