### ISSUE TITLE
IPC overheat if wearing clothing

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#23]
From the forum:

IPCs overheat if they're wearing either too much clothing or certain clothing, not sure which. My usually-warden IPC was getting super hot in the warden coat, I had to swap to the vest, which is both not as awesome looking and not as immediately identifiable as 'warden'.

**Comment by OrbisAnima** [comment]
It is not intended? I mean, they have already a mod of 50% brute damage reduction, and they are not whitelisted, they don't feel pain, can go to space, don't bleed..

**Comment by SpadesNeil** [comment]
I have to test it for myself but this was a complaint of them overheating ridiculously.

**Comment by ShadowLarkens** [comment]
Alright, so, I did find the cause of this, and it's not an easy fix.

Basically, the standard 'okay burn nutrition to stabilize body temperature' stuff, (human/life.dm, 783) doesn't happen for IPC's. They just have `10` added to their body temperature every life tick.
Normally, `handle_environment()` (human/life.dm, 661) would see that the normal station air is colder than them, and calculate cooling, just enough to keep them stable. However, it does not apply this cooling if they are wearing armour that protects against cold. All subtypes of `/obj/item/clothing/suit/armor` have the cold_protection flag UPPER_TORSO|LOWER_TORSO; So, with that factored into the cold calculations, IPC's stabilize at a very high temperature with armor on.

Problem is, none of this is easily fixable; The easiest solution would quite literally be to just remove the entire IPC heating system and let them behave like normal humans.

**Comment by OrbisAnima** [comment]
I will support you there, let's remove the heating and remove the brute damage reduction, that's fucking insane and it will invite abuse

**Comment by SpadesNeil** [comment]
Fuck it. Remove the whole heating system, yea. Remove their brute damage perk to balance it.

I'm willing to let them keep their ability to survive without air. They can't be cloned so this is balanced already. Balanced enough for us.

**Comment by OrbisAnima** [comment]
Roger, I will look into it since I been dealing with species code a bit too
