### ISSUE TITLE
Taur sprites misaligned when sprite icons are updated on macros or micros.

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#231]
This has been a longstanding issue for quite some time now. Whenever your icons are updated putting on a suit or calling update_icons through the view variables menu, if your character is anything beside the default playerscale, your taur body gets misaligned with the rest of you.

This obnoxious bug has been in the code since we added taurs and no one has fixed it yet, so I'm putting it here.

**Comment by nightwingthedragon** [comment]
It's something to do with when update_tail() is called; since taurs work on update_tail(). I'm thinking perhaps tails don't update when update_icons() is called, which would be dumb, but unfortunately apparently true. But if that's not it, I don't know what is.

**Comment by SpadesNeil** [comment]
@Arokha want to check this out maybe? Or @Cameron653 ? This has been a long standing bug that no one has been arsed to fix.

**Comment by SpadesNeil** [comment]
Worsened to Blocker because this is preventing me from finishing the vore mob code.

**Comment by SpadesNeil** [comment]
update_clothing_icon() is the source of the problem.

**Comment by SpadesNeil** [comment]
regenerate_icons() also causes this bug.
