### ISSUE TITLE
Jukebox as ambience

### ISSUE THREAD

**Issue by HawkerTheGreat** [SpadesNeil/VOREstation#238]
![capture](https://cloud.githubusercontent.com/assets/9869250/10749677/335f70a4-7c3b-11e5-8a24-72ea15240fda.PNG)

**Comment by nightwingthedragon** [comment]
Not sure if this is an issue, or intentional!

**Comment by HawkerTheGreat** [comment]
Let me explain a bit more. Its not so much of a big deal, but the way the jukebox works is it sends ambience to the client, so when you leave the range of the source, it cuts out the sounds. This is fine and all, but when you re-enter the area... Ambience won't let you hear the radio until it makes a full loop. - Therefor if you enter and exit the bar, you won't be able to listen to music unless you restart it.

// Or I'm pretty sure thats how it works. (Also, Radio can be disabled via toggle ambience button. Is this intentional???)

**Comment by SpadesNeil** [comment]
For some reason the ambiance works fine when I use the jukebox at CentCom. The music starts playing again if you re-enter the area.

I only had this happen once though and have not tested it since.

**Comment by Leshana** [comment]
I know why this happens.  It is because of the dynamic lighting areas, in which case the mobs are actually entering new areas in which the ambiance is not set (the areas auto-generated by the dynamic lighting system).   I have a fix for this which I didn't merge because I didn't feel like doing stuff that day.

**Comment by SpadesNeil** [comment]
plz fix

**Comment by Screemonster** [comment]
It'd be nice to be able to turn the jukebox _specifically_ off with a toggle anyway, a few people have asked for it.

**Comment by SpadesNeil** [comment]
@Leshana is this fixed in the Polaris version? If so, I can close this.

**Comment by Arokha** [comment]
It is fixed in the Polaris one. She fixed it a couple of days ago.
