### ISSUE TITLE
Invisible Players

### ISSUE THREAD

**Issue by LunaruF** [SpadesNeil/VOREstation#242]
So as far as I've experimented with, when you go into character settings and select a size and cancel, your size will be set as blank. Upon joining the game with a blank scale, you will be invisible. How invisible? Well, you're technically extremely small to impossibly be seen, but you also can't even see yourself when you click to observe what are on tiles. Further experiments are needed to see how abusive this can be, such as being able to avoid damage and etc.
At the moment at best it could be used as a big nuisance as, well, obviously invisible players aren't so great when you can't even find them on the tile.

**Comment by Arokha** [comment]
There's a fix for this being applied next update.
