### ISSUE TITLE
Spawn items into medkit

### ISSUE THREAD

**Issue by Arokha** [SpadesNeil/VOREstation#247]
If you roll a doctor, it seems that it puts fluff items in the medkit you start with rather than the satchel.

**Comment by nightwingthedragon** [comment]
The code is probably searching for the first available container, and since the medkit spawns in your hands, that'd be it. Can we make it so it searches only for satchels and backpacks?

**Comment by SpadesNeil** [comment]
I think this can be fixed if we just change the order in which things spawn in the job/medical.dm file.

**Comment by SpadesNeil** [comment]
This is such a minor thing.
