### ISSUE TITLE
Ghost Charity! Gib ghosts all your stuff!

### ISSUE THREAD

**Issue by Treasa729** [SpadesNeil/VOREstation#248]
While observing, you still come up in the menu for people to give items to, so please help someone who has nothing out and give them some food or change, these ghosts don't even have a body! D:

**Comment by SpadesNeil** [comment]
Pfft well that's silly.

**Comment by Arokha** [comment]
This doesn't appear to be easily fixable. The only way it seems to fix this would be to remove the right-click 'Give' option on people. It APPEARS to be that this can work one of two ways:

1) Be a verb on all mobs in 1 range, allows right-click or typing verb and getting list.
2) Be a verb on you that shows the choice list every time, no right-click menu.
