### ISSUE TITLE
Issues with forcefeeding

### ISSUE THREAD

**Issue by Treasa729** [SpadesNeil/VOREstation#252]
It seems that people can no longer force feed you once you reach a certain threshold of food, even if you'd still be able to eat by yourself! D:

**Comment by SpadesNeil** [comment]
I thought I disabled that threshhold! Unfortunately I'm busy right now so I can't do any SS13 coding but I'm sure someone else will fix it.

**Comment by Arokha** [comment]
This is done. Fixing some other things before making the PR.
