### ISSUE TITLE
Micros as ID

### ISSUE THREAD

**Issue by Treasa729** [SpadesNeil/VOREstation#272]
I think it would be awesome if it would be possible to use micros as ID for when opening airlocks, that way when you pick someone up, you don't necessarily have to take their ID off to be able to move around in their department and such! Is there some way to use whatever access the micro would have at the time (So what they'd have access to if they just walked at an airlock) and give that access to the macros holding them as well when macros hold them in hand? (or possibly in the ID slot :P) I think that'd be awesome for snatch styled stuff, heh.

**Comment by Arokha** [comment]
This is done. Fixing some other issues before making the PR.
