### ISSUE TITLE
CC Rep/Obs/Adm HUD Icon

### ISSUE THREAD

**Issue by Arokha** [SpadesNeil/VOREstation#274]
There's a nice new NT icon for people but not for our custom jobs. Need to apply the NT icon to these jobs for the hud instead of the dumb unknown questionmark.

**Comment by SpadesNeil** [comment]
This cannot be fixed with how the system currently handles alt title jobs. The whole system needs to be gutted. Marking as wontfix, because this involves more than a single patch. It involves redoing the entire code of how hud glasses work.

**Comment by Arokha** [comment]
I'm cool, so I'll fix it anyway without doing that.

**Comment by SpadesNeil** [comment]
Nevermind I'm a doof.
