### ISSUE TITLE
Stuffing micros inside shoes

### ISSUE THREAD

**Issue by Dhaeleena** [SpadesNeil/VOREstation#280]
I would LOVE the ability to put micros inside footwear, maybe by adding a slot to the footwear were only micros are allowed or being able to add a micro to a shoe like it was an accessory like a medal to a jumpsuit, they should not be able to be spotted by just examining the person like you would to see a medal.

**Comment by Arokha** [comment]
I like this idea.

**Comment by FirstSgtDan** [comment]
I support this!

**Comment by OrbisAnima** [comment]
Same comment than in insole, you will need to make shoes containers

**Comment by Arokha** [comment]
Aaaaaargghhhhh I hate this but I'll do it. :v
