### ISSUE TITLE
Holsters fit in pockets

### ISSUE THREAD

**Issue by Arokha** [SpadesNeil/VOREstation#283]
You can put a gun in them first, which does NOT fit in pockets. Things that hold things bigger than slot shouldn't themselves fit in that slot.

**Comment by Arokha** [comment]
In looking, I'm unable to replicate this. The game actually has logic to prevent this when you holster a gun:
> w_class = max(w_class, holstered.w_class)

Closing, as in testing, I can put a holster in a pocket, put a gun into it, then no longer put it into a pocket, as would be desirable.

**Comment by Arokha** [comment]
Found a related issue, which is that you can put a holster into a pocket first, then put a gun into it. You can't take the gun out without putting it into your hand first, though.

**Comment by SpadesNeil** [comment]
The w_class for holsters should be 3 anyway.
