### ISSUE TITLE
Taur Clothing!

### ISSUE THREAD

**Issue by Treasa729** [SpadesNeil/VOREstation#289]
While we now have socks for most people which is awesome, I think it'd be really good if we could have an option for taurs as well! As of right now, there still isn't really any clothing for taurs, including the new option for socks and such, so I think it'd be nice if we could actually have options for clothing on taurs! I was initially just thinking about stuff like socks, but possibly stuff like saddles which could let people who are the same size ride taurs around rather than having to be micros, or just general clothing which also affects their taur body instead of just their anthro/human portion!

**Comment by Arokha** [comment]
This would require a lot of sprite work. It'd be basically impossible to make all clothing have a taur version, but if you wanted to have like FOUR pieces of taur clothing, okay. But they would need sprites for each type of taur (the canid looking one, spider, naga, etc). Will you sprite them? :P

**Comment by Treasa729** [comment]
I would, sadly when I last tried spriting, I failed miserably xD I might be able to give it a shot again, but last time I spent like three hours and only got a crappy outline and a half filled in sprite that got scrapped. I doubt I'd be successful, and anything I made would probably end up looking abhorrent :P

**Comment by Treasa729** [comment]
But I definitely didn't mean an option for all clothes, just possibly accessory style items which could be added to also cover taur bodies with some basic clothing or something

**Comment by nightwingthedragon** [comment]
I can't even begin to picture how clothes would look on taurs! All I can think of is this picture!

http://d.facdn.net/art/silverfox5213/1435074107/1435074107.silverfox5213_commission_fore_shaypup_fa.jpg

**Comment by SpadesNeil** [comment]
Custom taur clothing isn't really something I can think of a good way to figure out. Gonna mark as wontfix and come to this maybe some other day.
