### ISSUE TITLE
Species whitelist logic is fucked

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#29]
Whitelist should *not* include anything beside the Vox or Diona, but it does.

Using the whitelist in the config option bars players from using Tajaran, Unathi, and everything else not human. I don't want this. Only Vox and Diona should be whitelisted.

**Comment by OrbisAnima** [comment]
Fixed.
https://github.com/SpadesNeil/VOREstation/pull/38
