### ISSUE TITLE
Food Processor missing from kitchen.

### ISSUE THREAD

**Issue by renthur** [SpadesNeil/VOREstation#297]
As stated, there's no food processor in the kitchen, despite it being the only way to acquire soy dope and meatballs.

**Comment by nightwingthedragon** [comment]
Actually, this is false information. I believe that as of new bay, meatballs can be created via the blender. They require animal protein and flour. Soy dope is made by cutting a soy bean, presumably with a knife. The food processor is now obsolete and replaced with the grinder.
