### ISSUE TITLE
Chat channel for announcements for admins!

### ISSUE THREAD

**Issue by nightwingthedragon** [SpadesNeil/VOREstation#299]
Admins can't always be online when faxes or admin-helps or prayers are sent out. However, our neat system with the end-of-round announcements could be used to great effect here! My proposal is a new chat channel that's specifically for these messages and only accessible by admins, so we can still receive timestamped (and hopefully dated!) messages from the station even when nobody's online.

**Comment by SpadesNeil** [comment]
@Leshana !

**Comment by SpadesNeil** [comment]
Doesn't look like this is going to be a feature for now.
