### ISSUE TITLE
Players with hardsuits on shouldn't be able to vore.

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#302]
It's silly and breaks immersion when you shove prey through a closed/sealed hardsuit and into some hole. Makes no sense, and it's abused especially while on EVA and during gateway missions.

You can easily toggle parts of the suit if it's safe to do so while the suit is active.

**Comment by nightwingthedragon** [comment]
Actually, the suit is explicitly stated to be flexible enough to tighten and loosen around injuries and such. Through the helmet makes no sense, I'll grant you! But people with prey in them should certainly still be able to wear suits.

**Comment by SpadesNeil** [comment]
I think it's reasonable to say they can have stuff in bellies, but not the act of doing the vore. Just to clear that up. I didn't mean someone with a full gut can't use hardsuits. I mean if a bodysuit is on you can't AV or UB or BV or CV.

**Comment by nightwingthedragon** [comment]
Sounds more reasonable to me!

**Comment by Arokha** [comment]
I get that it's not 'realistic' but I think we can't 'fix' this for RP reasons. Like I've often taken micros 'in my muzzle' into space and whatnot then swallowed them later.

Really, if you want to fix this, then you need to define like... where each orifice is and what covers it. Like no AV if you're wearing a spacesuit. No oral if you're wearing a helmet, or whatever.

**Comment by SpadesNeil** [comment]
Defining what is covered would fall to somehow getting the vore code, during a vore attempt, to check the predator's outfit in the suit slot, and check its armor var.

If bio protection is 100% then it's a fully sealed suit and the code will go "Nope can't AV/BV/CV/UB them."

If it's a 100% bio helmet, the game will do the same but for oral vore.

**Comment by nightwingthedragon** [comment]
To be honest, this seems like such a minor thing that I really wouldn't bother doing anything about it.
