### ISSUE TITLE
Add clientside "tick" sound with chat updates.

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#304]
And include an option to turn it off in preferences.

This was a thing I always appreciated in Gmod.

**Comment by OrbisAnima** [comment]
What's a tick?

**Comment by SpadesNeil** [comment]
A sound effect. Just to alert that there has been a chat update. A new line of text.

**Comment by FirstSgtDan** [comment]
I often get so much text I just wish I heard a tick when someone mentioned my name so I didn't have to read the whole thing.

**Comment by SpadesNeil** [comment]
It'd be a very subtle tick.
