### ISSUE TITLE
Add bowel/intestine to AV

### ISSUE THREAD

**Issue by Dhaeleena** [SpadesNeil/VOREstation#305]
its just a simple request, tho i dunno how simple is it to make, but i find that doing AV that leads directly to the stomach doesnt have much sense. Maybe to make it more simple, there can be just another option like, 'Anal Vore (stomach) and Anal Vore (intestine) so coding something to pass a prey from organ to organ is not necesary and in the future some kind of absorption of nutrients thing can be added to that. But i guees just making a new organ called Bowels/intestines would be very cool for the many people that does AV. I dont know if someone asked for this on the forums or if its on the works or if its planned for the next big update.

**Comment by FirstSgtDan** [comment]
I approve~

**Comment by Screemonster** [comment]
Give a way of moving prey from one space to another and I'm sold. Sure it'll add an extra step to Avida's "fulltour kisuke before he even realises what's happening" routine but we all have to make sacrifices.

**Comment by Arokha** [comment]
This is really kinda part of the new vore overhaul in #601 since you can do whatever you want for bellies in that. So I'll close this since it's a dupe and you'll be able to do this with that feature set.
