### ISSUE TITLE
Character Ban System

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#308]
I'd like a system to ban characters without banning players. This system would be used to deal with purely IC incidents such as serious violations of company policy that would get you fired, but are too well role-played to justify any bans because everyone still had a thrill during the ordeal.

**Comment by OrbisAnima** [comment]
It's not feasible, you could ban people from names, but they could be Richardicko D'angelo, and thus pass the ban.
You could ban chars from appareance sets, but that would bring us a whole catter of problems too, and even then, it could change one detail of the character and then render the ban invalid. 

This is a situation where admin notes, and players disposition will work better.

**Comment by SpadesNeil** [comment]
Bugger.
