### ISSUE TITLE
Change agressive grab when cuffing to normal grab

### ISSUE THREAD

**Issue by Dhaeleena** [SpadesNeil/VOREstation#309]
Having to grab and upgrade the grab to cuff is really bad, the only way this can be done is if you leave the person in complete pain so they cant stand up in a long while, flashing and flashbangs doesn't work because the person easily stands up before you can even upgrade the grab. Having to just use normal grab to cuff would be a lot better and less annoying

**Comment by SpadesNeil** [comment]
Fixed in next server update.
