### ISSUE TITLE
Can't handcuff people with rig suits on?

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#310]
That's idiotic in my opinion. What are you gonna do? Beat them into crit?

**Comment by Arokha** [comment]
You cannot, it gives you a specific message saying that the armor on the suit is too big to get the cuffs around, which... does make sense.

**Comment by SpadesNeil** [comment]
Well either we adjust the rules of engagement for people with hardsuits on, and authorize shoot-to-incapacitate/kill for those individuals, or we change how hardsuits handle being cuffed.

**Comment by nightwingthedragon** [comment]
Or have hardsuits respond to, say, EMPs and lock down on their user to impede movement because suddenly your heavy-but-power-assisted suit of armour isn't power-assisted any more.

**Comment by SpadesNeil** [comment]
Closing for now.
