### ISSUE TITLE
Camera mislabel: Genetics camera is listed as Fore Solar Control.

### ISSUE THREAD

**Issue by JoanRisu** [SpadesNeil/VOREstation#312]
On the list of cameras it seems the Genetics Camera is labeled as Fore Solar Control.

**Comment by Arokha** [comment]
Fixed by #329

**Comment by FirstSgtDan** [comment]
Oooh. So that`s why we in engineering can see a camera in research.

**Comment by Arokha** [comment]
... it's good you said that, because I didn't change or look at the network. XD *goes to fix that*

**Comment by Arokha** [comment]
Actually that seems unrelated. Which camera?
