### ISSUE TITLE
Exosuit slot uses belt_mirror.dmi instead of back.dmi

### ISSUE THREAD

**Issue by Arokha** [SpadesNeil/VOREstation#314]
Appears to be a mistake, since this means we are missing out on a bunch of the sprites in the totally unused back.dmi file.

**Comment by Arokha** [comment]
Some enterprising individual appears to have copy-pasted a lot of the sprites out of back.dmi into belt_mirror.dmi to compensate for this...

**Comment by SpadesNeil** [comment]
So is this fixed?
