### ISSUE TITLE
Belly overlay layer!

### ISSUE THREAD

**Issue by nightwingthedragon** [SpadesNeil/VOREstation#316]
https://dl.dropboxusercontent.com/u/29945202/LOOK%20WHAT%20I%20DID.gif

I want to add this, I've wanted to for almost a year now! It's a fairly simple concept; when you eat someone (or if you select the right option), you obtain a larger belly on your sprite that's overlayed on top of your clothes to give the impression of "overflowing" them.

From Skype;
"I could make five different states for bellies.
Flat, Bulge, Round, Big and Huge
For no/micro prey, small prey, samesize prey, big prey and macro prey respectively.
You can set it to "auto", which makes it an appropriate size for what you have inside you, or you can choose one of those five to be displayed on your body constantly."

All I'd really need would be sprite artists!

**Comment by SpadesNeil** [comment]
@JoanRisu ?
