### ISSUE TITLE
Plague doctor outfit missing

### ISSUE THREAD

**Issue by kcin2001** [SpadesNeil/VOREstation#317]
ok ive noticed 2 things that there is at least traces of if not the full item in the game but doesnt exist where it should. the plauge doctor mask seems to be fully added but it doesn't spawn with the other pieces and the roboticist labcoat at least has a wearable texture but no item sprite and it obviously doesnt spawn on the roboticist anymore. if those could be readded it would be greatly appreciated.

**Comment by nightwingthedragon** [comment]
Can at least confirm that the awesome-as-fuck roboticist labcoat no longer spawns on the roboticist.

**Comment by SpadesNeil** [comment]
According to the code, plague doctor outfit is now spawnable in character setup if you're in a department that can use it. If this isn't working, re-open this.
