### ISSUE TITLE
just going to put this here

### ISSUE THREAD

**Issue by kcin2001** [SpadesNeil/VOREstation#318]
ok so im mostly putting this out as a discussion for something that we could possibly do if it is even possible so ill get to the point..... usable toy mechs for tinies. i've had a talk about this at least twice over ooc an looc so im going to put it here since i want this to be added if possible along with a few ideas for it

there would be all the same types of mechs that we have the toys for

the combat mechs would have a nerf dart shooter similar to the dart crossbow

the firefighter ripley would have a squirt gun

and the H,O.N.K. would have a bike horn on it basically

(dont mean to have 2 issues posted in a row but this has been nagging me for a week and i dont know what better place to put it)

i would love suggestions and hopefully news if this is even possible because i would be elated if it was

**Comment by SpadesNeil** [comment]
This belongs on the suggestion section of the forum. Not here.
