### ISSUE TITLE
Add access to Bot Maintenance for Roboticist

### ISSUE THREAD

**Issue by Jwguy** [SpadesNeil/VOREstation#319]
I realize there may be some reservations against this, but hear me out; I think the Roboticist should have access to Bot Maintenance panels for some bots, if not all.

Whenever the Roboticist makes a bot, it sits lifeless and inert, and will never begin moving about (or in the case of Medibots, can never be loaded with chemicals, even though the Robotics lab is stocked with Tricordrazine for this purpose). They also cannot repair any Bots, because the maintenance cover has to be opened in order to do so.

Normally, this requires a user with sufficient access in other departments to open the panel on the bots with their ID cards (Medical for Medibot, Security for Securitrons and ED-209s, Janitor for Floorbots and Cleanbots). Given the environment in our server, and how things tend to go, these people aren't always available to activate the bot or allow configuration.

This could be solved by giving access to Maintenance and Behavior Controls to Roboticists, and honestly, it seems like something they should already have.

**Comment by SpadesNeil** [comment]
This is intentional, to prevent roboticists from tampering with security bots or filling the medical bot with chloral or whatever else. Plus you can render any security cyborg inert just by swiping a card on them and they can't move.
