### ISSUE TITLE
Dual Energy Blade Sprite Bug

### ISSUE THREAD

**Issue by JoanRisu** [SpadesNeil/VOREstation#321]
A player has reported that when turned on, the duel energy blade item and icon sprites disappears.

**Comment by SpadesNeil** [comment]
The dualsaber code and sprites are fucked. It's more than an oversight. Bay was lazy and I fixed it in the old code. I haven't fixed it again yet.

**Comment by Arokha** [comment]
Sprites for this are missing (kinda). In lefthand.dmi and righthand.dmi there is dualsaber0 and dualsaber1 which covers off and on, but only for the green saber. The rest are missing.

**Comment by JoanRisu** [comment]
I'll try to make time to fix this but someone will have to ride my ass on friday to get me to do it.
