### ISSUE TITLE
Being able to hug a specific body part

### ISSUE THREAD

**Issue by FirstSgtDan** [SpadesNeil/VOREstation#322]
Well, I play as a micro 99% of the time and sometimes I want to hug people, but obviously I can`t hug their torsos. It would be nice if I could aim at their feet and hug them there.

This should be labeled as an enhancement I guess.

**Comment by nightwingthedragon** [comment]
This is an interesting idea! I'll look into it and see what I can do.

**Comment by Arokha** [comment]
Hah it'd be cute if each body part had a different help-intent message. Mouth was kiss, hand was hold hand, head was pet.
