### ISSUE TITLE
Atmos Tech not being supplied with correct backpack/satchel

### ISSUE THREAD

**Issue by FirstSgtDan** [SpadesNeil/VOREstation#323]
After many days having to change my backpack at my department's locker, I find out that I was supposed to receive a backpack of my department by default (Industrial, same as engineer).

Here's what I'm receiving when I spawn as Atmos Tech while choosing from the different options at Setup Character menu:

Nothing -> Nothing
Backpack -> Black/grey backpack
Satchel -> Black/grey satchel
Satchel Alt -> Leather satchel

**Comment by Arokha** [comment]
Fixed this in a pull request. Atmos techs will get the normal engineering backpacks if/when it's merged.

**Comment by FirstSgtDan** [comment]
Thank you.

**Comment by JoanRisu** [comment]
Due to missing merges, this issue is being reopened.

**Comment by SpadesNeil** [comment]
Is this still a problem?

**Comment by FirstSgtDan** [comment]
No idea, I haven't played atmos tech in ages.

**Comment by Cameron653** [comment]
This appears to still be a bug.
http://puu.sh/oJqxW/16d6f1eb8c.png
Left: Backpack
Middle: Satchel
Right: Satchel alt

**Comment by Cameron653** [comment]
Resolved. See the PR above.
