### ISSUE TITLE
Micro + flash = blind macro

### ISSUE THREAD

**Issue by FirstSgtDan** [SpadesNeil/VOREstation#324]
I have tested with a friend and I can`t blind macros after they pick me up. This could be used for self-defense. Also, on being flashed, the macro could instantly release the micro (or have a chance for that to happen).

**Comment by Arokha** [comment]
Hmm, this is hard. There's stuff about being an in-hand micro that's not very obvious.

The important issue is that when you're grabbed, you're actually inside a container that looks exactly like you. The little thing you see in your hand when you grab a micro is actually a box, painted to look like the micro inside it.

So really, you're not being 'held' by them at all, and the game considers you inside a container and unable to interact with stuff outside. That's he hard part.

**Comment by FirstSgtDan** [comment]
Ah I see. Well, it was only an idea anyway. It`s not like I run away from big people.

**Comment by SpadesNeil** [comment]
I'm afraid this isn't exactly feasible, and we got a lot of other issues right now. Marking as oversight but won't fix.
