### ISSUE TITLE
Prescription Glasses causes a stray light pixel on arm!

### ISSUE THREAD

**Issue by ArbyTheDragon** [SpadesNeil/VOREstation#325]
When facing south (or north) when wearing prescription glasses, there will be a light pixel on your left arm. When facing north, this pixel will be on your right arm in the exact same place.

https://gyazo.com/e31d8025480450baa7e576c61452aef2 This is a normal character sprite

https://gyazo.com/9792385b9234bb910c265272bc481a4d This is the sprite when wearing glasses. NOTICE the white pixel on the left arm.

https://gyazo.com/711496e7c093d4f74b06292a16f1c38c This is the sprite facing north when wearing glasses. NOTICE the white pixel in the exact same place on the sprite, but now on the right arm.

**Comment by Arokha** [comment]
That's dorky.

**Comment by Arokha** [comment]
That pixel was the exact same color as the transparency background in Dreammaker, making it invisible. XD Fixed in PR #327
