### ISSUE TITLE
UB transformation taur not functioning

### ISSUE THREAD

**Issue by Molenar** [SpadesNeil/VOREstation#326]
was told this issue by another player, was said they had far more than enough nutrient in them to make the TF function, but no taur. Might also suggest some kind of message to the pred in these situations to be able to know when transformations happen.

**Comment by kcin2001** [comment]
there is a message when a tf happens both to the prey and pred but in my experience taur halfs do not get added to the player but i have only ever done and seen messages for gender change

**Comment by Cameron653** [comment]
This should be closed, as #406 fixed this problem.

**Comment by SpadesNeil** [comment]
From now on when making a PR, type "Fixes #xxx"
