### ISSUE TITLE
Universal Speak variable does nothing

### ISSUE THREAD

**Issue by nightwingthedragon** [SpadesNeil/VOREstation#340]
I used to use this setting to be able to play a xenomorph who could speak common; now I can't. It seems that bay coders, in their infinite wisdom, have managed to break this variable. Could we see about getting it fixed, please?

Also noted that when I added Galactic Common (:0) to my xenomorph, they would just print
> Skittles says ":0 Testing!"

Instead of actually saying Testing in galactic common.

**Comment by ShadowLarkens** [comment]
Actually, last I checked, this isn't a problem with the universal_speak variable, but instead, the galactic common `:0` hotkey doesn't work correctly. BYOND.

**Comment by SpadesNeil** [comment]
Can't fix it, then?

**Comment by ShadowLarkens** [comment]
The galactic common hotkey needs to be changed to something other than 0.

**Comment by SpadesNeil** [comment]
Wouldn't that break things?

**Comment by ShadowLarkens** [comment]
The language hotkeys are just a one-character variable, the parsing is all automatic. Just need to find a different letter/number/character to set it to.

**Comment by nightwingthedragon** [comment]
Well, why would the universal_speak variable not allow me to speak universally, then? That's not a problem with the galactic common hotkey, surely? My text still showed up in light purple my end, which is the default xeno colour.

**Comment by ShadowLarkens** [comment]
@nightwingthedragon Try testing it again, but use any other language than galactic common- perhaps sol common or gutter. I'm 99% sure that the galactic common language hotkey is just borked, and no one can speak it via the hotkey, humans just do because that's default behaviour.
