### ISSUE TITLE
Need to update the custom items spawning list. 

### ISSUE THREAD

**Issue by JoanRisu** [SpadesNeil/VOREstation#346]
Someone needs to work on the custom items spawning list. Specifically peeps with access to the server. ouo)b

Tasald needs his stuff still and I need my federation kit. I dunno who else needs their item spawns.

**Comment by FirstSgtDan** [comment]
An updated list would surely come in handy.

**Comment by SpadesNeil** [comment]
Leshana, Aronai, and myself have config access.

**Comment by SpadesNeil** [comment]
This should be fixed. Some dingus entered Tasald's name wrong. :U
