### ISSUE TITLE
Belly flavourtexts are saved per-player instead of per-character.

### ISSUE THREAD

**Issue by Screemonster** [SpadesNeil/VOREstation#348]
When adding flavortexts to inside spaces and saving them, they appear to be saving the same text for every character the player has, rather than saving them in each specific character's file.

Steps to reproduce:
Go into a character
edit flavortexts
save slot
load another slot
look at flavortexts. the ones just entered will be there. Editing them and going back to the first character will overwrite them again.

**Comment by SpadesNeil** [comment]
@nightwingthedragon , can you fix that please?

**Comment by nightwingthedragon** [comment]
I honestly don't know what's causing that. I have the code set up just like the old code. I might need @Leshana to help.

**Comment by nightwingthedragon** [comment]
Come next sync we can hopefully close this

**Comment by SpadesNeil** [comment]
Marking as resolved. Pending confirmation.

**Comment by Cameron653** [comment]
I believe this should be closed. To my knowledge, this is fixed.

**Comment by SpadesNeil** [comment]
I thought I closed this.
