### ISSUE TITLE
Spider Taurs and Webs

### ISSUE THREAD

**Issue by SilverTalismen** [SpadesNeil/VOREstation#350]
I had a idea, no doubt people have already had this thought, But I thought what if Spider Taurs had the ability to create some webbing (requiring them to be on aggressive grab ontop of a resting person or monkey) and be able to cocoon them and drag them about working like a straight jacket (you could escape it given some time.) But doing this would drain a decent amount of their hunger away as a cost of doing so

**Comment by OrbisAnima** [comment]
This is pretty much underway, will be my last code on virgo, when I get the time to work at it and it doesn't break in one thousand pieces.

**Comment by SpadesNeil** [comment]
One may argue this is OP.

I don't care really. If it becomes a problem we'll remove it.

**Comment by antsnap** [comment]
OP is almost irrelevant on an ERP server imo. I don't think ruskies will learn our code enough to join as griefing spiders.

Just make escaping not super long and it's suitable for RP.

**Comment by SpadesNeil** [comment]
It's still relevant more than I wish it was. The temptation to abuse is bad to have. However this is something that adds flavor to the game aside from straight up abuse so I'm not opposed to adding it.

**Comment by OrbisAnima** [comment]
escape was planed to be one second actually.

**Comment by antsnap** [comment]
I think molenar dumped some web sprites in this thread.

http://forum.vore-station.net/viewtopic.php?f=22&t=192

**Comment by Screemonster** [comment]
If wrapping someone in a web is no faster/easier than EATING them then every person on the station already has an ability to detain/contain any other person on the station already.

(I've been known to just spawn the existing webs in Scree's office at times. they just slow movement. :p )

**Comment by SpadesNeil** [comment]
Then Balance isn't an issue if we go with Scree's suggestion.

**Comment by SpadesNeil** [comment]
We can now add this.

**Comment by antsnap** [comment]
beep beep I'm working on this. I have floor webs working atm for spider taurs only

**Comment by antsnap** [comment]
https://github.com/SpadesNeil/VOREstation/pull/432
