### ISSUE TITLE
Underwear bug

### ISSUE THREAD

**Issue by OrbisAnima** [SpadesNeil/VOREstation#351]
-Select a Sex
-Select an underwear other than none
-Change sex
-if the underwear is not on the list, it won't allow the user to change it. (None is on both lists)

Solutions:
a: Use the list I made when I created the code, and allow both sexes to choose any underwear

b: when changing sex, force it to none, so it won't fuck up the code and allow you to change the underwear.

**Comment by SpadesNeil** [comment]
Was this ever fixed?

**Comment by OrbisAnima** [comment]
Not by me, I proposed two possible fixes since the original code that allowed for both sexes to use them. Now on my server I just use an unified list and be done with it, sadly it is not compatible anymore with vore since we have top and bottom underwear separated :(
