### ISSUE TITLE
Add features to track and lose body weight

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#361]
Relies on #357 to be completed.

- New sprites and equipment (treadmill, weight lifting, some mini-games to go with it) to decrease weight slowly.
- Also add scales to medbay to get exact weight numbers, or add the feature to body scanners. Multiply weight by player scale. Return weight in **both** pounds _and_ kilograms.

Medical records should have information on the character's weight in pounds and kilograms. This is not necessary to consider the issue resolved but would be nice.

- Treadmill mini-game could require a player to continuously click the treadmill or an action verb every so often. Failing the minigame results in the player being flung and knocked down behind the treadmill, so account for what direction the treadmill is facing.
- Dumbbell mini-game would just require using the item in-hand while holding still to complete reps.
- Bar-lifting minigame... I don't know. Ideas? I want a 'failure' of this to result in the thing falling on you and choking you because I'm a sadistic fuck.
- Suggest other ideas.

**Comment by SpadesNeil** [comment]
Treadmills and dumbbells are suggested. Perhaps bar lifting.

**Comment by Molenar** [comment]
could have normal exercise on special designated exercise mats, like push ups, sit ups, etc.
