### ISSUE TITLE
Make Weight Gain persistent between rounds

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#362]
Relies on #357 and #358 to be completed.

Would be awesome if we could make body weight update at round end to overwrite the character save with the new weight, even if it's above the limits normally set by the character save menu. May require SQL to function correctly but I am not sure.

Should body weight also be saved with cloning? Or should it reset the character to the default average weight? I think the latter is more realistic, but the former may be desirable.

**Comment by SilverTalismen** [comment]
I would say yes for the first part, I have a character who would be the lowest weight avaliable, But if he gains weight I believe it should be saved for the next round, and if you get a scan before you get any weight it should keep you at what you weighed at scan

**Comment by nightwingthedragon** [comment]
Possibly have that as an option? Some people enjoy the process of working their way up to being the fattest balloons around, but not so much actually BEING the fattest balloons around once the stuffing's done. Set your weight at the start of the round, or have it carry over from last. Both of those under the same option.

**Comment by SpadesNeil** [comment]
It will be an option then.

**Comment by SpadesNeil** [comment]
Does @Leshana @Arokha or @Cameron653 know how this might be accomplished, if at all? I still have other features to finish but this would be the icing on the cake.

**Comment by SpadesNeil** [comment]
I'm told by the SS13 host chat this is very possible.

**Comment by Arokha** [comment]
You would just update the weight in their save file.

**Comment by Leshana** [comment]
That's what I said!

**Comment by SpadesNeil** [comment]
>You would just update the weight in their save file.

Yes but _hoooowwww_? I want to do it at round end (if a person survives to round end) and when a person cryo's. *nodnod*
