### ISSUE TITLE
Soviet AI monitor screens not in new code

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#376]
People want it back and so do I. It was an old station monitor sprite in the older code.

**Comment by Screemonster** [comment]
I'll take a look at this in a couple of days, was gonna poke at AI displays anyway. (I assume you mean the status screens rather than the core)

**Comment by SpadesNeil** [comment]
Yes. The status screens.

**Comment by Screemonster** [comment]
Found the sprite in the oldcode dropbox, can fling up a fix when I get home from work tonight. There's actually two soviet-looking status displays there, one which is a copy of the redoctober AI core and another which is just a bold yellow-on-red hamer and sickle.

**Comment by SpadesNeil** [comment]
Get the red october one. the old one was a placeholder.

**Comment by Screemonster** [comment]
Well derp. Should have checked my messages BEFORE diving straight into gimp and tidying sprites up. Well, the old placeholder one has been smoothed and shaded a bit so it's not so glaring.
