### ISSUE TITLE
Slime race and prosthetics - they keep their actual limbs, too

### ISSUE THREAD

**Issue by ursamedium** [SpadesNeil/VOREstation#379]
Not entirely sure what's going on here, but 
![img](http://i.imgur.com/r3f3HGv.png)
Made a slime person with full prosthetic limbs, had a character idea I was mulling around, and it seems they were keeping their actual limbs, as well?

**Comment by SpadesNeil** [comment]
This is a problem with how sprites are colored in our code and I currently have no ideas nor intentions to fix it. You still have robotic limbs and I can see them in the sprite but they are shaded purple with the rest of you.

Marking as wontfix, sorry.
