### ISSUE TITLE
Lights are borked

### ISSUE THREAD

**Issue by JoanRisu** [SpadesNeil/VOREstation#384]
The lighting system seems to be broken. In areas where power is down or in created areas, there is still light despite there being no source.

**Comment by OrbisAnima** [comment]
This is more a mapping issue, since you leave an area with light, like... space, and then you build on top, ie, the area has a natural luminosity.

**Comment by OrbisAnima** [comment]
((Also, I would hardly call that bug major, since it doesn't breaks gameplay))

**Comment by JoanRisu** [comment]
Orbis, this issue still applies to the entire station. Not just in an area marked as "space." I don't think this is just a mapping area problem. 

For instance, when I turn off the lightswitch in the captain's quarters, there is still light.

**Comment by JoanRisu** [comment]
Also, we have a new labeling system so major doesn't mean _very tiptop of the list_

**Comment by OrbisAnima** [comment]
Ahhh, roger!

**Comment by JoanRisu** [comment]
At this time, it seems the issue is now limited to build mode only. I would like to keep this issue open over the weekend for a few more days to take note of any occurrences outside that condition.
