### ISSUE TITLE
Custom ear/tail menu doesn't list standard options for other species

### ISSUE THREAD

**Issue by Screemonster** [SpadesNeil/VOREstation#385]
At present, the ear/tail menus allow you to have your species default, none, or one of the options from the fluff tails menu. There is presently no option to pick the default tail for a DIFFERENT species (such as giving a tajara the sergal tail sprite)

Adding the other default tails will allow for things like giving a sergal a unathi tail to make an anthro kangaroo, and so on and so forth.

**Comment by SpadesNeil** [comment]
This is something I would want actually.

**Comment by Screemonster** [comment]
I can definitely see people wanting to put tajaratails on birds when I finally get them finished so they can make anthro griffins.

**Comment by OrbisAnima** [comment]
take the tail sprites from those species and add it to the list of tails made for the code, that's pretty much what I am doing for the Eros server. You can of course, wait until I finish with it and port it
