### ISSUE TITLE
Snipping wires on vending machines doesn't leave logged fingerprints

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#389]
I just accidentally banned a player because I thought they were straight up lying to me.

To reproduce:
0. (Optional) Let some poor sod mess with the machine.
1. Go to a vending machine.
2. Screwdriver it. (Note that no logs are left in the fingerprints var, even hidden admin prints.)
3. Cut wires. (Still no prints. Not even an "Electrified by..." message.)
4. Space evidence.
5. Come back a few minutes later and zap yourself, then call an admin and claim someone is griefing.

There's still other ways to pull logs on this but on-the-fly verifying shit gets messed up by this.

**Comment by SpadesNeil** [comment]
@Arokha @Leshana @killer653 get in here D:

**Comment by OrbisAnima** [comment]
Well... it makes sense it doesn't leave prints, after all, the original user is using insulated gloves on it.

of course, if you mean admin prints, that's an entirely different matter

**Comment by killer653** [comment]
I could probably look into it and see if I could make it so touching the vending machine puts prints.

**Comment by Leshana** [comment]
Whaaaaaaaaaaat?  Nooooooo!

**Comment by killer653** [comment]
Fixed. See PR #391
