### ISSUE TITLE
Remove Changeling Proboscis Insta-Killing (maybe replace with vore mechanic)

### ISSUE THREAD

**Issue by Screemonster** [SpadesNeil/VOREstation#394]
At present, the only real way for lings in code to work if for them to husk people, which makes them somewhat too murdery for events.

Giving them a vorey means of doing it (such as automatically absorbing genomes from anyone they digest) would fit the theme of the station a lot better.

A way for admins to give characters the changeling ABILITIES without them needing to be an outright changeling would be fantastic. Last time I made an "alien creature" for an event with a nagatail and unathi body, I had to make it a ling and have it eat like half a dozen spawned-in braindeads just to give it the ranged hallucinogen sting and enough chemicals to actually be useful.

**Comment by OrbisAnima** [comment]
it's a relatively simple change to do, I look foward to these events scree!

**Comment by Screemonster** [comment]
Also I just realised that fluffwise a vore-based DNA-stealing stingbeast is basically Scree dialed up to 11 :p
