### ISSUE TITLE
Add Bird Species

### ISSUE THREAD

**Issue by Screemonster** [SpadesNeil/VOREstation#398]
http://forum.vore-station.net/viewtopic.php?f=22&t=477&p=3089#p3089

deets here.

Sprites are done for an avian race, based on the vilous nevreans (same lore as sergals).
Also got a monkeylike in the form of a parrot-esque thing that I've called a "sparra" unless you can come up with a better name.

Hair/headfeathers can be added later easily enough, as can alternate tails.

**Comment by SpadesNeil** [comment]
As amusing as your Issue titles are, I need you to be descriptive with them. XD

I edited your issue and will be converting it to a milestone set.

**Comment by Cameron653** [comment]
I'll probably give this a shot and see if I can get it working.

**Comment by Cameron653** [comment]
All three of the issues should be closed, now what it's added in.
