### ISSUE TITLE
Add Bird Species Language

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#399]
We need to come up with some kind of language for these creatures to speak. I'll leave it to @Screemonster to decide what it's called.

**Comment by Screemonster** [comment]
Well, on tgmud, people speaking nevrean literally just come out as "peep peep peep peep peep peep peep peep peep peep peep peep" and that seems to fit in with some of the fan stuff I've seen. Just lots of peeps and cheeps and other whistly sognbird onomatopoeia.
