### ISSUE TITLE
Make shoeless people run at same speed shoed people do?

### ISSUE THREAD

**Issue by antsnap** [SpadesNeil/VOREstation#404]
Would be good for those who RP barefoot chars.

Thoughts?

**Comment by OrbisAnima** [comment]
just take off shoes speed... also, take off the tajaran boost to speed if you are going to do it. Some sec players will whine, but already having glass in the floor stunning and damaging you is punishment enough... and this idea might even make handcuffs on the orange shoes (legcuffs) see more use.

**Comment by Cameron653** [comment]
It'd probably be a good feature, as I don't see too many situations in which this could be a bad thing, except for security. And even then, the prisoners should usually have shoes on anyways.

**Comment by antsnap** [comment]
Consensus seems that's a good idea. I'd like to add we have the mechanic were you can put people in the foot slot as a macro if you walk over them with no shoes; by making barefootedness less annoying, hopefully that sees more use~

Ill try to have a PR today.

**Comment by antsnap** [comment]
https://github.com/SpadesNeil/VOREstation/pull/446
