### ISSUE TITLE
Apparel duplication thing.

### ISSUE THREAD

**Issue by Finlandier** [SpadesNeil/VOREstation#405]
I put the crew resource's hat on Ian.

It was on Ian.

Then it was on my hand, too.

The item was kind of duplicated, but it was still the same item in two different locations. Like, an invisible copy and a visible copy of it.

Dunno how to explain it, but, it's really easy to discover.

**Comment by SpadesNeil** [comment]
This bug has been in for a while. It's not really worth fixing I'm afraid. I'm marking this as wontfix for now. There's not much important that can be duplicated from hats.
