### ISSUE TITLE
Insole?

### ISSUE THREAD

**Issue by Rixunie** [SpadesNeil/VOREstation#410]
Add the ability to hide micro's/smaller people in your shoes, suits, etc, effectively hiding them from view?

**Comment by OrbisAnima** [comment]
a micro is an object.If you want to hide them in your shoes... you need to make shoes a container. Some suits, like the labcoat, already are a container, and thus micros are hideable there, you might get problems in there with talking, whispering and emoting, so test before comiting.

**Comment by SpadesNeil** [comment]
Duplicate of #280
