### ISSUE TITLE
Audio Range for Prey

### ISSUE THREAD

**Issue by Rixunie** [SpadesNeil/VOREstation#411]
Make it so players inside of predators have reduced chat range possibly?

**Comment by Screemonster** [comment]
An option to anonymise prey for people outside would be interesting too, so someone talking in a stomach would still have their name revealed ('cause you can hear them) but people using "me" would just be identified as "(pred)'s prey" or simply unknown.

**Comment by SpadesNeil** [comment]
Since no one seems to be able to tackle this, I'm slating it under wontfix. Besides, we already have the subtle (for /me) and whisper (for /say) commands.
