### ISSUE TITLE
Puddles/Remains

### ISSUE THREAD

**Issue by Rixunie** [SpadesNeil/VOREstation#412]
Add puddles if someone CV/UB's someone or something with a toggle for it to be visible to others maybe? Could have it evaporate over time so it won't bother others.

**Comment by Cameron653** [comment]
Taking a stab at this.

**Comment by Arokha** [comment]
Asking in a forum thread about this first is a good idea. I asked several months ago and was told by basically everyone who replied that they would prefer not to have any sorts of remains.

**Comment by SpadesNeil** [comment]
I don't think that opinion has changed based on Skype group response.

**Comment by Cameron653** [comment]
I put up a forum post to see if people would want this added in. So far it's 4-0 for adding it in.
http://forum.vore-station.net/viewtopic.php?f=23&t=523&p=3245#p3245

**Comment by Cameron653** [comment]
I closed the PR and marked the forum post as closed as the amount of people that don't want it more than the people that do want it.
