### ISSUE TITLE
Cannot control porta-turrets

### ISSUE THREAD

**Issue by DemicusMaximus** [SpadesNeil/VOREstation#417]
/obj/machinery/porta_turret

Weather built or spawned, the controls do not respond to human interface. AI and Borgs can still control. Leaves them stuck with the following controls regardless of input:
Status: On
Behaviour controls are unlocked

Lethal Mode: Disabled
Neutralize All Non-Synthetics: No
Check for Weapon Authorization: No
Check Security Records: Yes
Check Arrest Status: Yes
Neutralize All Non-Authorized Personnel: Yes
Neutralize All Unidentified Life Signs: Yes

This makes them pretty much useless during events, securing areas during red alert or higher emergencies, or pretty much anything but protecting Sec, as they will fire indiscriminately at anyone without certain access.

**Comment by Screemonster** [comment]
Had a tinker with this, confirmed that it's still not behaving. I can see the vars that the control panel needs to be changing (protip: vv on a closed turret only shows you the cover, the actual turret is another entity inside it, THAT is the one with the variables)
No idea how the popup interface works though so someone more experienced than I am will have to tinker with it.

**Comment by SpadesNeil** [comment]
Upon next server update we should see if this works again.
