### ISSUE TITLE
Port Paradise's parallax code for space tiles?

### ISSUE THREAD

**Issue by Screemonster** [SpadesNeil/VOREstation#418]
https://github.com/ParadiseSS13/Paradise/pull/3734

https://gfycat.com/ThoughtfulDenseAnophelesmosquito

This is pretty as hell and if the overheads aren't too great it's a huge boost for the feeling that space is _big_. It's still a WIP from their end, but worth keeping an eye on.

**Comment by OrbisAnima** [comment]
it's really awesome!

**Comment by Cameron653** [comment]
I did some testing to port it over, and everything _works_ , as seen in 
https://i.gyazo.com/afef7d6af6c1d5741b46ce89ea889dde.mp4
But there's one major problem, the majority of the space tiles are too dark, as seen below.
https://i.gyazo.com/8976b8b0cd2c4d7061eecad5b8dc434e.mp4

If anyone is going after this, I'd personally wait until he fixes all the major bugs as shown, and then port it over when Paradise merges it and everything's working.
