### ISSUE TITLE
Lysis-Isolation Centrifugue (Xeno Botany issue)

### ISSUE THREAD

**Issue by OrbisAnima** [SpadesNeil/VOREstation#42]
If the Lysis machine had a disk when there is a power outage, it will take out the disk, but will not allow you to insert it again, or a new one, since it thinks there is a disk.

There is also the issue where if you try to destroy and then rebuild the machine there is no board for it.

the machine name is /obj/machinery/botany/extractor

**Comment by Arokha** [comment]
I can't duplicate this. Turning off the power to the machines in the room doesn't seem to eject the disk, and it seems to let me insert/remove/insert before and after doing so.

**Comment by OrbisAnima** [comment]
I couldn't duplicate it either, , but, there is still the thing where we should create the board for it
