### ISSUE TITLE
Implement mechanics to allow absorption.

### ISSUE THREAD

**Issue by Screemonster** [SpadesNeil/VOREstation#420]
http://forum.vore-station.net/viewtopic.php?f=20&t=527
Discussion thread here.

It's been a thing a few people have been looking for for a while, to the extent of using PAIs as a ghetto means of playing "Arbon's butt" or similar, so we should probably implement an actual way to go about it.

**Comment by antsnap** [comment]
+1 for slime chars :3

**Comment by Screemonster** [comment]
Even separate from the absorption part, slimes could benefit from an "engulf" vore-mode (even if it would just be another swallow-to-stomach thing with different messages)

**Comment by OrbisAnima** [comment]
woudln't it be easier to allow characters to customize the messages they make for each kind of vore? I mean, some people digest others, then some people absorb them...

**Comment by Screemonster** [comment]
Implemented in #581 and #639.
