### ISSUE TITLE
Stomach acid entities and tiles

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#424]
Because goon confirmed secret voraphiles.

Stomach acids code, fleshy doors, etc. Really not hard to code but this keeps reminding me to do it.

**Comment by SilverTalismen** [comment]
What exactly will this add?

**Comment by SpadesNeil** [comment]
Stomach floor tiles so I can make a vore themed Z-level.

**Comment by SilverTalismen** [comment]
Aah okay, well makes sense
