### ISSUE TITLE
Rebalance Cloaking Device

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#425]
Cloaking devices are pretty much absolutely useless with security huds being worn by security all the time. I propose we change how the cloaking device works.

First off, it no longer shows up on hud.

So how do you defeat it? If you bump into a player while it's active, attack someone, or use an item, you decloak with a loud noise. If you are hit by a projectile, you are also decloaked.

If you are forcibly decloaked in this manner, there's a cooldown before you can cloak again.

Cloaking devices should also be defeated by thermal goggles, allowing you to see the target normally.

**Comment by OrbisAnima** [comment]
sounds fun, though, you don't really need to redesign most of it. just... check out the chameleon proyector, it has most of the functions you mentioned, better than going from ground zero

**Comment by Screemonster** [comment]
The other thing that I considered a while back would be giving it a limited duration, make it the invisibility watch to the chameleon projector's cloak-and-dagger.

But absolutely make it vanish you from the huds, it's pretty pointless that the "completely invisible" thing is easier to spot and stands out more than the disguise item.

**Comment by Cameron653** [comment]
I suspect I have a fix for making it not show up on the huds. You could possibly make it so when it's on and stealth is detected (Listed under mob/living/carbon/human/update_icons.dm). it changes your invisibility to 101. 

When it's turned off (Currently the ways of turning it off are to hit someone (With any item/projectile, do an AOE flash with a flash, or use a flashbang.), make it so it changes the invisiblity to 0. This should be an easy enough fix. The way to make thermals see it would be to make thermals detect invisible living mobs (Which could possibly be done by giving the thermals a SEE_INVISIBLE_LIVING flag.)

I'm going to see if I can fix this later on today.
