### ISSUE TITLE
Xenoarch only has one scanner.

### ISSUE THREAD

**Issue by OrbisAnima** [SpadesNeil/VOREstation#426]
The Depth Analysis Scanner is a machine you have to drag everywhere, is often lost somewhere in the z level of the asteroid or in use by one of the two possible xenoarchs. while a longer solution like being able to create your own might be nice, an inmediate solution like adding another to the asteroid should be easy to add right now.

**Comment by SpadesNeil** [comment]
Let's make it possible to actually build the damn things.

**Comment by Cameron653** [comment]
Correction: It's the suspension field generator, not the depth analysis scanner. That being said, I might look into this.
