### ISSUE TITLE
Deca-code locks broken

### ISSUE THREAD

**Issue by Fevix** [SpadesNeil/VOREstation#435]
Results of a recent cracking of locked container on asteroid. All codes were attempted on the same crate.
Code | Corr. #, Inc. Pos | Corr. #, Corr. Pos.

1111 | 0 | 4 -This one made me WTF. How do you rearrange the same digits?
2222 | 0 | 0 - This was mainly done to determine if it was just returning 4 correct digits in wrong opsitions for every set of 4.
3456 | 0 | 1
3466 | 0 | 2 -This combined with the previous one indicates that the 6s are correct (If 3 or 4 were correct, the second number wouldn't change, and if 5 were correct the second number would be 0.)
6678 | 0 | 3 -Sixes exist but do not belong anywhere apparently.

At this point I gave up and flipped a table.This 4-digit code has 4 1's, 2 sixes, and a 7 or an 8, and none of the 1's or 6's appear in the first 4 digits.

**Comment by Screemonster** [comment]
The deca-code lock can't have more than one of the same digit. Repeating a digit makes the count flip out.

So your code there has a 1, a 6, and either a 7 or an 8, and the last digit is 9 or 0.

**Comment by SpadesNeil** [comment]
So this isn't broken?

**Comment by Fevix** [comment]
@Screemonster I did not know that. My apologies.
