### ISSUE TITLE
Languages cannot be spoken.

### ISSUE THREAD

**Issue by Zael553** [SpadesNeil/VOREstation#436]
There are issues with two of the languages in the game, namely Birdsong and Galactic Common (when playing as a Vox). The issue stems from the prefix used to speak in these languages uses the same prefix for speaking in a specific radio channel. Birdsong conflicts with the Science department (:n) and the Galactic Common conflicts with the Command channel (:c). This makes it nigh impossible to play Vox and we can't enjoy the new language of the Nevrians either.

**Comment by killer653** [comment]
#434 addresses the vox issue and fixes it by making it :7
Galactic common works. It's :6 not :C

**Comment by antsnap** [comment]
We should move all languages to numbers at some point for consistency.

Well least till we get more than 10 :o
