### ISSUE TITLE
Bird species defines missing from human_species.dm

### ISSUE THREAD

**Issue by joey4298** [SpadesNeil/VOREstation#437]
You can spawn in the Sparra, but not the humanoid mob.

**Comment by SpadesNeil** [comment]
This is because when birds were added, no one defined a mob for it. All the code does is re-texture a normal human and change its variables.

**Comment by Screemonster** [comment]
Uh. I have no idea how race coding works or how to define a mob. All I did was the sprites.

**Comment by Cameron653** [comment]
I could look into this later after I finish the foxes and fennecs.
