### ISSUE TITLE
Singulo apparently not deleting on level transitions

### ISSUE THREAD

**Issue by Screemonster** [SpadesNeil/VOREstation#439]
The construction site has an area set aside specifically for the singularity engine, specifically on another z-level so that it won't wreck the rest of the station if it gets loose.

Apparently that doesn't help and some three hours after leaving Z4, it found its way to Z3 and ate telecomms. Deadshift, but this is something that would be best to avoid happening on a populated shift as an engineering project in the place that engineering projects are supposed to be really shouldn't be in a position to end the shift in an awful murderous manner.

Singulos USED to automatically delete themselves on a level transition. Is this not the case any more?

**Comment by SpadesNeil** [comment]
IT'S NOT A BUG, IT'S A FEATURE.

# **ALL HAIL LORD SINGULOTH**

**Comment by SpadesNeil** [comment]
The only reason I'm not fixing this is _because_ I don't want a singularity left unattended just because it's on another Z-level.
