### ISSUE TITLE
Inside flavor text is missing from character setup.

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#44]
Needs to be re-added.

**Comment by SpadesNeil** [comment]
@nightwingthedragon ?

**Comment by SpadesNeil** [comment]
Well let's try @Leshana then.

**Comment by nightwingthedragon** [comment]
I can do this, because I need to re-add the extra 10 character slots anyways. Didn't reply before because just learned last night that Git Issue is a thing.

**Comment by SpadesNeil** [comment]
Does this still need doing?

**Comment by nightwingthedragon** [comment]
Yes, but I need Leshana's help since she rewrote how stomachs and their flavour texts are handled.

**Comment by SpadesNeil** [comment]
Okay. @Leshana get in here!

**Comment by nightwingthedragon** [comment]
I swear I'm still working on this, shit just got busy at uni lately x.x

**Comment by nightwingthedragon** [comment]
Closed in PR #333
