### ISSUE TITLE
Viewing Variables occasionally causes client crash

### ISSUE THREAD

**Issue by Screemonster** [SpadesNeil/VOREstation#440]
So far, have been unable to reliably reproduce whatever is causing this.

Sometimes, when an admin attempts to vv a player, the admin's client crashes immediately. Have had it happen myself (win8.1) and it happened to Molenar today as well.
So far have yet to determine a pattern and since the variables never actually display, we can't see what's in them that makes the crash happen.
Opening an issue to try and track this.

**Comment by Screemonster** [comment]
Interestingly, when ONE admin is affected it doesn't seem that ALL are affected.
Tested with Ainslie Grzeskiewicz today. Molenar crashed, I was able to vv them fine, molenar tried again and crashed.

Error message is "dreamseeker encountered an improper argument"

Has happened with flavortext too reportedly.

**Comment by SpadesNeil** [comment]
If this is only happening to Molenar it's a clientside problem. If we cannot reproduce the bug, we'll mark as invalid.

Until then someone with Win 8.1 needs to test it, but we can't do that unless we know what is in the flavor text to cause it.

Attempt to reproduce the issue on a new shift. Sometimes Dreamseeker just has dumb bugs like this.

**Comment by Screemonster** [comment]
It's happened to me once. I figure that any time it happens it should be logged here - might be related to weird text characters in flavortext or records, but no idea why that would affect different people in different circumstances.

**Comment by SpadesNeil** [comment]
Step-by-step instructions to reproduce?
