### ISSUE TITLE
White bunny ears added to the character creation

### ISSUE THREAD

**Issue by Molenar** [SpadesNeil/VOREstation#441]
just what it says, we need an actual white set of ears.

**Comment by antsnap** [comment]
Bunny ears currently match the hair of the character.

I can't sprite for crud so someone else make it. We already have a bunny ear sprite to work with~

**Comment by Molenar** [comment]
the sprites already existed on the old code, just need to port them https://www.dropbox.com/s/hw9l1n7y7novw50/bunny.dmi?dl=0 i'm shit with git stuff, but here's the sprites

**Comment by JoanRisu** [comment]
The bunny ears have been added to pull request #489

**Comment by Arokha** [comment]
This was merged, dunno why this stayed open.
