### ISSUE TITLE
UB Oviposition mechanic

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#444]
Requested by a number of players.

The option to release a character as an egg if you're a Bird or Unathi would be nice.

Eggs should have a look and description based on the species it came from--including custom species.

"That is an Unathi egg. Some species of Unathi apparently lay soft-shelled eggs!"
"That is a Nevarean egg. Most Nevareans lay hard-shelled eggs!"
"That is a Human egg. Some humans--wait, what?"
"That is a Tajaran egg. Apparently that's what a Tajaran egg looks like. Weird."
"That is a Skrell egg. It's soft and squishy."
"That is a [custom_species] egg. It has a very unique look to it."

Player should be able to break out of the egg at any time--or someone else break it.

**Comment by antsnap** [comment]
That's cute.

Shouldn't be too tricky. Someone make sprites~

**Comment by killer653** [comment]
This would be a really nice feature, I'm going to look into it and see if I can get a prototype working at least
