### ISSUE TITLE
Replace tradeband and gutter with Angelic and Daemon?

### ISSUE THREAD

**Issue by antsnap** [SpadesNeil/VOREstation#447]
Howdy,

http://forum.vore-station.net/viewtopic.php?f=20&t=560

The idea was mentioned to replace tradeband and gutter (which no one really uses afaik) with Angelic and Daemon, the native tounge of the angle and demon alien RP races.

The benefits are replacing two languages with little reason to use, with languages worth using. The other benefit is this woud allow us to have 1 less language effectively, thus freeing a hotkey (.8).

Thoughts?

**Comment by SpadesNeil** [comment]
No. I like those. We shouldn't get rid of something that isn't broken. A lot more players use those languages than you think.
