### ISSUE TITLE
Birdsong language color is bright and hard to read for me.

### ISSUE THREAD

**Issue by antsnap** [SpadesNeil/VOREstation#452]
Anyone else think so? It's a quick change. Right now the color is FFBBFF,which is very bright pink (really close to white, on a white background...)

I was thinking making it darker, like #e600e6.

You can compare different shades by plugging FFBBFF into http://www.w3schools.com/colors/colors_picker.asp

**Comment by SpadesNeil** [comment]
#cc9900 Try this. I think this looks better, and fits the birdy mood.

**Comment by Cameron653** [comment]
It'd be a easy enough fix. Would you still like it to be "#CC9900"?

**Comment by SpadesNeil** [comment]
Go for it.

**Comment by Cameron653** [comment]
This should probably be closed since a PR was merged that fixed this.
