### ISSUE TITLE
The Judge cannot be loaded properly

### ISSUE THREAD

**Issue by ZodiacShadow** [SpadesNeil/VOREstation#455]
Okay, I'm not entirely sure how this issue came about, but I'll recount what went on.
I manufactured a Judge. I unloaded the five rounds from it to check what kind they were. Then I started to load the shotgun slugs back inside. At this point, none of my icons were updating, but the console worked just fine, and actions DID happen - meaning that I didn't see slugs getting picked up or disappearing from my hand when loaded into the gun, but they were - and I eventually filled up the gun. This was all well and good. I restarted BYOND to fix the screen freeze. When I logged in again, the gun was full, but there were three extra slugs lying about.

**Comment by ZodiacShadow** [comment]
I just tried mucking about with the Judge again. Almost the same result. Unloaded the gun, loaded the gun. Screen froze, and the gun ended up being "full" with another slug lying ready for use next to it. Examining the gun shows that it has five rounds in it. Unloading the gun gives the message "You unload 5 rounds from "The Judge".", but it only removes the four that are ACTUALLY in there.
So... it doesn't produce duplicates, but it DOES get loaded stupidly.

**Comment by SpadesNeil** [comment]
Does this bug replicate with all revolvers, or just the judge?

**Comment by ZodiacShadow** [comment]
As far as I know, it's just the Judge. Only one I've actively tested and had access to, recently.
Another note is that the second batch of experimentation happened VERY late in a shift, so that may explain some of the instability (the first report, however, did not).

**Comment by Arokha** [comment]
I'm unable to replicate this. It seems to work fine in the current version. Maybe something else fixed it? I can unload/reload the judge as much as I want but it doesn't seem to have any issues with freezing or shell duplication or anything. Ejects 5 shells, I pick 'em up 1 at a time and put 'em back in, then eject 'em again, seems fine.

Might try clearing your BYOND cache, maybe rsc file corruption or something? Weird that the screen would freeze for you.
