### ISSUE TITLE
Remove Lag [MC Update]

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#459]
https://github.com/tgstation/-tg-station/pull/16089

I'm not as good as a coder as I'd like to be, so I need one of you magic bastards to tell me how this works and how we can port it to our code.

**Comment by OrbisAnima** [comment]
My advice is to bribe Aronai, like, a lot. This is quite a nice idea implemented by a guy that knows what he is doing, but if you implement it badly things could go south pretty quickly.

Or just wait until I port it to Eros, and then import my commit.

**Comment by ForFoxSake** [comment]
This kind of update is _huge_. The kind of huge, that, rebasing all your code that you've written up until now onto the /tg/ code base would be easier to do.
I've got some ideas on how to reduce lag, and possibly bring in some new features, but they would be trivial changes in comparison to this kind of work.

**Comment by SpadesNeil** [comment]
Fuck. WELP.

**Comment by SpadesNeil** [comment]
NEW IDEAS TO REDUCE LAG, THEN.
