### ISSUE TITLE
Buried-crate puzzle is too obtuse.

### ISSUE THREAD

**Issue by Screemonster** [SpadesNeil/VOREstation#460]
Issue #435 touched on this, but it's really a part of a larger issue.

The puzzle that's there is not documented very well, with the popup not explaining important details like the fact that all four digits in the code must be unique. (with buggy results if you enter a code with repeated digits)

It's practically impossible to solve without a multitool as well. The 2014-code puzzle may have been simplistic and formulaic after a while, but it at least had a reasonable (30%) chance of being guessable without a tool, which improved to 70% with a tool if you knew what you were doing.

As it stands, miners are just asking for emitters/guns and bypassing the puzzle entirely, since breaking into xenoarch and using the emitter there is easier than trying to figure out a poorly-documented mastermind puzzle.

Since this is one that could have a lot of brainstorming to fix, I've posted up a forum thread:
http://forum.vore-station.net/viewtopic.php?f=23&t=569

**Comment by killer653** [comment]
A way it could be changed to be less random is changing it to be 4 digits to 2 digits. Looking into the code, it would be a simple fix and actually make it viable. Just need to simply make the popup when you click the box say the two digits must be unique, and lower it down to two digits.

**Comment by SpadesNeil** [comment]
I have no desire to make the puzzle easier. Making it better documented, well, that might help.

But really we need to make deca-crates explode when fired upon.

**Comment by Screemonster** [comment]
2 digits would become trivial. I'd solve it just by entering pairs of 12, 34, 56, 78. if the code is, say, 73, then on the 34 I'd be told there's one digit in the wrong place, and on 78 it'd say one digit in the right place (I can skip 90 - if I've not found one of them in 1-8 then I know it must be 9 or 0). That leaves only 48 or 73 as possibilities. With 2 digits it's roughly 10% success by pure guessing, and absolute guarantee in 6 moves or less with a tool.

Hell, even 4 digits isn't toooooo hard if you actually know what the puzzle entails.
1st guess: 1234. 2nd: 5678. Let's say the code's 0438.
My first guess gets me 1 in the correct position, one in the wrong position. Second guess gets one in the correct position. I know the last digit must be 9 or 0.
I try 3456. Again, I get a correctly placed one, and an incorrectly placed one. If 5 or 6 were the correctly placed digits from the second guess, they've now moved and would be incorrect, so I know the newly correct one MUST be the incorrectly-placed digit from the first guess - which is the 3 or 4.
I try 7890. Two incorrectly-placed. I knew one of 9 or 0 were in there, which means 5 and 6 aren't in it (only one in 5678, which I now know is in 7/8). Four guesses in, and we've eliminated 5 & 6. Also, all four numbers were found in 3456 and 7890, which means we can eliminate 1 & 2. So. **34 had one digit in the right place and one in the wrong. **78 had one in the right place. So the last two digits are either 38 or 74.
Let's try 3974. Two digits in the wrong place. That tells us the last digits are 38, AND since we'd already confirmed both 3 and 4 were present, 7 & 9 must not be. So it's either 4038 or 0438.
Even with me deliberately picking the worst of random guesses, I can ping that combination in 7 moves max. It's just a little scribblework with a notepad and a bit of time.

Now, I am aware that people have raised issues about my tolerance for puzzles.
