### ISSUE TITLE
Abandoned crates should explode when shot

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#461]
Brought up in #460

Players abuse emitters and lasers instead of opening the crates like they should, which leads to other abusive problems down the line when they start lasering open gun crates and stuff.

**Comment by Screemonster** [comment]
At the very least, using a gun/emitter to bypass the puzzle entirely shouldn't be _objectively better in every way_ than solving the puzzle.
Not only is it faster and simpler, it's a guaranteed success.
I'll take a look at the crate code - would we want it to _always_ explode when shot, or have a small chance of successfully opening it?
(for reference on the odds, old crate had 30% chance by random guessing, while new crates have a 1/504 chance. With a tool, old crates went up to 70%, while a skilled player can crack the new ones pretty reliably - new ones are _way_ more skill than RNG in getting them open)

**Comment by SpadesNeil** [comment]
I want it to always explode. You're shooting a supposedly tamper-proof crate packed with explosives to destroy its contents if tampered with.

**Comment by Screemonster** [comment]
Coolcool. Same for emagging/eswording/emping?

**Comment by SpadesNeil** [comment]
Yes.

**Comment by Screemonster** [comment]
Makes sense, it _is_ a "cryptographic sequencer" so codebreaking should be its _thing_.

Line 167-171 of /code/modules/mining/abandonedcrates.dm have the boom - abandonedcrates.dm also has them unlock when emagged.

The code for _crates_ has a thing for being attacked with an emag _or_ an esword that is slightly different to what abandoned crates do. I'm not super-familiar with how byond-code handles inherited stuff, but does this mean that since abandoned crates are a child of crates, their version of what happens when you emag them takes precedence?

This is probably the first actual codey-thing I've tried to tackle :p

**Comment by SpadesNeil** [comment]
I'll try to find it. It's something like bullet_hit() or bullet_act() or something along those lines, and it's part of the crate object class overall. I have to overwrite the function for abandoned crates so they explode.

**Comment by Screemonster** [comment]
Cool. I flung a thing to you in skype but I think that was the explosion one.

One solution I was considering was giving crates a new var like "tamperproof" or "secure" or something like that and having them check that var when you shoot/bomb/emp/sword them. If 0, proceed as before. If 1, boom.

**Comment by SpadesNeil** [comment]
There's a better way of doing that. I can just overwrite the function instead of adding new vars. Unless you intend on adding this to other crates.

**Comment by Screemonster** [comment]
I was thinking it'd be a neat thing to add to some of the cargo crates like the super secure ones (EMP gear, military hardware, basically stuff that needs captain/HoS access to open)

**Comment by SpadesNeil** [comment]
> Heck. Give it a 50% chance to explode on shot, and a 50% chance, completely independent, to vaporise the loot. Then there's only a 25% chance that the loot is intact.

Nightwing posted this in Skype. I agree with this. For now I'm going to go forward with this initial fix, but later I want to make a separate github issue to implement something like this.

**Comment by SpadesNeil** [comment]
`/obj/structure/closet/bullet_act(var/obj/item/projectile/Proj)
	if(!(Proj.damage_type == BRUTE || Proj.damage_type == BURN))
		return

	health -= Proj.damage
	..()
	if(health <= 0)
		for(var/atom/movable/A as mob|obj in src)
			A.loc = src.loc
		del(src)

	return`

Found the snippet of code where damage is handled. It's in closets.dm

**Comment by Screemonster** [comment]
Just saw miner and engineer haul three crates into engineering, line them up in front of an emitter, and open all three flawlessly. No messages about the anti-tamper system failing either.

**Comment by SpadesNeil** [comment]
It's possible he was just really lucky. It's a 1/3 chance to open the crates.

**Comment by SpadesNeil** [comment]
Assigning Scree to test this.

**Comment by Screemonster** [comment]
`+			if(5)
 +				visible_message("<font color='green'><b>The anti-tamper mechanism of [src] fails!</b></font>")`

Well, I can say for certain that this bit didn't kick in. I'll have a play with it later.
