### ISSUE TITLE
Virus splicing is partially broken

### ISSUE THREAD

**Issue by Enigmier** [SpadesNeil/VOREstation#463]
When splicing viruses in virology, sometimes you will be unable to splice to a stage at all. . I have no  What will happen is that the button that you click to splice that stage will show the loading circle without ever actually splicing the virus. There have been times were I am able to splice to 1,2, and 3 but not 4 or I will be able to splice to 2,3, and 4 but not 1.

**Comment by SpadesNeil** [comment]
Not marking with severity until bug is confirmed reproducible.

Can you provide step by step instructions of how to reliably reproduce the bug?

**Comment by Enigmier** [comment]
To start off get a virus dish, either from the freezer next to the disease splicer or a virus crate order from cargo. Next you place a dish, any one, into the pathogen incubator. Allow the virus to reach 100% growth density and place the fully grown virus in the disease analyzer. Once completed, splice any one of the symptoms by placing the virus dish in the disease splicer and clicking on the "Splice #" blocks. Preferably the a stage one symptom for the sake of testing. After you have spliced a symptom and saved it to a disk, try to splice the saved symptom to another a different virus. Specifically stage one or four. There is a chance that you will be unable to splice to one of those symptoms. If you attempt to splice to the broken stage, circle will appear next to the splice number and remain there for an indefinite amount of time.The shift I was playing yesterday prevented me from splicing to 1 however I could splice to 4. Today I was unable to splice to 4 but I was able to splice to one. It seems to vary round by round basis.
