### ISSUE TITLE
pandimensional predator idea

### ISSUE THREAD

**Issue by Screemonster** [SpadesNeil/VOREstation#475]
Following a bit of brainstorming in admin chat, we hashed out the basics for an additional area using the belly tiles. (it came about after some pathfinder talk about bags of devouring)

Essentially, we discussed the idea of a singulo-style spacial anomaly that instead of destroying things that entered it, dumped them in a new off-level area (kinda like the wormholes random event, but with a highly specific teleportation target instead of a random one)

Essentially, this idea then developed into some bluespace entity that would occasionally poke its... mouth... into realspace, gobble some stuff up, then disappear.

CODEWISE, this would need the following:

A singulo-variant. It would operate/move/decay in exactly the same way as the ordinary singulo, with a few differences. 1: no radiation or EMPs. 2: no deleting of turfs or anchored objects. 3: stuff that enters it isn't destroyed, and mobs are not gibbed, but instead they're sent to a specific area on Z2. 4: consuming stuff wouldn't make it bigger, essentially putting a cap on its lifespan as it decays and finally expires.

A Z2 belly area. Basically it'd be a stomach for this thing. Non-hostile area with some randomly swallowed junk in it, diary for someone who's been here before. Hints that the critter's like a whale, actually eats bluespace matter and its metabolism doesn't interact with normal matter, and following a short trek from the landing point along some narrow squiggly tubes, a cobbled-together device using the beach's "return to station" sign code - a scientist managed to assemble some of the junk into a teleporter to get out.

Sprites for the swirly dimensional portal mouth thingy, belly textures, and the thing in the stomach that's a means to get back.

Make _this_ the result when scientists put a BoH in a BoH. Stuff like that attracts the spesswhale.

Add it to the events list so admins can have one spawn during a boring shift :p

**Comment by SpadesNeil** [comment]
Recoding the singulo to teleport what it eats would probably be quite easy. It's the level that we need. We can stick it on Z2, indeed.

**Comment by nightwingthedragon** [comment]
Actually, if I can get the time, I'd like to give this a go. Would anyone mind me giving it a crack?

**Comment by SpadesNeil** [comment]
Go for it. If you're gonna be messing on Z-level 2 just give me a heads up before you start any work so I know not to pull any map changes to exodus2.dmm
