### ISSUE TITLE
Changable barsigns

### ISSUE THREAD

**Issue by antsnap** [SpadesNeil/VOREstation#477]
Consider a drider bartender. They would probably want to change the barsign to "The Spider's Parlor" but, that is not possible at the moment. As far as I know the barsign is determined at round start and remains static.

**Comment by Cameron653** [comment]
You need to hit it with your ID, according to the barsign code.

https://github.com/SpadesNeil/VOREstation/blob/c5feac2a7e0f793c47ea76eaee92838bae2d62f8/code/game/objects/structures/barsign.dm#L14-L24

**Comment by Screemonster** [comment]
Cameron653 is absolutely correct. Swipe your ID on it, it'll give you a list of all available signs to choose from.
I didn't know this myself until I added the spider sign.
