### ISSUE TITLE
SSD description should indicate how long a player has been gone.

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#48]
"He has suddenly fallen asleep. (( Player is not connected. ))"

Should be something like:
He has suddenly fallen asleep. (( Player has been disconnected for [time] minutes. ))

**Comment by Arokha** [comment]
Don't think it should be a timer but rather the message should change when beyond whatever our rule is for a threshold of SSD person before putting them in cryo. AKA when it gets to 30 minutes of them being SSD, it can say "They seem to have been asleep for a long time. You should put them in cryosleep."

**Comment by SpadesNeil** [comment]
10 minutes is my limit for being offline. 30 seems like a bit much. Imagine making a player wait 30 minutes to cryo someone so they can have a job slot.

**Comment by Arokha** [comment]
Sure. Seems reasonable, but I think the rules say like 20 or something, might need to update those.

**Comment by Arokha** [comment]
I've addressed this in #225 and also added an 'idle' time in addition to a 'disconnected' time.
