### ISSUE TITLE
Items dropped inside a predator get stuck in predator inventory

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#483]
This is a nasty bug.

Steps to reproduce:
1. Get ate.
2. Drop an item.
3. Get gurgled.

**Comment by antsnap** [comment]
I've eaten many a friendly crewmate. Usually they _look_ like they are stuck, but instead they go into weird slots. Every time I've been able to pull the item out.

So yes the items get put into the predator inventory, but I've personally never had it get stuck there.

I think although this is a bug, it can be useful if the prey forgot to get rid of an important item before scening.

This assumes I'm correct, though. If there's an instance of an item getting **stuck** then it needs fixing.

However we must keep in mind: if an item doesn't go to the pred's inventory, where does it go?

**Comment by SpadesNeil** [comment]
The items get permanently stuck in my experience, because they get dropped into weird slots, but the icon for the slot is above the item that got ate. Items like this shouldn't be lost like this. They should remain in the stomach's contents until those contents are released.

**Comment by Arokha** [comment]
Rolled into #601
