### ISSUE TITLE
Gibbing should make a noise.

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#491]
A nice gruesome splatter sound effect.

**Comment by antsnap** [comment]
Gibbing with what? If you gib with the admin command or wizard stuff, then it does indeed make a noise.

**Comment by SpadesNeil** [comment]
If it does, it doesn't make a sound I've ever heard. You just turn into a pile of meaty remains.

**Comment by Screemonster** [comment]
Just tested with a wizard ei-nathing a bunch of mobs in the holding area. The only noise it made was the electric spark sound for the spell.
Gibbing mobs from the VV panel was also silent.

**Comment by JohnWayne9392** [comment]
I always liked the gibbing sound from Quake 2, if you guys need a suggestion.

**Comment by SpadesNeil** [comment]
I don't know what that is.
