### ISSUE TITLE
Tasald Missing Fluff Items

### ISSUE THREAD

**Issue by Tasald** [SpadesNeil/VOREstation#492]
I have a few items that were approved but haven't seen in game yet, I would have done this sooner, was waiting to see if the pistol was passed.

the revolver and new permit are from this one
http://forum.vore-station.net/viewtopic.php?f=27&t=446

the coat, which I was thinking would still go into the HOS locker is from here
http://forum.vore-station.net/viewtopic.php?f=26&t=340

there's not custom item box that spawns in my bag so i spawn missing items sometimes because of the number i have, and a wallet that i can't prevent from spawning on me.

currently I have the E-Luger, permit, loyalty implant, and a random wallet that spawn on me, and yes, i've tried redoing the custom list items, i just end up with an extra wallet.

**Comment by SpadesNeil** [comment]
Your revolver and revolver permit will be added next server update. I'm going to edit this post to only talk about the item box. Your permit will spawn inside the box along with a wallet and the implanter.

**Comment by Tasald** [comment]
some of the stuff was added, but theres a blank space in the bag i can't get rid of and it all spawns with no box still

**Comment by SpadesNeil** [comment]
What do you want to go in the box?

**Comment by Tasald** [comment]
every thing?, if i spawn as a job like hop or captain it gets rid of some of the items, but if i had to pick, could you stuff the permit into the wallet, then the wallet and implant into the box?

**Comment by SpadesNeil** [comment]
Wallet, permit, implant. Can do.
