### ISSUE TITLE
Jobs whitelist

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#493]
We need a proper jobs whitelist which behaves like the species whitelist in a config file.

New whitelisted jobs will include things like...

- CentCom staff
- Syndicate listening outpost crew
- Mimes
- Clowns
- Blue Shield (if it's ever re-added)

Until this whitelist is added properly, I cannot add these whitelisted positions.

**Comment by Arokha** [comment]
I have this working for the latejoin joblist. Hides jobs you're not whitelisted for, and if you somehow manage to tell it to pick one anyway, it refuses.

Trying to make it work for the job shuffler at round start.

**Comment by Arokha** [comment]
Done.
