### ISSUE TITLE
Exosuits don't register ID's placed in wallet

### ISSUE THREAD

**Issue by ZodiacShadow** [SpadesNeil/VOREstation#494]
As the title says - when you have an ID in your wallet, it provides access for you, just as placing it in a PDA... but exosuits don't register them.

**Comment by SpadesNeil** [comment]
This is a very minor thing I'm not even sure to be worth fixing, but I'll open it for now. If it isn't fixed in a month I'll mark as wontfix.

**Comment by Arokha** [comment]
I am assuming you mean whapping the exosuits with a card to unlock them.

**Comment by ZodiacShadow** [comment]
Don't actually remember if I tested _that_. I meant for providing access to _enter_ the exosuit.
