### ISSUE TITLE
NanoUI does not appear correctly in PDAs.

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#50]
The buttons are not displaying correctly on PDAs. Probably a CSS issue.

**Comment by Leshana** [comment]
Buttons look like this. They have a blue background when hovering, but no default style.
![pda - buttons unstyled](https://cloud.githubusercontent.com/assets/14110581/10236908/8c45e3b8-6879-11e5-8838-f8bca9337fa7.PNG)

**Comment by ShadowLarkens** [comment]
Um, are you sure that the buttons having no background isn't intentional?

**Comment by Leshana** [comment]
Perhaps it is, but if so I think its ugly!
From a UX design perspective, buttons should [afford](https://en.wikipedia.org/wiki/Affordance) clicking.  The icon helps, but it doesn't look like a *button*.
I am presuming the lack of background is what @SpadesNeil was referring to? @nightwingthedragon mentioned it to me on skype as well.

**Comment by SpadesNeil** [comment]
I'm very sure it's not intentional. This is completely inconsistent with NanoUI everywhere else in the game. I want the blue buttons back. This looks dumb.
