### ISSUE TITLE
Medihound Internal Chemical Storage

### ISSUE THREAD

**Issue by Treasa729** [SpadesNeil/VOREstation#505]
The medihound currently only has the sleeper as a form of treating people with chemicals, but they are also equipped with a syringe which is relatively useless because they'd need to pull a beaker around behind them absolutely everywhere to be able to use it, or have the syringe pre-filled with a specific chemical. Not having hands means that they cannot carry anything, and as it stands, they have no method of getting chemicals into their syringe unless they are already at a filled beaker. They can only produce chemicals in their sleeper, and have no method of being able to fill the syringe with those. What I'd propose is some sort of internal chemical storage module (Literally just a beaker or two that spawns in their inventory) that can be filled via their syringe, and then drawn from if the need arises so that they can also make use of the syringe they have.

**Comment by Cameron653** [comment]
I tried to give them a beaker, but it ends up being buggy if you place it in a chemmaster or anything like that, as then humans can grab it and cause other problems. They already have almost all the chemicals needed to heal people no matter what damage they have, and the syringe was so they can use something the chemist might give them, like some dex+ or something of that nature, but only a small ammount of it.

**Comment by Treasa729** [comment]
Ah, that makes sense. It'd still be awesome if we could get some sort of chemical storage anyway, but that's understandable, thanks for the response!
