### ISSUE TITLE
Canine borg modules spam attack logs.

### ISSUE THREAD

**Issue by Screemonster** [SpadesNeil/VOREstation#507]
ATTACK: Treasa/(Myrian) attacked Azeroth_Margican/(Kyla Ever-Wind) with synthetic tongue (INTENT: HELP) (DAMTYE: BRUTE)
ATTACK: Treasa/(Myrian) attacked Azeroth_Margican/(Kyla Ever-Wind) with synthetic tongue (INTENT: HELP) (DAMTYE: BRUTE)
ATTACK: Treasa/(Myrian) attacked Azeroth_Margican/(Kyla Ever-Wind) with synthetic tongue (INTENT: HELP) (DAMTYE: BRUTE)
ATTACK: Treasa/(Myrian) attacked Azeroth_Margican/(Kyla Ever-Wind) with synthetic tongue (INTENT: HELP) (DAMTYE: BRUTE)
ATTACK: Treasa/(Myrian) attacked Azeroth_Margican/(Kyla Ever-Wind) with synthetic tongue (INTENT: HELP) (DAMTYE: BRUTE)
ATTACK: Treasa/(Myrian) attacked Azeroth_Margican/(Kyla Ever-Wind) with synthetic tongue (INTENT: HELP) (DAMTYE: BRUTE)
ATTACK: Treasa/(Myrian) attacked Azeroth_Margican/(Kyla Ever-Wind) with synthetic tongue (INTENT: HELP) (DAMTYE: BRUTE)
ATTACK: somekindofpony/(Glitch.E) attacked Kisuke_Gema/(Kisuke 'The Nerd' Gema) with synthetic tongue (INTENT: HELP) (DAMTYE: BRUTE)
ATTACK: somekindofpony/(Glitch.E) attacked Kisuke_Gema/(Kisuke 'The Nerd' Gema) with synthetic tongue (INTENT: HELP) (DAMTYE: BRUTE)
ATTACK: somekindofpony/(Glitch.E) attacked Enigmier/(Kiran Gradsif) with synthetic tongue (INTENT: HELP) (DAMTYE: BRUTE)
ATTACK: somekindofpony/(Glitch.E) attacked Nyxian/(Giovanni Cannavacciuolo) with synthetic tongue (INTENT: HELP) (DAMTYE: BRUTE)
  Scree: jesus wept I am putting up a github issue to stop those borgdog tongues showing up in my attack logs because ALL I SEE IS LICKING
ATTACK: Treasa/(Myrian) attacked Azeroth_Margican/(Kyla Ever-Wind) with synthetic tongue (INTENT: HELP) (DAMTYE: BRUTE)
ATTACK: Treasa/(Myrian) attacked somekindofpony/(Glitch.E) with synthetic tongue (INTENT: HELP) (DAMTYE: BRUTE)
  Viveret: kek
ATTACK: somekindofpony/(Glitch.E) attacked Treasa/(Myrian) with synthetic tongue (INTENT: HELP) (DAMTYE: BRUTE)

But yes. It does no damage and it's not really an attack, but the synthetic tongue and b.o.o.p. module _really_ need to not be attacks as a third-degree doggy-affection session just fills the admins' screens with a sea of blue and the only way around it is to turn attack logs off entirely.

**Comment by Cameron653** [comment]
Fixing this now. Almost done.
