### ISSUE TITLE
PDAs spit out ID cards in Cryo.

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#51]
Has been an issue since the old code. Is still an issue.

**Comment by OrbisAnima** [comment]
do you want me to destroy the id's?

**Comment by SpadesNeil** [comment]
Cryo should move the ID cards into storage instead of deleting them entirely.

Cryo has recently been updated so that it will deny people who do not have the required access to the console. This will prevent people other than heads of staff retrieving items like guns and valuables.

ID cards should be stored and not destroyed if possible.

**Comment by OrbisAnima** [comment]
Ok, I was able to preserve the ID's but not yet do so with the pda, thinking of giving the pda an special proc just for this case

**Comment by OrbisAnima** [comment]
Fixed, only problem is that I get a warning of "unused label" code works byond that

**Comment by OrbisAnima** [comment]
Fixed :dancers:

**Comment by SpadesNeil** [comment]
Make a pull request then and reference this issue #51

**Comment by OrbisAnima** [comment]
yus, I am on it
