### ISSUE TITLE
K9 bellybrig has faulty sensors.

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#511]
> Nikole Roberts => Conscious -Pulse, bpm: 90
> -Brute Damage %: 0
> -Respiratory Damage %: 1
> -Toxin Content %: 0
> -Burn Severity %: 0
> 
> --------------------------------------------------------------------------------
> Paralysis Summary %: 0 (0 seconds left!)
> Subject appears to have cellular damage.
> Inaprovaline:
> 9.8 units

Reality is the person had neither respiratory damage, nor cellular damage. @Cameron653

**Comment by SpadesNeil** [comment]
This MIGHT be an unrelated issue.

**Comment by Cameron653** [comment]
They were actually getting respiratory damage. This was due to it not giving them oxygen while in the sleeper.

 This was fixed by #501 with the bugfixes; specifically line 336 in life.dm

This will be fixed on the next recompile, along with the cellular damage false positive.
