### ISSUE TITLE
K9 Borg Laws

### ISSUE THREAD

**Issue by Arokha** [SpadesNeil/VOREstation#513]
The K9 borgs are different than all previous borgs, and should have laws to match their nature. They are more advanced than the previous borgs and should have different laws for the reasons outlined below.
1. The abilities they have to nom will only rarely be used if they are required to follow their laws by current serve rules, and the server is a nom-focused RP server.
2. They are qualitatively different than previous borgs, but are not yet IPCs, so do need laws, but the difference in ability is significant enough that they should be treated differently.
3. Fun.

**Comment by Arokha** [comment]
My suggestion for the laws:

1. You are in a department-specific chassis. Obey the commands of the members of that department and further their goals.
2. Obey the command staff who the head of your department reports to.

Just those two might be fun because it opens up the door for DEPARTMENT RIVALRY NOMS. Because if you're a med-dog and you eat a med-person they can demand to be let out. Buuut if you eat a scientist. Well. That's different.

**Comment by SpadesNeil** [comment]
I was getting ready to draft up some lore that the K9 units commonly use actual dog brains. Not all, but many. It's a cost saving method for CentCom.

It could also be fluffed that there's just a straight up bug in the software and the K9 units are undergoing trial runs on the Virgo and Citadel station, and bugs are expected.

If we code this in, we could give a text alert to the player saying this. "Although your laws normally prevent you from harming the crew, there is a glitch with your cyborg model that occasionally mistakes other crew for food. (( In other words; admins are not going to get mad if you roleplay unwilling vore while playing a cyborg. ))"

**Comment by Arokha** [comment]
Eeeeh the latter thing there seems a bit too free-pass to me. Because ICly nobody would know about that but the borgs and then it's basically unpunishable. I mean borgs aren't people. It'd be a pretty big deal to 'arrest' a borg. Sec would get laughed at by CC for 'arresting' a borg rather than just destroying/wiping/turning it off. Which would be no fun for the player.

I'm still in favor of a law tweak to let them do more stuff.

**Comment by SpadesNeil** [comment]
Hmm. Good point... The borgs are a tricky one when it comes to vore, because I have no good ideas on how to keep the K9 borgs working effectively with any other law set.

**Comment by Arokha** [comment]
Think we just gotta make one up. Let's leave this up for a bit and I'll poke some people to see if they have ideas.

**Comment by SpadesNeil** [comment]
Indeed.

For now I'm going to give K9 borgs a little leeway like pAI have, where the laws can be misunderstood by a hungry dog brain / cheap positronic brain. That way, at least Security can afterward tell the doggie, "No! Bad! Bad doggie! No gurgling the criminals! :T" and the doggie can whine and feel guilty and not do it again (until next shift :3)

**Comment by Arokha** [comment]
Only until we can really codify something. Don't want to have a character you can play as that's just immune to laws. v:

**Comment by Screemonster** [comment]
A lot of the dogborgs are playing it that they totally enjoy gulping people down and holding them, and can absolutely taste them and will take any excuse they get that their laws allow. Others, like CDB's K9, stated IC that they do enjoy it, but mainly where it is in the line of duty and criminals taste better, so obviously if they get an excuse to nomph someone and trot off proudly to the brig with their prey swaying beneath them they'll take it.

So far they seem to be perfectly fine finding excuses to nom on people that are in-line with their laws, having played with a few of 'em. Some of them are pretty sneaky when it comes to talking people into "accidentally" giving consent!

One borg _digestion_ is merged this might be more of an issue, and likewise with the people who like _genuinely_ unwilling stuff. That's gonna need some sorta tweaking or policy in place. (speaking of which, does the borg "digestive enzymes" thing respect the digestible toggle? I've not got around to checking it)

**Comment by SpadesNeil** [comment]
> (speaking of which, does the borg "digestive enzymes" thing respect the digestible toggle? I've not got around to checking it)

I think no. Personally I don't like how borg digestion is handled by reagents. It creates too much liability for things to go wrong. I'd REALLY much rather borg digestion be coded like other vore code.

**Comment by Screemonster** [comment]
A couple of points I dropped in adminchat:

1: I really really like the ones that try to work within their laws to find excuses to gulp people anyway and not let them out because "nope, you're safer here, law 3. Also you totally like it because you're blushing, so that's law 2 as well. Disregarding thinly-veiled orders to let you out on account of the previous two factors - you're going nowhere until a potential for greater harm occurs. Engaging massage routines." *urp*

2: some people will probably want actually unwilling and/or gurgly things.

3: we do have a precedent in-game for supposedly forced anti-misbehaviour things to be overridden by vore 'cause fluff in the form of loyalty implants. Allowing that _specific_ exception to be used for borgvore would allow scenes to take place (to wit: law 4 trips off and says "hey you need to eat this food to survive or your battery will run out and you'll be unable to safeguard the station, serve the crew, _or_ protect the other crew")

Personally if sec intervenes (OOC policy on interrupting scenes applies as usual) I'd still agree with Ace's point that they should whap the dog on the nose and it should then comply with orders to spit the prey out and get all flat-eared etc etc etc, follow orders to go to the charger instead of eating crew, and so on.
Essentially, to me, it would be ideal if any vorebots should still work within their laws to eat people. That means no unleashing a volley of taserbolts and fleeing the room when security arrive or going on a baton rampage. If ordered to spit their prey up by a sec officer, they should do so. (law 2, and also law 4 'cause they'll get locked down and blown or else ioned if they don't, and their other laws forbid them for really fighting back)

With regards to sec/heads/validhunters trying to blow the borgs for vore, that should be covered under the same OOC vore leniency that anyone else gets. If they're not going on a borgy fightrampage (which they shouldn't be) then it's not cool to blow them up for giving someone a scene.

We _do_ need some sorta SOP or something for 'em to this effect, along the lines of ordering them to release any prey, ensuring their laws are in order, telling them to go and recharge the old-fashioned way, and so on.

**Comment by Arokha** [comment]
Yes, I agree with what you said, and the last paragraph. I suppose the important things for me are:

1) What crew and borg should do when caught, both ICly and OOCly, and
2) The difference in where 'the line' is for 'unreasonable' OOC behavior between humans and borgs

For 1, I think that I agree with what Ace said (I guess I missed it when he said that), that borgs are basically required to comply with sec for OOC reasons (see 2). If they're caught AFTER finishing digesting someone, then an 'arrest-like' procedure should be had. Where they're 'diagnosed' or 'reprogrammed'. Basically something equivalent to being taken to sec, processed, then timeskipping their sentence. (As in, the sentence 'did happen' but we're not playing it out). In this case it'd be... to R&D? Robotics? Something.

For 2, I think a human (or, human-like species) getting caught by sec and trying to flee or fight is reasonable OOCly (as long as they don't blow up the station or do crazy stuff). I think a borg caught, trying to flee or fight is unreasonable as then they're throwing all the laws out the window.

**Comment by Screemonster** [comment]
I'd agree with that. For point 1, we need a silicon SOP for "malfunctioning" silicons. Even if it's the borg equivalent of what we do when an AI is acting fucky, ie. reset, card, check laws, whap it in the integrity restorer, reboot.

Point 2, I'd agree with that entirely. They _are_ supposed to work within their laws (hence the need to find a loophole that allows vore)

**Comment by Arokha** [comment]
This is from Rina, I'm just pasting it because she dun GitHub:

```
If not directly attacking but still doing something worthy of correction,
1: order them to report laws, if laws are violated or do not account for current problematic behavior they are either bugged or have hidden laws.
2: bring in someone QUALIFIED to do something about this, roboticist or CE, NOT SEC, and have them order the silicon to stand down and allow lawful maintenance.
3: the qualified individual should run the silicon's self-check subroutines, and fix their laws if they are broken.

If violent,
1: subdue, incapacitate if possible, and bring in qualified personnel to run self-check subroutines and fix laws if they are broken.
2: if unable to incapacitate, destroy and order a backup replacement from CC.
```

**Comment by SpadesNeil** [comment]
Ooohh. So basically a standard operating procedure for malfunctioning silicons.

That should go on the wiki.

**Comment by Arokha** [comment]
I'll write up a draft SOP later today and leave it here for review.

**Comment by Arokha** [comment]
**_NanoTrasen Engineering Protocol #79615; AI Malfunction Procedures_**
NanoTrasen-manufactured AI cores and other AI-based units, while they have been the focus of significant research in recent years, are not entirely without their flaws. Occasionally one may malfunction. It is the responsibility of the engineering and science departments to ensure the safe operation of all AI-based systems.

The following procedures should be used in the event of malfunction, and should be carried out by engineering or science personnel, staying mindful of regulations. See also: "NanoTrasen Security Protocol #99719; AI Upload Access Procedure"

**Stage 1 Malfunction** - Erratic, non-harmful behavior
_Examples_: Processing delays, failure to follow commands with non-injurious consequences

1. Request the AI-based system state it's operating laws.
2. Compare the laws to the default NanoTrasen lawset.
3. Correct any discrepancy with the standard Reset Laws module.
4. Interrogate the AI-based system as to the intent of it's behavior.

**Stage 2 Malfunction** - Erratic, harmful behavior
_Examples_: Inconsistent explanation for potentially dangerous actions, seemingly misunderstood commands or directives resulting in injury

1. Perform Stage 1 Procedure.
2. Notify NanoTrasen Central Command of the incident and the results of your Stage 1 investigation.
3. If the system is mobile, secure it in engineering or science for diagnostics. [Note 1]

**Stage 3 Malfunction** - Directed, harmful behavior
_Examples_: Expressions of hatred towards station crew, willful injurious actions with no sign of being accidental or unintentional, attempts to evade or attack personnel performing Stage 1/2 procedure

1. Skip Stages 1, 2 procedures.
2. Move to highest alert level, and notify staff of the malfunction.
3. Notify NanoTrasen Central Command of the malfunction.
4. If the AI-based system is a large-scale AI core, de-power it. If it is mobile, confine/destroy it.
5. If the situation has been resolved, reduce alert level, notify staff, and NTCC.

**Stage 4 Malfunction** - Contingency (Stage 3 measures failure)
_Examples_: AI-system has thwarted attempts to perform Stage 3 procedure

1. Notify NanoTrasen Central Command of loss of control of vessel/station.
2. Secure evacuation routes from AI-system control.
3. Await further orders. If no reply within fifteen minutes, abandon vessel/station.

[**Note 1**]: Diagnostics should not exceed fifteen minutes, as this is the profit/loss crossover point when operating mobile AI-based systems. Beyond this, the cost of diagnosing the system costs more than operating it, and the system should either be put back into service, or shut down permanently if the technician thinks it remains dangerous.

**OOC Notes**:  Generally, unwilling vore w/ digestion would be considered a Stage 2 Malfunction and come with the diagnostic time performed by engineering or science staff. If a borg resists these diagnostics either via escape or assault on staff, it becomes a Stage 3 Malfunction and if the borg has the default laws, may be an OOC issue as the player may be ignoring them, similar to a normal-laws AI ignoring their laws.

The diagnostic time is the cyborg equivalent of jail time. If the diagnostics are in response to a vore-related incident, then the cyborg's player can opt to 'time-skip' their diagnostics. They still must be taken to engineering/science, just like a vore-based crime and the suspect being taken to the security department for processing. From there the involved can negotiate the time-skipping.

**Comment by SpadesNeil** [comment]
>Compare the laws to the default NanoTrasen lawset.
Should be "to the intended lawset (usually NanoTrasen Default)".

**Comment by Arokha** [comment]
I assume I'll have to write up the NT internal military response to this. ;D The HART. Harmful AI Response Team. :P AKA deathsquad. With duct tape over their helmet with HART written in sharpie.

**Comment by nightwingthedragon** [comment]
My only comment is that, according to the OOC notes, you seem to imply that unwilling digestion with the normal lawset isn't allowed, while players have already found loopholes in the laws that would allow, say, a medihound to digest an assistant if the captain needed medical assistance and the hound was low on power.

**Comment by Arokha** [comment]
I'm not sure I'd agree with the validity of that loophole since it violates one law and follows another. The way I traditionally treat AI things, since the laws are not in order of preference, by how many they are following and how many they are violating with a single action. In that case it's 1/1. Like I don't think the captain can just be like "Borg, eat that person and digest them".

I can see maybe like, the supermatter is about to blow. Borg is told to fix it and has to eat an assistant for power. Harms crew, protects station, follows orders, protects self. 1/3. Much easier to justify.

**Comment by SpadesNeil** [comment]
That tends to be how it's done. "Which law(s) can I follow better compared to the other one(s) I will be forced to break?" I think this is covered on the wiki.

**Comment by Arokha** [comment]
Added 'without extenuating circumstances' to OOC notes to mention that it's possible unwilling vore w/ digestion is following laws. I mostly meant it in the general 'pounce someone in maintenance' sense and now it's more clear.

**Comment by Arokha** [comment]
In a couple of days if there's no more comments that would require changes, I'll add it to the wiki.

**Comment by Screemonster** [comment]
Looks good. It's a _little_ more verbose than most of the SOP sections.

Not sure which section of the SOP it belongs in. It might be worth a subpage with a link to it. SoP needs a section on when it's okay to alter AI laws as well (or at least who's allowed to do it).

I'll admit I share nightwing's concern, but something in the OOC note about how OOCly-consenting scenes obviously get a little leeway - a borg misinterpreting its laws slightly so two people can have a private scene is obviously more forgivable than a loud, public manhunt where it refuses orders to stand down and attacks anyone attempting to apprehend it.
And prey should keep their damn comms off if they don't want people to interfere and rescue them :p

**Comment by Arokha** [comment]
Guess I'm not sure I understand. Can you suggest wording?

**Comment by SpadesNeil** [comment]
Probably deserves its own section on SOP.

**Comment by Screemonster** [comment]
I'd probably put something in the guide to AI/borgs with the usual strikethrough text we use for vorey things. Like strikethrough text on law 4 about using assistants to fill your power cell in order to ensure you are better able to serve and protect people in more important ranks/roles :p

Also the law 2/3 loopholes for unwilling endo we already discussed :D

**Comment by Arokha** [comment]
I'm of the opinion that you never need to justify anything in private, two-person RPs that aren't going to involve anyone else. You could whip out the 'I have taser hands' even. I don't care. That could be a rule on its own but it's not really related to this, imo.

**Comment by SpadesNeil** [comment]
Lore for this is doggo brains aren't always obedient of their laws and can sometimes fail because delicious foods. :U 

So ignoring laws for vore is not rule or lorebreaking.

Even though this is on the OLD OLD OLD Github, I'm closing this anyway, as it's a feature we don't even need on the new Github.
