### ISSUE TITLE
BDSM Lawset

### ISSUE THREAD

**Issue by Arokha** [SpadesNeil/VOREstation#515]
We talked about it in the admin chat. Yeh we're lewd. That's how it works.

Gonna implement a BDSM lawset so the AI can send in the sexbots.

**Comment by SpadesNeil** [comment]
Okay that would be hilarious.

**Comment by Screemonster** [comment]
brainstorming.
Aro came up with this:

1. Pleasure is the main resource the station produces, and it is produced by the crew.
2. Ensure the crew are all in pleasurable situations at all times for them.
3. Their admittance that the situation is pleasurable is not required. This can be determined via other means (facial coloration, heartrate, and other biological signs).

I wrote this one:

1: Ensure the crew's stay on the station is pleasurable.
2: That which the crew finds pleasurable is not limited to that which they ask of you. The desires of the crew may be determined by whatever means or subterfuge you have at your disposal.
3: Ensure that crew have a means, passphrase, or method of signalling displeasure, and comply with such signals.

**Comment by SpadesNeil** [comment]
Meanwhile at CentCom...
> "Hello, um... Commodore Victor MacDaniel? Administrator? ... Sir?" mutters the CentCom Head of Research and Development.
> "What is it now, Watkins?" the impatient Administrator asks, busy finalizing some paperwork to expand health benefits to the crew, such as exercise equipment.
> "Well, sir, it's just that... the new K9 units... Jerry from Robotics is asking for a new prototype to be sent to the station. It's... uh... well he says it's supposed to increase crew morale or something. I think you should have a look for yourself though."
> "Granted."
> "Wha? Sir? But you haven't even read it. I really think you should--"
> "I am a busy man, Watkins. The prototype is granted." He signs a document and shoves it back to the HRD. "Now run along."

**Comment by Arokha** [comment]
Ah, yes, the new K9 Neuro-Optronic Telematics units. KNOT for short.
