### ISSUE TITLE
Xenos can no longer slash apart tables

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#521]
Really, baystation?

**Comment by DemicusMaximus** [comment]
Cant slash tables, can't go invisible, and the cool 'attack' sprites for being in Hunt speed are missing. BUT HEY, ITS REALISTIC SOMEHOW! >_>

**Comment by SpadesNeil** [comment]
No Baystation just thought it would be smurt ppl and shift everything over under the /human directory so they could put clothes on Xenos.

# BUT GOD FORBID THEY PUT A HAT ON IAN CUZ THAT'S ANIMAL ABUSE.

The only reason I don't change it back is because it actually makes Xenos use the same vore code as humans.
