### ISSUE TITLE
Add "preferences" section to flavortexts.

### ISSUE THREAD

**Issue by Screemonster** [SpadesNeil/VOREstation#524]
A lot of people are running into the character limit with flavortext, especially if they have wordy preferences.

Suggest adding a "preferences" field along with the other flavortext sections that always shows up regardless of what is being worn, so no matter how verbose people get with the rest of their character description, RP preferences are always visible and won't be cut off.

People will also have less excuse to not fill them out, which will have us admins beating our heads off the table less.

**Comment by Dhaeleena** [comment]
I think this should be added, not ASAP but it SHOULD be added, i see it as something completely necessary for a server like ours. I cannot fit my hundred lines of lewd kinks in one place D:

**Comment by UnknownCatgirl** [comment]
I did this once a LONG time back as a commit and got it working, I should be able to try it again and see how it goes.

**Comment by Arokha** [comment]
This would be nice yes. If UC would like it, UC can have a shot!

**Comment by UnknownCatgirl** [comment]
Alright then! I might even be able to get it done today.

**Comment by SpadesNeil** [comment]
Marking as 'minor' because currently, the only way to fill out the entire field is by disregarding the other fields for each body part.

But it'd be nice to have a dedicated "preferences" field contained in OOC brackets.

**Comment by UnknownCatgirl** [comment]
I GOT IT WORKING WITH THE HELP OF CADENCE! Anyways, both commits are on my github page now, going to pull request it.

**Comment by SpadesNeil** [comment]
Reopening because completely broken and had to revert because this wasn't bugtested, and it erased all player's normal flavor text.

**Comment by UnknownCatgirl** [comment]
I did try testing it out via a private server, but was unaware it had erased other flavortext at the time since I didn't exactly have the charactee save data and all that. So, apologies. I'll try testing it and fixing what's wrong later.
