### ISSUE TITLE
Big iron comes loaded with full speed loaders instead of bullets

### ISSUE THREAD

**Issue by Tasald** [SpadesNeil/VOREstation#529]
PFT AHAHAHAHAHHAHAAHHAA

..this is hilarious but needs to be fixed. I tested it and is does not fire with them loaded so no 36 chambered revolver XD.

**Comment by SpadesNeil** [comment]
... Well.. that... isn't... supposed... to happen...

**Comment by Screemonster** [comment]
http://i.imgur.com/rJ4LmdJ.jpg so basically this

**Comment by SpadesNeil** [comment]
Oh yea nevermind is feature not bug. :D

**Comment by SpadesNeil** [comment]
... I'm kidding.
