### ISSUE TITLE
dogborg digestion breaks the sleeper

### ISSUE THREAD

**Issue by Screemonster** [SpadesNeil/VOREstation#531]
http://forum.vore-station.net/viewtopic.php?f=20&t=616

Report thread here. Digesting gets rid of them, but doesn't empty the sleeper to allow the borg to eat another person.

**Comment by killer653** [comment]
The way you can clear it is by clicking the "eject" button. That being said, I'll see about having it do it automatically so people aren't required to do so.

**Comment by Screemonster** [comment]
Well, if clearing it's just a matter of clicking a button then that's bumping the priority down.

**Comment by killer653** [comment]
Yeah. It should work if you click the eject button unless something is _really_ messed up. Should be an east enough fix when I get home.
