### ISSUE TITLE
Virtual Reality

### ISSUE THREAD

**Issue by Arokha** [SpadesNeil/VOREstation#535]
VR System needs:
Visor item for observing
DNI item for playing
Console for changing things in environment
Map area for VR
Code for moving into/out of VR
Code for console to do things in VR

Visor item:
Just a headset to watch people in VR. No means to affect input. This basically snaps your viewport to the VR areas like a camera monitor would.
This is cheaper to make than the DNI and probably has a few for free at CC for VR combat events or something. Might be a few for free on station.

DNI item:
Made by R&D, more expensive. Direct neural interface head-mesh. Fits over scalp. Allows user to interact in VR.
Original idea was to copy your body, but instead make that one option in a menu, with others being generic other race avatars (Furries don't play as humans on SL)
Captain might get one for free.
Does 50 or something HALLOSS on getting dumped out by death in VR.

Console:
Has a menu to affect VR areas, like changing the environment (spawning rocks/trees and replacing floor tiles with snow or grass, really. Or bellystuff c~c)
Also can spawn mobs for combat things. Maybe even wave-based combat minigames? Nothing too complicated. Don't want intense game-in-game thing.

Map area:
Would likely be on same z-level as centcom, with the other stuff like wizard base and whatnot.
Maybe just a cross-shaped hallway with a 5x5 or 7x7 room at the end that's a space that can be customized and used. Each has a console.
Could also be like 3 small 1 big one. Either way the code will be annoying, the bigger it is, coding all the little preset areas. Maybe use holodeck cheating.

**Comment by Cameron653** [comment]
Make sure you aren't instantly able to enable/disable VR mode, as I've seen servers that have done this and ended up being able to be crashed by someone using an autoclicker. Give it some kind of delay, like 1 minute or so.

**Comment by Arokha** [comment]
Sure. I can fluff it as like, too stressful. Or hell, maybe leaving VR gives you 10 HALLOSS period. Doing it to fast KO’s you.
