### ISSUE TITLE
Blindness in BYOND 510

### ISSUE THREAD

**Issue by Arokha** [SpadesNeil/VOREstation#537]
The way blindness works is that there is an overlay ('blind' var) that is moved from layer 0 to layer 18 when the mob is blinded that is the size/shape of the screen with a little transparent hole in the middle. This is in life.dm. 

Unfortunately in 510, layer 0 is rendered like other layers. This results in all carbon mobs (aka all players) being blinded as soon as they spawn in.

The overlay needs to be hidden some other way (0 alpha, invisible = 1, etc).

**Comment by DemicusMaximus** [comment]
Currently running one of the 510 revisions, and cannot replicate. Can anyone else verify?

**Comment by Arokha** [comment]
This wasn't on our server, happens on servers running 510 with 510 clients.

**Comment by SpadesNeil** [comment]
Was this ever resolved?

**Comment by Arokha** [comment]
No, not yet. Can confirm it's still a problem in 510.1339

**Comment by SpadesNeil** [comment]
@Leshana or @Arokha or @Cameron653 want to take a crack at this? I'd do it myself but I'm not as good of a coder as I'd like to be. I do not even yet know where blindness is handled in the code. I can probably figure it out if I _have_ to but I won't figure it out quickly.
