### ISSUE TITLE
RUST Doesn't Work

### ISSUE THREAD

**Issue by Leshana** [SpadesNeil/VOREstation#54]
The RUST fusion engine doesn't work!  Oh No!
* Some of the parts are inobtainable in game.
* Gyrotron computer completely inoperative
* Its over 9000

**Comment by SpadesNeil** [comment]
RUST never was totally finished in Baycode. Or anywhere, last I checked. Would be nice to complete it.

**Comment by SpadesNeil** [comment]
I may remove RUST entirely from cargo to avoid confusion.

**Comment by SpadesNeil** [comment]
Supposedly some parts can be produced with plasteel, and not just bought through cargo. I only commented out the code, so perhaps run a test server with it uncommented?
