### ISSUE TITLE
Remodeled CC Office

### ISSUE THREAD

**Issue by DemicusMaximus** [SpadesNeil/VOREstation#540]
Used up some of the empty space, plus added more actual office functionality. Added a coffee table with chairs so the reps have a less formal place to sit and talk. Also added r-walls, since this is a command-level room, it was bombed recently, and crew have a bad habit of breaking in through the walls since that is easier than hacking a door.

http://i.imgur.com/ZPHNO3p.png

Please note, the plants icon should be the sakura tree, as per Joan's request. :3

**Comment by SpadesNeil** [comment]
The pink tree, yes?
