### ISSUE TITLE
Telecoms terminals lack frames.

### ISSUE THREAD

**Issue by Screemonster** [SpadesNeil/VOREstation#552]
See image: http://i.imgur.com/vghwVb5.png

Whatever frame sprite they're supposed to be using, it isn't displaying.

**Comment by Arokha** [comment]
What's the path for those computers?

**Comment by Screemonster** [comment]
(E) (C) (M) type = /obj/machinery/computer/telecomms/monitor 
(E) (C) (M) type = /obj/machinery/computer/telecomms/server 

(E) (C) (M) parent_type = /obj/machinery/computer/telecomms
