### ISSUE TITLE
Beepsky attacks deathsquad/ERT.

### ISSUE THREAD

**Issue by Screemonster** [SpadesNeil/VOREstation#554]
As per title. Officer Beepsky seems to respond to death commando gear as a level 4 infraction - which is normally the weapon check. Officer was wearing the normal central command ID which suggests that they don't have weapon authorisation.

Worse, the handcuffs that were spawned had no in-hand icon.

**Comment by Arokha** [comment]
That's interesting. The CC IDs typically provide immunity to bots, as they are unobtainable without admin assistance. As the code puts it:

```
	//Agent cards lower threatlevel.
	var/obj/item/weapon/card/id/id = GetIdCard(perp)
	if(id && istype(id, /obj/item/weapon/card/id/syndicate))
		threatcount -= 2
	// A proper	CentCom id is hard currency.
	else if(id && istype(id, /obj/item/weapon/card/id/centcom))
		return 0
```

This is in the middle of the proc that determines threat level. So a CC ID doesn't even modify threat level up or down, it literally just sets it to 0. However Beepsky can only see IDs you're wearing in the ID slot or in a wallet.

**Comment by SpadesNeil** [comment]
Deathsquad does not spawn with a CentCom ID. They spawn with a normal ID that has CentCom access. Big difference that should be altered.

The question is, do we make Beepsky check CentCom access, or do I just create a new SWAT ID and call it a day? I can't give them straight up CentCom ID's for lore reasons.

**Comment by SpadesNeil** [comment]
Okay I know how to fix this.
