### ISSUE TITLE
Prey being deleted when their predators are removed from the game.

### ISSUE THREAD

**Issue by Screemonster** [SpadesNeil/VOREstation#560]
At the moment, unless something's changed and I never noticed, if a predator is deleted by some means (being eaten/digested themselves, cryo, etc) then the prey are also immediately deleted and kicked to observer mode.

This can result in undesired behaviour, ie. endo prey getting digested along with their predators when matryoshka vore scenes happen, and prey remaining on the manifest and taking up a slot when their predator takes them off to cryo.

Ideally, prey with digestible=0 should be moved into the top predator's stomach if their predator is removed via digestion, and cryopods should _also_ cryo any prey that a character is carrying when they go to cryo, freeing the slots and erasing them from the manifest.

**Comment by antsnap** [comment]
This is indeed somewhat of an issue, but it makes sense for immersion AND probably doesn't happen that often (what endo prey doesn't hop out when their pred is getting digested? Usually digestion/death will turn them off from that scene).

However, for those few it would be uncomfortable. So I am obviously for fixing this. It will only make RP safer and more enjoyable.

**Comment by Arokha** [comment]
Actually my dogborg noms code does this already. I'm going to make a new issue that rolls up all the things I want to write into a new vore system, and close this as it'll be a dupe then. brbrbrbrb.

**Comment by Arokha** [comment]
Rolled into #601

**Comment by Screemonster** [comment]
Reopening as cryo still doesn't cryo prey. Was absorbed and ghosted at the time but don't see why that should matter.
