### ISSUE TITLE
Movement speed permanently lowered after digestion

### ISSUE THREAD

**Issue by DemicusMaximus** [SpadesNeil/VOREstation#563]
Have not tested this with normal crit (ex weapons fire), but if you get eaten, digested down to near death (seeing white, 150-199 damage) and are released and patched up, your movement speed is permanently stuck at around 6. Normal seems to be around 10. Have tested this about five times now, each time giving the same result: The rest of the round you're stuck at about half speed.

move_speed = 6.5

Healing, a-healing, medicines, attempting to edit the var, nothing seems to reset movement speed.

**Comment by DemicusMaximus** [comment]
Addendum: move_speed seems pretty inconsistent. 3.5 is faster than 6, but 10 is faster than 6 too. Is this actually the variable that controls how fast your character moves? And if not, what is causing this slow-down?

**Comment by SpadesNeil** [comment]
Does nutrition level change this?

**Comment by Arokha** [comment]
Could be nutrition yeah, or, if you search 'bad' in the vars on you, do you see any bad organs? Could be bad legs.

**Comment by DemicusMaximus** [comment]
Nutrition going up or down does not seem to effect.

As for "bad" vars, I will have to test.

**Comment by DemicusMaximus** [comment]
Further tested. Nutrition values seem to not have an effect. No "Bad" organs are listed. Damage to legs and groin is 0. Move speed starts at ~3, raises to ~6, and remains that way. for at least 30 minutes. Tests haven't gone longer than 30 min so far. Tested as human, taj, and akula just in case of species issue, similar results.

One abnormality. Changing the variable "next_pain_time" from 86276.1 to 0 changes move speed to 3, but the on screen speed has returned to normal, despite normal move speed being ~10. Dafaq Move_Speed, behave yourself.

**Comment by DemicusMaximus** [comment]
Disregard previous "next_pain_time", MORE tests seem to indicate it was unrelated as well. But these tests show that the slowness happens any time you are brought to "whiteout" levels of crit (150-199), regardless of how. 

Further tested to see if this was a result of admin heals, or slow heals. Slowness was still present in both scenarios. (a-heal vs healing pills over time)

**Comment by SpadesNeil** [comment]
This doesn't seem like a bug. This seems like the input of weariness after injuries so you can't just hop back up and sprint right back into the frey the instant you're healed. I do not think this is a bug.

**Comment by DemicusMaximus** [comment]
Closing issue since, after you mentioned it, this does actually seem like a feature. In the words of our glorious overlord Howard: "It just works"
