### ISSUE TITLE
OOC Notes Redundancy

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#567]
Flavor Text, we have a Preferences section. However we also have OOC Notes on the main character setup page. Why do we have both? This looks like a bug. Where does one apply where the other does not?

"General" flavor text also has a blurb about how it includes OOC preferences. It should no longer say that.

**Comment by Screemonster** [comment]
Just tested the "OOC notes" thing, shiftclicked myself, the text I entered didn't appear anywhere.

**Comment by SpadesNeil** [comment]
Then I have no idea why we have that extra feature.

**Comment by SpadesNeil** [comment]
if(config.allow_Metadata)
		dat += "<b>OOC Notes:</b> <a href='?_src_=prefs;preference=metadata;task=input'> Edit </a><br>"

This may have something to do with it.

**Comment by SpadesNeil** [comment]
This has to do with metadata so I'm closing this issue.
