### ISSUE TITLE
CentCom Observer should be implanted

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#568]
They do not have loyalty implants.

**Comment by Arokha** [comment]
Good point. Hm. How do other jobs get that…

**Comment by SpadesNeil** [comment]
It's just a small var I think that adds an implant after all your other gear.

Also they do not have hats! This makes me sad. Also the clipboard and paper should probably be spawned inside their backpack but that's a personal preference.

**Comment by Arokha** [comment]
Pick a hat, throw it in! Guess I forgot it. Just look at special.dm, pretty easy.

**Comment by SpadesNeil** [comment]
I didn't know you could email reply but I'll handle it.
