### ISSUE TITLE
OOC preferences flavor text is not in brackets.

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#570]
It should be in OOC brackets (( Like so. ))

**Comment by Screemonster** [comment]
Might be an idea to put it after all the body-part-flavours as well just for consistency of having all the appearance-related things in one block and the OOC bit after, rather than general-prefs-bodyparts like it is now.

**Comment by SpadesNeil** [comment]
I also noticed this line never appears:

				var/msg = input(usr,"Set your preferences here, Such as your favorite fetishes, or things that you really dislike!","Flavor Text",html_decode(flavor_texts[href_list["task"]])) as message

Don't know why.

**Comment by SpadesNeil** [comment]
Oh I know why now. Fixing.
