### ISSUE TITLE
Change how K9 digestion works, because injecting reagents is REALLY HACKY AND BAD

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#573]
Why can't we just code it to damage people if digestion is enabled like we do other mobs? Literally a button. If they're inside the sleeper and digestion is on, it starts slowly damaging them like it did in the original vore code.

**Comment by Arokha** [comment]
I'll make digestion into a self-cleaning cycle rather than 'injecting enzymes'. I can change the rest into other stuff too if you want but yeah. Also not a bug, as much as you dun like it. Should add a fluff label.

**Comment by SpadesNeil** [comment]
It counts as a bug if it's not working as intended. Digestive enzymes can be injected, then the occupant ejected and continue dying. That is not working as intended. Therefore it is a bug.

**Comment by SpadesNeil** [comment]
However I added this tag because reasons. *nodnod*

**Comment by Arokha** [comment]
Almost done with this.
