### ISSUE TITLE
Hand teles, teleporters in general, and vore

### ISSUE THREAD

**Issue by Screemonster** [SpadesNeil/VOREstation#574]
Okay, so. Teleporters are a bit of an elephant-in-the-room for vore and we need some shenanigans.

If possible, it would be neat if the hand teleporter could skip the part about spawning a portal and instead just teleport the user to the selected beacon (or random point) if they click it in-hand while in a stomach.

Also, teleporting a mob into the same tile as someone else would be funny as hell if it put them inside whoever was standing there :3

Bonus points if tracking beacons are made edible so sneaky predators could pop the bridge beacon in their mouth and wait for the RD to start messing around with the tele.

**Comment by Arokha** [comment]
Sounds fun \o/

**Comment by SpadesNeil** [comment]
oh god yes this would be funny and fun

Worst case scenario players can use the OOC escape function and fluff it as the beacon's inaccuracy teleporting them just outside the predator.
