### ISSUE TITLE
Ready characters start scanned

### ISSUE THREAD

**Issue by Arokha** [SpadesNeil/VOREstation#575]
AKA earlyjoin characters that spawn already 'at work'.

http://forum.vore-station.net/viewtopic.php?f=20&t=567

From this thread. Makes sense to me.

**Comment by killer653** [comment]
Should probably be a toggle so you can opt out of spawn start scan, as it can be used by a crafty Geneticist to impersionate someone if everyone is scanned at round start.

**Comment by Arokha** [comment]
Yup, that was part of the thread. Makes sense to me. This isn't applicable to that many people really since who starts ready at round start? LOSERS, THAT'S WHO? >:CCCCC
