### ISSUE TITLE
Means of removing prey from predators.

### ISSUE THREAD

**Issue by Screemonster** [SpadesNeil/VOREstation#582]
At the moment, the only way to mechanically force a predator to expel prey is by giving them enough toxin damage to make them vomit. Ideally people should be RPing this but it'd be nice to have mechanics to support it.

Adding something like an "ipecac" chemical and adding it to cargo medical crates, a few bottles in medbay, and maybe a bottle in the brig medical area, that forces predators to release all prey (or just induces vomiting without the need for toxin damage) would be neat. Maybe make it expel some reagents too 'cause.. yanno. It's a purgative, give it a legit medical use too. (not blood, don't expel their blood)

For _absorbed_ prey, maybe make it _slightly_ more complicated. Cloning a prey with absorbed=1 should pop up a prompt on the prey's side to ask if they wanna be given a new body so there's no eternal-kidnapping happening. Alternatively, some chemical, possibly derived from clonexadone, injected into the pred to force 'em to separate out.
Nightwing suggested "Mix clonex with ipecac to produce unzorbitol."

**Comment by Screemonster** [comment]
Oh, and let prey resist out of dead preds after a delay. That'll be particularly handy for voremobs.

**Comment by Cameron653** [comment]
Just going to note this down: Absorbed prey don't have the absorbed
variable anymore as it was decided to be redundant and just a safeguard to
prevent preds from accidentally releasing absorbed prey. Instead, they can
be released directly by the pred under the "release" button.

>

**Comment by Arokha** [comment]
I could do both of those drugs thar. Though can't do unabsorby stuff until the absorbing is merged. I'll do the other for now.

**Comment by Screemonster** [comment]
Well, if we just go by some sorta fluff like "yeah, being shot up with a chemical that makes you expel everything from every orifice is PROBABLY gonna mess with your ability to keep someone absorbed because holy hell _that's probably going to be unpleasant and seriously hinder your ability to concentrate_ then that'll do as a stopgap :p

**Comment by Screemonster** [comment]
Resolved in #662
