### ISSUE TITLE
Chargers for borgs in med/sec

### ISSUE THREAD

**Issue by Arokha** [SpadesNeil/VOREstation#586]
Maybe a logout station somewhere other than engineering too? Like in the AI core with the other 2 chargers, or maybe replace 1 of the 6 cryo things with a borg sleeper thing? S'not like 6 people ever log out at once

**Comment by Screemonster** [comment]
A robotic storage unit next to the upload with the charger would be handy for sure. I had to tell a borg where the robostorage was the other day 'cause they didn't know it even existed, that drone-room being so far off the beaten track that the only players that commonly walk through it are engineers setting the SW solars or taking a gas can from atmo to enging waste processing.

**Comment by HethDrakiel** [comment]
There's one in Robotics as well, but it's only the one there

**Comment by SpadesNeil** [comment]
Resolved by https://github.com/SpadesNeil/VOREstation/commit/91f859a9e35a24d6899b876ffddfb53eb66befde
