### ISSUE TITLE
Machine race should be excluded from weight gain/loss

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#588]
I just realized I never added any code checks for preventing machine race characters from gaining or losing weight.

Considering how the code currently works, they cannot be overweight ever, so therefore it doesn't make sense that they can lose weight while starving or using exercise equipment.

I propose tossing in an extra check that keeps machine race weight at the default of 137 at all times.

**Comment by Arokha** [comment]
This is about like, IPCs right? Not about cyborgs?

**Comment by SpadesNeil** [comment]
Correct.
