### ISSUE TITLE
SCRAM button for SME in control room.

### ISSUE THREAD

**Issue by Screemonster** [SpadesNeil/VOREstation#60]
Along with all the other buttons the engineers have on the central console, a button for the guy monitoring the engine coolant to toggle the two emergency cooling valves from the engine room would be neato.

Especially if it's got a big red button sprite. I'll sprite a big red button if necessary.

**Comment by SpadesNeil** [comment]
Sprite a big red button and tell me where to put it.

The problem is I do not know how to activate those cooling pumps remotely.

**Comment by ArbyTheDragon** [comment]
But danger is fun! Why would you want to make cooling the engine in an emergency a safer job? :3
