### ISSUE TITLE
Skrell Bodies Aren't adecuate for our skin code

### ISSUE THREAD

**Issue by OrbisAnima** [SpadesNeil/VOREstation#61]
the file r_skrell.dmi in icons/mob/human_races should be of a light grey hue like the other Races, and so they cannot get proper colors.

Vox suffer the same fate, but Unknown if this is inteded.

**Comment by SpadesNeil** [comment]
Vox will not have it.

Skrell, I am debating. I think they should still not have it. But this is a personal opinion.

Until I get more opinions, I won't tag this as "enhancement" or "won't fix".

**Comment by SpadesNeil** [comment]
Considering no one is saying anything, marking as wontfix.
