### ISSUE TITLE
Put micros in vending machine

### ISSUE THREAD

**Issue by Arokha** [SpadesNeil/VOREstation#614]
So that the next item vended is the micro instead of the requested item? :D

**Comment by DemicusMaximus** [comment]
Meh, doubt it would be used more than a few times, then be forgotten.

**Comment by OrbisAnima** [comment]
The feature or the Micro?

**Comment by Screemonster** [comment]
I can think of a few micros that would go for this, but the issue is that they'd kinda get bored waiting for someone to show up :p

**Comment by OrbisAnima** [comment]
For starters, you will want a way to show up there is a Micro for sale, and a button for the micro to escape, even if it's just resist and 2 minutes escape. Hell, it could be a viable alternative for the brig.
