### ISSUE TITLE
AI looping 'no interface' message

### ISSUE THREAD

**Issue by Arokha** [SpadesNeil/VOREstation#617]
User clicked on doorway to gateway, may have been emagged or rewired, 'no interface' message looped forever.

**Comment by DemicusMaximus** [comment]
I was there to confirm this bug, but so far can not replicate, nor find any singular variable that affects this repetition. Could it have been a one-off fluke created by some odd combination of variables?

**Comment by SpadesNeil** [comment]
Cannot reproduce.
