### ISSUE TITLE
Add clown and mime jobs.

### ISSUE THREAD

**Issue by Screemonster** [SpadesNeil/VOREstation#618]
Clowns and mimes need to be added and whitelisted.

Marked "map" because they need somewhere to spawn at roundstart at the very least. Since the holodeck has a theater setting, maybe a little "backstage" area nearby would do it. Or just stick them in the bar for now.

**Comment by DemicusMaximus** [comment]
I believe they were removed from the code entirely, cause Bay does Bay things. But it should be easier to re-impliment them if they can be lifted from older code, or from other versions. Rather than have to make an entirely new job from scratch.

**Comment by SpadesNeil** [comment]
Mimes will not have invisible wall spawning and clowns will not have the ability to infect PDAs with viruses. However, other functionalities will remain.
