### ISSUE TITLE
Lighting glitches on Z-levels generated at runtime.

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#623]
![dreamseeker 2016-04-17 21-05-04-52](https://cloud.githubusercontent.com/assets/6484985/14756280/128e4ece-08b6-11e6-8e55-5e195924cea0.png)

To reproduce:
1. Start server with a randomly generated gateway map that has space tiles. Do not include it when you compile the code. Just list it in the awaymissions.txt file.
2. Go into space, or look at space.
3. Turn on a light source of any kind.

Things to test: Does this only happen with the "space" area, or does it happen with others? Why don't normal tiles suffer from this lighting bug?

**Comment by ArgobargSoup** [comment]
Is this generated during the server's startup?  Is there a "refresh lighting" check that could be run without too much lag?
