### ISSUE TITLE
Abandoned Crates not working?

### ISSUE THREAD

**Issue by ZodiacShadow** [SpadesNeil/VOREstation#624]
So... okay, the way abandoned crates are now set up is less High or Low and more Mastermind.
What I don't get is this: I got to a point where I had 4 correct digits in the correct positions... but the crate didn't open.
What am I missing?

**Comment by SpadesNeil** [comment]
@Screemonster !

**Comment by Screemonster** [comment]
What code did you enter?

**Comment by ZodiacShadow** [comment]
Far as I recall, it was 8487.
I'd excluded all other numbers (except zero. Is zero in there?) and confirmed that 4 and 7 belonged in their respective places, as well as 8's placed elsewhere registering as  "correct digit, wrong position". I had a few moves left over, so I double-checked a few things. ^^;

**Comment by ZodiacShadow** [comment]
Lemme clarify. My first move was 1111, which just happened to be 0/0. Nothing correct. So I could test if the 8's were needed by saying 1818.

**Comment by OrbisAnima** [comment]
You can't repeat numbers, it was an old bug that was from the old code when this system was implemented.

**Comment by ZodiacShadow** [comment]
Hah. That means it said 8 was in the correct position twice... because one of them was and the other was treated the same?

**Comment by OrbisAnima** [comment]
Exactly. if 0 was a number in one of the four right answers, throwing 0000 would throw you that it had 4 digits on the right position. You have two ways to solve this Scree, one is redoing the logic so it doesn't count twice or more a digit, the other is making a catch at the end where it discounts from the report any repeated digit.

**Comment by Screemonster** [comment]
If I knew how byond did string manipulation, I'd sanitize the input and have it simply not accept a code with a repeated digit. As far as I can tell the report thing has something with nested for loops to cycle through each character of the input and check them against each character of the answer.

**Comment by OrbisAnima** [comment]
Tested in local, works like a charm. (Also, the code is not spaghetti and can be reused as an example for the puzzles of the new maps on development)

**Comment by Screemonster** [comment]
See also #461 which has been reopened. Nothing to do with the code but does refer to abandoned / tamperproof crates.
