### ISSUE TITLE
Able to Read "Me" commands through walls with Mesons

### ISSUE THREAD

**Issue by Prawneen** [SpadesNeil/VOREstation#625]
So, I was asked to make an Issue here about this. I have noticed while playing the Chief Engineer, that sometimes I can actually read someones entire Me commands through walls while wearing Optical Meson Scanners. I have had that happen two times by now. But it rarely happens. Either I am not near people or it's just a simple bug that occurs because of something I am not able to figure out.

**Comment by Arokha** [comment]
This is SUPPOSED to happen with thermals. Maybe someone copypasta’d the thermals code to make the mesons or something and accidentally left that in.

**Comment by SpadesNeil** [comment]
Probably shouldn't happen with Mesons.

**Comment by Arokha** [comment]
mob/emote.dm : line 46
```dm
for(var/I in view(world.view, get_turf(usr)))
```

Emotes are sent to people in range who can see you turf, according to a comment,
```
//get_turf is needed to stop weirdness with x-ray.
```

I am unsure what this weirdness is, but without knowing I'm not going to just change this and break everything. I can safely say though that changing that would also break emotes from inside someone.

**Comment by Arokha** [comment]
There's another get_turf a few lines lower as well that is probably ACTUALLY the one responsible.
