### ISSUE TITLE
End-of-round stats saving

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#626]
I would like to make it possible to save statistics like flavor text, hair style, body weight, (etc) at the end of the round. This way people who like things like weight gain, transformation, or just want to save their flavor text at the end of a game and forget to do it after 6 hours, can just toggle this on and off and have it automatically saved when the round ends regardless of being logged in or not.

Parameters of this issue being resolved:
- [ ] Verb to toggle persistence mid-round in case you don't like some changes. This belongs under the "Preferences" tab or "IC" tab.
- [ ] Toggle persistence in character preferences, turned on by default.
- [ ] Flavor text should be saved.
- [ ] Internal flavor text should be saved.
- [ ] Body weight should be saved (up to 500). If nutriment is over the required amount to gain weight at the end of round, excess nutrition is calculated and dumped into body weight. (See weight gain milestone for details.)
- [ ] Body appearance (including hair style, colors, taur body, scale, etc) should also be saved.
- [ ] Option should be turned off by default for player prefs, and off by default in human_defines. When a player spawns normally with it turned on, human_defines is overridden by player prefs. This will prevent accidentally saving over an existing character with an admin-spawned character!
- [ ] You must be alive at the end of the round. If you're dead, nothing is saved!
- [ ] You must have random character set to false, or nothing can be saved. The random character option overrides and stops any saving.
- [ ] Going into cryo should save your information as it would during round end.
- [ ] Going into robotic storage should also save information as it would during round end.

I am told this should not require SQL to work. If we figure out how to do this, it is potentially possible we can have other persistent features as well including bank accounts and taking certain items home to keep for bringing on board in the future.

This issue replaces #362

**Comment by SpadesNeil** [comment]
Can @Leshana or @Arokha or @Cameron653 perhaps try to tackle this? Figuring out how preferences is dumped to the player's save file is a good place to start.

**Comment by Arokha** [comment]
This is possible but are you sure...? As long as it's optional I guess.

> You must be able to toggle the option on and off both in character setup and during the round. If it's off at round end, nothing is saved. This option should go under the "preferences" tab.

I assume that's what you meant.

I already did this for the vore code. It's not that hard.

**Comment by Arokha** [comment]
Can it be off by default? I don't want this affecting me, for sure, and I can imagine people getting surprised with it.

**Comment by SpadesNeil** [comment]
> Can it be off by default? I don't want this affecting me, for sure, and I can imagine people getting surprised with it.

Yes.

**Comment by Arokha** [comment]
All you do is call character.client.prefs.save_character() and save_vore_preferences() while playing. Should be tested thoroughly but it's probably that easy.

**Comment by SpadesNeil** [comment]
I will be testing the shit out of this. I've already thought of several scenarios where it can screw up such as cloning and ghosting. We should ensure those are all set up properly. Ghosting for example should count as being dead.

**Comment by Arokha** [comment]
Just make it a verb on /mob/living that you can click. It won't be present on spoopy ghosts.

**Comment by SpadesNeil** [comment]
That isn't quite what I meant by possible bugs, but nevermind it for now.

**Comment by DemicusMaximus** [comment]
Just a question from the non-coder... could this cause bloat? 

Much like how saves get massively bloated in Skyrim the longer you play from having altered many variables from their base state, having to record even a relatively small number of variables between rounds could cause similar issues, no? Especially if you take into account that while our player-base is a few dozen, many players have multiple characters, some as many as 20 characters.

**Comment by Arokha** [comment]
I don’t thiiiink so? It’s saving over the same stats again. Like there’s specifically only X, Y, Z in the save file and that gets overwritten, rather than ‘all things of this type’ or ‘all things in this area’, which I think is Skyrim’s problem since it decides what to include in the savefile when you save. This just saves everything so it’s always the max size.

**Comment by OrbisAnima** [comment]
A good consideration for this feature is to save it on freezer log out, and consider it if you want to affect ghosts or not. I can also foresee complains on this if someone is altered via dna, so you have to be careful around this and the possible issues it would spring

**Comment by SpadesNeil** [comment]
>I can foresee complains on this if someone is altered via dna, so you have to be careful around this and the possible issues it would spring

That's why you can turn it off.

**Comment by OrbisAnima** [comment]
wouldn't a "save preferences" button make more sense?

**Comment by SpadesNeil** [comment]
No, because the goal here is persistence and persistence is supposed to be saved automatically without input from the player breaking immersion, unless they want to break that immersion on purpose such as calling an admin because they got changed in a way they OOCly didn't want, or toggling off character persistence while an admin isn't around.

**Comment by OrbisAnima** [comment]
Sounds good, another question, you will call the proc on the people that survived (escaped to central) or the ones that remained in the station too?

**Comment by SpadesNeil** [comment]
Ideally, everyone who survived until the end.

**Comment by OrbisAnima** [comment]
Then on the case you died, if you have this feature active, the only thing that would be saved is the point of spawning

**Comment by SpadesNeil** [comment]
Correct.

**Comment by Screemonster** [comment]
Personally I'd wanna have the shuttle always be the latejoin point just as an IC thing 'cause Scree _hates_ cryo. Mebbe have the arrivals point have options of shuttle, cryo, and "last logout point".

Bonus points if you can combine this with latejoining in bellies for people who ended their last shift in a stomach :3

**Comment by Leshana** [comment]
Today is the day I announced I would start looking into ss13

**Comment by SpadesNeil** [comment]
/datum/controller/gameticker/proc/declare_completion()
		world << "<br><br><br><H1>A round of [mode.name] has ended!</H1>"
		for(var/mob/Player in player_list)
			if(Player.mind && !isnewplayer(Player))
				if(Player.stat != DEAD)
					var/turf/playerTurf = get_turf(Player)
					if(emergency_shuttle.departed && emergency_shuttle.evac)
						if(isNotAdminLevel(playerTurf.z))
							Player << "<font color='blue'><b>You managed to survive, but were marooned on [station_name()] as [Player.real_name]...</b></font>"
						else
							Player << "<font color='green'><b>You managed to survive the events on [station_name()] as [Player.real_name].</b></font>"
					else if(isAdminLevel(playerTurf.z))
						Player << "<font color='green'><b>You successfully underwent crew transfer after events on [station_name()] as [Player.real_name].</b></font>"
					else if(issilicon(Player))
						Player << "<font color='green'><b>You remain operational after the events on [station_name()] as [Player.real_name].</b></font>"
					else
						Player << "<font color='blue'><b>You missed the crew transfer after the events on [station_name()] as [Player.real_name].</b></font>"
				else
					if(istype(Player,/mob/dead/observer))
						var/mob/dead/observer/O = Player
						if(!O.started_as_observer)
							Player << "<font color='red'><b>You did not survive the events on [station_name()]...</b></font>"
					else
						Player << "<font color='red'><b>You did not survive the events on [station_name()]...</b></font>"
		world << "<br>"

Source: gamemodes/gameticker.dm

Saving player stuff could be handled here!

**Comment by SpadesNeil** [comment]
Marking as won't add because this will go into Polaris I think.
