### ISSUE TITLE
Sergal ears still a hairstyle?

### ISSUE THREAD

**Issue by LunaruF** [SpadesNeil/VOREstation#628]
Now that we've had the ear style menu for a while now and now that almost all hairstyles can be selected by other species instead of just limiting them to a small set of hairstyles for that species, I'm curious why the hairstyle "Sergal Ears" is still left as a hairstyle and not an ear style.

**Comment by Arokha** [comment]
...what if I want the style without hair?

**Comment by LunaruF** [comment]
I'm not really sure I understand the question, but...
Ears set to sergal and hairstyle set to bald? Cause that's what it already is by default, just ears on a bald head.
