### ISSUE TITLE
Farm bots aren't buildable anymore

### ISSUE THREAD

**Issue by OrbisAnima** [SpadesNeil/VOREstation#63]
gathered all the tools, wasn't able to assemble one

**Comment by SpadesNeil** [comment]
Farmbot.dm has been turned back on. Closed issue for now. Will be in next push.

**Comment by SpadesNeil** [comment]
Okay I lied. It pukes up a bunch of compile errors.

**Comment by OrbisAnima** [comment]
I am not the guy to ask about Wiki :P

**Comment by SpadesNeil** [comment]
Giving up on this for now.
