### ISSUE TITLE
Teleporter random-spacing chance - can be scene-breaking

### ISSUE THREAD

**Issue by Screemonster** [SpadesNeil/VOREstation#630]
Okay, teleporting and telenoms are in, so the hand-tele and teleporters are seeing more actual use. which is neat.

But people have been using them for scenes (silly fun stuff involving someone getting a beacon, and an accomplice stuffing things into them via the portal) and there's been a couple of time that the teleporter has glitched and randomly spaced them.
Dying to RNG is annoying enough as a game mechanic as-is, but interrupting a scene with it is a real cockblock.

Could the random glitchiness be changed to something else - targeting the wrong beacon, for instance? Would make off-target teleporting annoying but not an RNG-kill if they get dumped in the wrong place, and also make slyly snagging a beacon and pocketing it a fun thing to do for preds. If anything it'd lead to MORE telenoms than present 'cause at the moment people can see the beacon list and guess pretty accurately which ones are gonna lead to bellies and avoid 'em. :p

**Comment by HethDrakiel** [comment]
While I don't use the teleporters because of the random spacing chance. It would be better for it to not have the chance to space someone and ruin their life (IG literally, IRL metaphorically)

**Comment by nightwingthedragon** [comment]
Despite not really using teleporters myself, I'm in favour of this. I'd have the line that says "here's a chance of you getting spaced" replaced with "Here; there's like a 60% chance that this'll lead to a beacon which would put you in a belly, and a 40% chance it'll lead to a beacon outside of a belly"

**Comment by Screemonster** [comment]
Tbh my main objection is that it's utterly _random_ and occurs without warning, during normal, correct use of the teleporter. It's a save-or-die with all the problems of any other save-or-die in any game.

At least all the other deathtrap aspects of SS13 are things that are avoidable with proper precautions. The only precaution you can take in the teleporter is wearing a spacesuit to your vore scene.

Now, for people using the hand-tele uncalibrated? _That_ I can support random destinations. Likewise, people teleporting with a bluespace backpack should screw up the targeting as normal. But using the equipment properly shouldn't be an effective instakill.

**Comment by Somekindofpony** [comment]
How about, instead of the extreme of being outside of the station, it teleports you to a random room anywhere on the station at a lower chance? That way, instead of just completely killing a person who didn't take the teleporter with them, it causes a minor inconvenience. Or, leave a 1% chance of being spaced, just for that 'oh fuck' feeling.

**Comment by nightwingthedragon** [comment]
A random room is a neat idea, but a little trickier in practice until I figure out how to send people to turf in zones.

**Comment by Arokha** [comment]
You can look at the admin jail verb thing. It puts everyone in tiny boxes on exodus-2, each in their own box.

**Comment by Screemonster** [comment]
Randomly picking from the available job spawn points would be interesting.

**Comment by Arokha** [comment]
I know we had this talk earlier, just reminding that the non-hand-tele has a 'test fire' that makes it perfectly accurate for 300 seconds.

**Comment by OrbisAnima** [comment]
Take a look into the mech's mounted teleporter code, it has a really tiny chance of getting you into space, but otherwise it teleports to rooms inside the station (atmos container rooms are a room.)

**Comment by Arokha** [comment]
Hmm, in thinking about it, maybe not 'any job spawn' since that means you can break into any department with or without beacons or a normal teleporter just by using the hand tele over and over again since it has no real battery.

**Comment by Screemonster** [comment]
Actually, giving the hand tele a battery would be an interesting thing. Or have a failure de-sync it from the teleporter until you go back there and punch in a destination again. (as it is at roundstart when you haven't yet activated a teleporter)

Or just have it pick a mob and dump you inside :3

**Comment by SpadesNeil** [comment]
This is actually a bug, in my opinion. It annoys the shit out of me that you can set up the teleporter, testfire it and everything, and the hand-tele can still fuck you off into space.

I want to eliminate all possibility of being spaced. At worst it should teleport you to a random room aboard the station.

Also, clicking on an active portal should also teleport you. This is to prevent issues if you get stuck in a wall or window.

**Comment by Arokha** [comment]
PR #668 makes the following changes:

Changes the 'test fire' time to 10 minutes to allow you to get more done per test-fire.
The hand-tele portals and self-teleport (when inside something) are 100% accurate if the teleport hub it's connected to is also accurate.
Next to the (Active) or (Inactive) when in the hand tele menu, it will list 'Accurate' if the hub has been test fired, like

3818 (Active, Accurate)

so you can tell remotely when you need to testfire it.

**Comment by Arokha** [comment]
Also the teleport computer reminds you to test fire when you pick a destination to make people realize that's a thing
