### ISSUE TITLE
Active edges on the map

### ISSUE THREAD

**Issue by N0B0DY-1MP0R7AN7** [SpadesNeil/VOREstation#633]
These are mapping errors where an air filled tile is adjacent to a tile with vacuum on it on startup.
I would fix this myself, but again, this is not a big enough issue to create a pull request for.

The problematic points are:
-A tile at the construction area outside east of security. Northernmost tile directly adjacent to the wall.(exodus-1.dmm)
-The MechRecharger tile, outside the science station on the asteroid, as well as the plating below the solar panels outside the science station. (exodus-5.dmm)
-The tiles connecting the solar panels to the grille outside the satellite both on western and eastern sides. (exodus-3.dmm)
-Keelin's private beach needs an unsimulated wall border like the holodeck maps. (exodus-2.dmm)

**Comment by SpadesNeil** [comment]
> -A tile at the construction area outside east of security. Northernmost tile directly adjacent to the wall.(exodus-5.dmm)

Exodus-5? You sure? Because that's exodus 1.

> -The MechRecharger tile, outside the science station on the asteroid (exodus-1.dmm)

And the asteroid is Exodus 5.

> -The tiles connecting the solar panels to the grille outside the satellite both on western and eastern sides. (exodus-3.dmm)

At Telecomms, right?

**Comment by N0B0DY-1MP0R7AN7** [comment]
Yep i mixed those two up

and yes at telecomms

**Comment by SpadesNeil** [comment]
After investigating this I do not understand the nature of the issue.

**Comment by SpadesNeil** [comment]
@N0B0DY-1MP0R7AN7 Screw it, you can handle it. :U You have my permission to do a PR for the maps.

**Comment by N0B0DY-1MP0R7AN7** [comment]
why though... you did almost everything fine....
you just forgot the mech bay charger on the asteroid, and the tile in the picture i showed you
 plus i have no idea how to create pull requests and such

**Comment by SpadesNeil** [comment]
Because it's not very clear what else is broken. Please provide screenshots with the problem areas highlighted.

**Comment by N0B0DY-1MP0R7AN7** [comment]
*siiiiigh*
You have fixed them except for two places


A) was in the screenshot i posted under your commit
[2:13:50 AM] Cody: https://gyazo.com/c96d9e1f633cb5fa17549c0585eb3955.png
the northernmost tile adjacent to the wall in that pic.

B) the other is on the asteroid. directly on the southern wall of the science outpost(the thing where you corrected the solars), there is a MECH-RECHARGER port, with the machine and the computer.
the tile between the two, the one the mech would have to stand on, has air

**Comment by SpadesNeil** [comment]
> the northernmost tile adjacent to the wall in that pic.
I swear I checked that one.
