### ISSUE TITLE
Belly rubs to speed digestion (remove excess nutrients and turn it into fat)!

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#634]
Human mobs should be able to give belly rubs to other human mobs to speed up digestion.

By digestion, I mean nutrient level. If nutrients is over 450, every rub reduces nutrition and turns it into bodyfat (if applicable). This COULD potentially speed up digestion of prey too but I don't think that is wise.

**Comment by Arokha** [comment]
I dun understand. So bellyrubs fabricate nutrients? Like, whatchu mean?

**Comment by SpadesNeil** [comment]
If nutrition level is to the point of being "overfed" (which, I believe is nutrition over 450 last I checked), it slows you down slightly and gives flavortext talking about how overly stuffed you are.

By giving bellyrubs, it'll remove some of the nutrition level. Think of nutrition as "the amount of foodmush currently being processed by your body".

Does that clear up what I'm explaining? By bellyrubbing, you help the "digestion" go faster. Mechanically, you're causing the game to remove nutrition every time you rub the belly and covert it into fat.

So instead of waiting like, an hour, to passively digest food, you can remove it quickly in the same way you'd normally exercise. The difference is this is the opposite of exercise. You don't lose weight. You gain weight. You digest and gain the weight faster. If weight gain is turned off, you gain nothing obviously.

**Comment by SpadesNeil** [comment]
I could do this probably, I'm just lazy.
