### ISSUE TITLE
Runtime Error (null.grid_sensors) On System Boot

### ISSUE THREAD

**Issue by Leshana** [SpadesNeil/VOREstation#638]
On some boots a runtime error will print a few times.  Not every boot, it is random (result of a race condition):

> runtime error: Cannot read null.grid_sensors
proc name: check warnings (/obj/machinery/computer/power_monitor/proc/check_warnings)
  source file: sensor_monitoring.dm,87
  usr: null
  src: Power Monitoring Console (/obj/machinery/computer/power_monitor)
  src.loc: the floor (113,70,1) (/turf/simulated/floor)
  call stack:
Power Monitoring Console (/obj/machinery/computer/power_monitor): check warnings()
Power Monitoring Console (/obj/machinery/computer/power_monitor): process()
/datum/controller/game_control... (/datum/controller/game_controller): process machines process()
/datum/controller/game_control... (/datum/controller/game_controller): process machines()
/datum/controller/game_control... (/datum/controller/game_controller): process()

**Comment by SpadesNeil** [comment]
Now I am no expert on these matters but I do not know if this affects anything negatively or if it's just an annoyance, so I don't know if I should make this blocker (totally breaks something), severe (badly impacts something making it very hard to use or lagging the shit out of the game), major (noticeable, annoying, but avoidable), or minor (barely affects anything, so easy to avoid that most people don't notice).
