### ISSUE TITLE
Ammo magazines can be put into incorrect guns.

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#64]
The SMG's box magazine fits into a 9mm Stechtkin pistol and vise-versa.

Solution: Add a variable that is checked when loading a gun that indicates what kind of gun can accept the magazine. Have a list of compatible guns for every magazine type. If the magazine is incompatible, it simply won't fit. "The caliber is the same, but the magazine won't fit!"

Should also make sure ammo loading uses push and pop with the insert() proc, instead of the stupid += bullshit that Baystation used prior.

**Comment by SpadesNeil** [comment]
As a personal opinion, I also don't like how you can empty a magazine in one click. Should be one click per bullet.

**Comment by ZodiacShadow** [comment]
On the subject of emptying the magazine of bullets, may I suggest the magazine's ability to fill up from a tile-click, similar to a pill bottle? ICly, it doesn't make any sense... but neither does the pill bottle, mining satchel or plant bag. They are VERY useful, though, and letting a magazine do that COULD make ammo handling a bit easier...

**Comment by SpadesNeil** [comment]
Noooo, filling magazines is a tedious job. If you didn't prepare prior to an attack, I do not find it fair to be able to abuse it later on. Top off your mags first.

**Comment by ZodiacShadow** [comment]
...that is true. Combat-involvement makes all the different. Retracted.
