### ISSUE TITLE
OOC escape doesn't work in simple_animal vore mobs

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#648]
if(istype(src.loc,/mob/living/simple_animal))
		var/mob/living/simple_animal/pred = src.loc
		var/confirm = alert(src, "You're in a mob. Don't use this as a trick to get out of hostile animals. This is for escaping from preference-breaking and if you're otherwise unable to escape from endo. If you are in more than one pred, use this more than once.", "Confirmation", "Okay", "Cancel")
		if(confirm == "Okay")
			pred.prey_excludes += src
			spawn(pred.backoffTime)
				if(pred)	pred.prey_excludes -= src
			var/datum/belly/B = vore_organs[vore_selected]
			B.release_specific_contents(src)
			message_admins("[key_name(src)] used the OOC escape button to get out of [key_name(pred)] (MOB) ([pred ? "<a href='?_src_=holder;adminplayerobservecoodjump=1;X=[pred.x];Y=[pred.y];Z=[pred.z]'>JMP</a>" : "null"])")
			for(var/mob/living/simple_animal/SA in range(10))
				SA.prey_exclusions += src
				spawn(18000)
					if(src && SA)
						SA.prey_exclusions -= src
		pred.update_icons()

**Comment by SpadesNeil** [comment]
Hang on, this might be my fault. Will re-open if it isn't.

**Comment by SpadesNeil** [comment]
okay yea, it's not me

**Comment by Arokha** [comment]
Was instructing prey's belly to release themselves. Testing fix now.
