### ISSUE TITLE
Create "Demand n' Supply" Event

### ISSUE THREAD

**Issue by Leshana** [SpadesNeil/VOREstation#651]
The "Demand n' Supply" Event is a random event where CentCom demands that the station deliver certain goods to them using the supply shuttle.  Success is rewarded, failure is grumbled about.

Sequence:
1) Event starts with an announcement and delivery to request consoles listing the items that should be delivered, and when the deadline is.
2) When the items are put on the supply shuttle and sent to CentCom, they are counted as delivered.  If only some of the items required were delivered, a new request console message is sent listing what still remains.
3) When all have been sent successfully, the event ends as a success. Awards supply points.
4) If the deadline is reached without all items delivered, event ends with failure.  Deducts supply points.

**Comment by Leshana** [comment]
In order to make this event, I will have to add an additional hook into the supply shuttle code to detect when the whole shuttle is old, instead of crate by crate.
Also: The request console code sucks! I will have to clean it up a bit in order to avoid huge repeats of code.

**Comment by Screemonster** [comment]
While you're working on the request console code, is it possible to make them notify the department on the appropriate channel when a request comes in?
Nobody ever uses them as it's quicker to just ask the cargo tech over the comms than it is to use the request console, and when you're working cargo the only time you even know a request is there is if you're physically stood next to it.
