### ISSUE TITLE
Vore mobs cannot damage Mulebots (and probably other robots)

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#657]
Need to test if this is just vore mobs or all hostile mobs, and if it's just mulebots or all bots.

**Comment by Arokha** [comment]
I bet mulebots are not /mob/living/silicon, and as such don’t have brute/burn/etc. If I remember right, most station robots (like cleaning and etc) are NOT /mobs at all, and are just objects that move around, in which case they literally have no brute/burn etc stats.

**Comment by SpadesNeil** [comment]
Correct.

**Comment by Screemonster** [comment]
... come to think of it, I've never seen Beepsky get taken down by hostile mobs. Something to test when I get home and fire up the test server.
