### ISSUE TITLE
Hostile mob target tracking can get stuck sometimes

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#659]
Need to investigate the cause but it falsely makes mobs appear non-hostile when they are VERY HOSTILE.

Mobs will sometimes keep a target variable even though the target is no longer in line of sight. This was witnessed with giant snake mobs (hostile/vore/large)

**Comment by Screemonster** [comment]
Is this related to the thing I've had with a faithless one time?
I'd taken control of it but it was in the confession booth. I aghosted briefly to peek and see if anyone was responding to the noises I was making, then someone opened the door and it immediately aggro'd - when I stopped aghosting and took control back, my movement was still locked on following them around, but not attacking unless I clicked them.
