### ISSUE TITLE
Can mobs still be force-fed if they are dead?

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#661]
If so, this should be corrected immediately. You cannot feed yourself to something that is dead.

**Comment by Arokha** [comment]
I'm not sure why this would be physically impossible.

You probably can feed yourself to things that are dead, but they can't digest you. The life proc is no longer going and their bellies would be inert so you could, you know tauntaun yourself inside them for whatever reason. But nothing would come of it.

**Comment by SpadesNeil** [comment]
Well then there needs to be a check for the update_icons() to not execute if the mob is dead, or the mob will have an icon that appears alive.

**Comment by Arokha** [comment]
Huh. Really? How... does... I mean what makes their icon dead to begin with? I was assuming that'd be update_icon() o.o

**Comment by SpadesNeil** [comment]
Yes, but it spits prey out before updating icons.

If the mob eats someone, it'll update_icons(). While alive, this is not an issue. If they are DEAD however, a problem arises.

1. Kill a vore mob. death() sets icon_state = icon_dead. update_icons() changes the icon so it's visible. So, snake-dead.
2. Force-feed yourself to it. update_icons() is called. Mob becomes [initial(icon_state)-[preycount]. So, snake-1.
3. Escape mob. update_icons() is called again. Mob becomes initial(icon_state) which is snake.

See the problem?

**Comment by Screemonster** [comment]
How would one get out of a dead mob besides OOC escape anyway? Is that a thing that's doable?

**Comment by Arokha** [comment]
Someone can help you out I guess. I’ve wanted to add resisting out of mobs for awhile though so maybe that.

**Comment by SpadesNeil** [comment]
Make sure you can only do that with NPCs.
