### ISSUE TITLE
Add fluff items (ears, tails, etc) to custom loadout menu

### ISSUE THREAD

**Issue by Screemonster** [SpadesNeil/VOREstation#67]
The custom loadout thing seems like the ideal place for things like cat ears and succubus wings and the like. Not a major deal for latejoiners as the vendor is right there by the spawn points, but it'd be nice for folks at roundstart not to have to trek back to a vending machine.

**Comment by OrbisAnima** [comment]
I was seeing the code of this one, after I finish with some custom items PR, I will tackle it

**Comment by OrbisAnima** [comment]
Done!
