### ISSUE TITLE
Few issues with Borgs with the new Vore Panel and an old issue.

### ISSUE THREAD

**Issue by GuiltyBeans** [SpadesNeil/VOREstation#675]
First time using this to report issues, so bare with me......So a few things popped up that I've found. With the new vore panel, all living things can eat. Seems that borgs got that to! So here's a few things I've seen so far I think could be looked into for them:

- Borgs can't grab or be grabbed, thus they are unable to eat (Without someone feeding), or be eaten. Makes sense to not be eaten though."
- If fed someone, the bellies that a borg can use via the vore panel don't instill the effects they are supposed to. Digestion, Absorption and Healing all don't work. This was tested with Medihound and K9 models whom have the sleeper bellies.

As for borgs in general, I've found a few issues and was directed here, so here goes:

- An issue came up during an away mission where a subject was suffering brain damage. While inside the Medihounds sleeper they were given Bicaridine to cure brute and then Alkysine to cure a 15.5% brain damage. The Brute damage was fixed, but the brain damage wasn't. Unsure if it was due to blunt trauma or not, but was asked to report it.

**Comment by Arokha** [comment]
Borgs aren’t really designed for noms. The vore mechanics all use nutrition which borgs don’t have. So for now, borgs can’t eat people properly. Just use the sleepers rather than the vore mechanics! :p

**Comment by SpadesNeil** [comment]
Please keep different bugs in separate reports so we can be clear about which one is being fixed or not and why.
