### ISSUE TITLE
Telenoms are broken in the new vore system.

### ISSUE THREAD

**Issue by Screemonster** [SpadesNeil/VOREstation#676]
Probably related to people not having a "stomach" any more.
It dumps you in their contents, but doesn't do any gulping or put you in an actual belly according to the vore panel. Using OOC shows in the logs as you escaping from them but doesn't actually move you.

Suggest having it always go to the first belly, the one you start out with and is immutable. Probably also a good idea to tag that one so it's _always_ a "stomach", otherwise we'll run into pref issues when someone sets it to be their dick or something and someone who's not into CV has their teleport intercepted.

**Comment by Arokha** [comment]
`var/datum/belly/B = targetmob.vore_organs[1]`

Already thought of this. It **DOES** put you in the first belly.

**Comment by Screemonster** [comment]
... well, it didn't when I just did it on my test server. I fed the beacon to a random sergal, then pointed the teleporter at it, testfired, and hopped through. Inside panel didn't show me in a belly even though I did jump to their position.

**Comment by OrbisAnima** [comment]
maybe inside panel is the one borked? did you try normal consumption and checked the panel?

**Comment by Screemonster** [comment]
Test that too. That worked fine.

**Comment by Arokha** [comment]
I know what it is now. Associative arrays will be the death of me. Let me improve telenoms a bit and I'll fix that too.
