### ISSUE TITLE
Ability to ignore some players OOC and deadchat (Not LOOC and IC)

### ISSUE THREAD

**Issue by OrbisAnima** [SpadesNeil/VOREstation#677]
Here is a code I though you guys would find useful, does what the title says, also, it's an example of middle round saving preferences

https://github.com/PolarisSS13/Polaris/pull/1539

**Comment by SpadesNeil** [comment]
I am strictly against ignoring players ICly and LOOCly, but this, I am okay with.

Obviously ensure admins cannot be ignored.

**Comment by Datraen** [comment]
I'm a dev on Polaris, I'm going to talk to the dev of this PR to try to ensure that staff can't be ignored, for obvious reasons.

**Comment by JoanRisu** [comment]
Welcome friend. ouo)b

**Comment by SpadesNeil** [comment]
> I had absolutely no idea what server this was.

Welcome to the weird part of the SS13 community.
