### ISSUE TITLE
Adds humanoid foxes and fennec foxes (Name WIP)

### ISSUE THREAD

**Issue by Cameron653** [SpadesNeil/VOREstation#683]
# **CURRENTLY WIP**

Add humanoid foxes. 
Add humanoid Fennec foxes
Add fox tail
Add Fennec tail
SPRITES: http://puu.sh/oFjmp/ef815b7100.png 
(Sprites created by: ArgobargSoup)

Features: 
Fennec have higher heat resistance and lowered cold resistance.
Foxes have lowered heat resistance and heightened cold resistance

Edit: Clarification

**Comment by Arokha** [comment]
I likes me some FENKS!

Make sure you split the tail/ears sprites and put them into sprite_accessories.dm so they show up for users in the ears/tails options. Just cut/paste them into their own icon states and put them into the files referenced. If you have questions, let me know!

**Comment by Cameron653** [comment]
@Arokha Alrighty, cheers!

**Comment by SpadesNeil** [comment]
The original creator of the sprites is ArgobargSoup from Eka's. They sent me these sprites for use.
