### ISSUE TITLE
Space Bear vore code doesn't seem to work

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#687]
Reportedly, they do not eat people they knock over.

**Comment by Screemonster** [comment]
/mob/living/simple_animal/hostile/vore/bear/AttackingTarget() doesn't contain a callback to the parent, which is where the eating happens.

**Comment by SpadesNeil** [comment]
Fixed by https://github.com/SpadesNeil/VOREstation/commit/8e21790407baff9cea0d3ecba823527630a97448
