### ISSUE TITLE
Fire Alarms not working

### ISSUE THREAD

**Issue by JoanRisu** [SpadesNeil/VOREstation#692]
Three people have tested this, myself included. The Fire Alarms are not responding to manual commands nor are they responding to timers.

**Comment by Arokha** [comment]
A bit frustrating as there's no exceptions on the server. Do they respond to FIRES though?

**Comment by JoanRisu** [comment]
According to people who've tested it, no they do not. Only the Atmos alarms react to fires. 

The Atmos alarms are also having problems resetting.

**Comment by Arokha** [comment]
I do not think the air alarm reset is related. It can be another issue if necessary but as far as I know, air alarm resets not working has been a longstanding tradition fixed by screwdriver.
