### ISSUE TITLE
Vox Alien stealth/Carapace/Pressure/armour suit

### ISSUE THREAD

**Issue by Prawneen** [SpadesNeil/VOREstation#694]
so! For the first time I made a Vox character on vore station and immediatly wanted to see how the stealth suit looks like. I got a holokit and changed it to alien stealth suit. However it didn't work. The sprite didn't show up and it simply shows the small green "SUIT" thing.

Easy to re-create the problem. Grab a holokit, take the exosuit part and change it to Alien Stealth suit or any other of the Vox Alien suits while playing a Vox. It seems bugged. The sprite at least! And since I wanna play a Vox it really bothers me ;~;

I have no idea if the real suit is bugged too, The holokit version is though.

Also is it possible to store the Nitrogen Tank somewhere else than your hands and backpack as a Vox? It's a bit annoying if you wanna keep your actual backpack, and carry around the Nitrogen tank

**Comment by Prawneen** [comment]
I've tested the real Vox stealth suit and other suits with the current code of Vore station. And spawning it in, and wearing it as a Vox works perfectly fine. Seems like only the Holokits option is bugged.

**Comment by Cameron653** [comment]
I can confirm that it's only the holokit that is bugged.
http://puu.sh/oJqry/ee982d05b0.png
Top row: Real suits
Bottom row: holokit suit.
