### ISSUE TITLE
Security Camera map needs to be updated

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#695]
This map has never been updated since we made the new code. We should correct that. I just do not know how it is done.

**Comment by Arokha** [comment]
There's a button in one of the admin panels that's like 'generate nanoui map' or something like that. It will build the PNGs and throw them at you. It freezes the server for like 60 seconds so maybe do it on a test server. Then, you include those in spessmens. Like the pngs are just in a folder somewhere. Can't remember where.
