### ISSUE TITLE
AMI RIGs useless for xenoarch/anom

### ISSUE THREAD

**Issue by KiraAlitruss** [SpadesNeil/VOREstation#698]
Issue made on 5.5.2016

The AMI hardsuit modules cannot be deployed by xeno archaeologists nor anomalists due to a lack of access on their part. 
Image evidence (to look nice); ![image of evidence](http://img.prntscr.com/img?url=http://i.imgur.com/fmp7TJj.png)

**Comment by Cameron653** [comment]
Currently, as it is, only the RD has access as shown here:

https://github.com/SpadesNeil/VOREstation/blob/e65ce61831290aac92069283a0fae9515dc3af18/code/modules/clothing/spacesuits/rig/suits/station.dm#L66

Going to fix this up real quick.

**Comment by Cameron653** [comment]
Resolved this and squeezed it into the fennecs and foxes addition.
