### ISSUE TITLE
Prey can buckle their predators to things.

### ISSUE THREAD

**Issue by Screemonster** [SpadesNeil/VOREstation#70]
As title. It's rather silly.

**Comment by OrbisAnima** [comment]
Pfff, this is awesome :D

**Comment by ShadowLarkens** [comment]
Prey can do a lot of things they probably shouldn't be able to do, like shoot weaponry, disarm their surroundings, etc.

**Comment by OrbisAnima** [comment]
and administer pills

**Comment by OrbisAnima** [comment]
This is sadly one of the areas of code I will opt to say "Yeah... let's implement honor system"

**Comment by SpadesNeil** [comment]
Not really. Find the place in the code where it says "You buckle so-and-so to the chair" and then check if you're inside a belly before that code is executed.

If you're in a belly, return. Maybe leave a message like; "You're inside of a stomach. You can't buckle them to a chair, idiot."

**Comment by ShadowLarkens** [comment]
@SpadesNeil Problem is, to actually make sure that applies everywhere, we would have to snowflake those kind of checks practically everywhere. Attackhand code, buckling code, etc.

**Comment by OrbisAnima** [comment]
uh, I was thinking, what if we enforced the resting status or the handcuffed status on the belly?

**Comment by SpadesNeil** [comment]
Resting status breaks wiggling, though. Of course we could just add in a new verb to replace that so prey can still do squishy wiggly noises. Something under the IC tab. But, then we still have to check if we're in a belly to begin with and we are back to square one.

**Comment by Arokha** [comment]
Resting prevents PDA use, and if you make any sort of new status you're back to the part where you have to check for that new status everywhere. Really, anything that prevents hand-use like buckling or shooting also prevents using PDA, which people do while they're in bellies fairly regularly.

The game really wasn't just designed with 'being in things' in mind. There's unfortunately not a 'reach' proc that returns everything in reach. That'd be neat though. We're stuck with view and oview for now.

**Comment by SpadesNeil** [comment]
Giving up on this.

**Comment by OrbisAnima** [comment]
Ace, the problem is the following. You need to have a flag for when someone is vored, wich you have I believe, and then add an if on the buckling action.

**Comment by OrbisAnima** [comment]
snowflake it if it's that big of an issue

**Comment by SpadesNeil** [comment]
If you want to take a crack at it, go for it.
