### ISSUE TITLE
Releasing someone inside someone else breaks them?

### ISSUE THREAD

**Issue by HethDrakiel** [SpadesNeil/VOREstation#711]
I was playing around with one of the mechanics OOC, I ate someone while we were both inside someone else, and when I release they became invisible and stuck to primary prey (The one who nommed both of us) and they were invisible but could still somewhat act

**Comment by HethDrakiel** [comment]
I tested this at the start of the very next round (didn't comment then because I went to bed right after) with me as the primary pred, and when the bottom prey was nommed and released in me I couldn't find any trace of them in any of my bellies (or inventory spots) but they were still stuck to me, unless I overlooked something while I was tired

**Comment by Cameron653** [comment]
Just tested this. Can confirm it's a bug.
