### ISSUE TITLE
Double Bladed energy sword sprite disappearing when activated

### ISSUE THREAD

**Issue by JemliRoivas** [SpadesNeil/VOREstation#714]
Both the inventory sprite and the sprite that appears on the character disappear when the blades are activated.  In order to deactivate currently, you have to drop the blade.
![scrnshot1](https://cloud.githubusercontent.com/assets/19252303/15098510/5b90ea42-150d-11e6-8f30-9b5835029a6b.png)
![scrnshot2](https://cloud.githubusercontent.com/assets/19252303/15098511/5b931074-150d-11e6-8b71-c7709b4f9148.png)

**Comment by SpadesNeil** [comment]
#321
