### ISSUE TITLE
Black slimes should produce random minerals normally found mining

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#719]
Obviously not very much, but it'd be a nice alternative for shifts with no miners.

**Comment by Cameron653** [comment]
I think this would be a good idea, as science has no other way to get minerals other than miners (And the xenoarcheologist getting lucky), and it would be relatively easy to make/add in.

**Comment by antsnap** [comment]
Good idea. When balancing, lean towards the abundant side. Keep in mind it takes a while and a lot of luck to get to the black slimes, so the reward should be plentiful.

**Comment by SpadesNeil** [comment]
The only problem is black slimes only produce more black slimes. This can become extremely broken very quickly if left unchecked.
