### ISSUE TITLE
Vore messages are formatted oddly

### ISSUE THREAD

**Issue by ZodiacShadow** [SpadesNeil/VOREstation#72]
An example anal vore message may follow the format "[predname] schlorps [preyname] into [pronoun][predname] [bodypart]."
In that, the fact that the pronoun and the pred's name stick together is one thing... but the fact that the pred's name is mentioned again at all is odd. Nehi'd get the message "-into her Nehi Maximusbelly", for instance, which seems highly redundant.

**Comment by SpadesNeil** [comment]
This isn't something we're going to bother correcting, as there's not currently a better way to do it, and when we make one, the old system will get gutted and thrown out anyway.

**Comment by SpadesNeil** [comment]
Wait I totally misread this.

**Comment by Leshana** [comment]
This was fixed by efdcb0a3712e7b962b688939902a8cd70323c4f5, so I will need specific examples of where it is still broken.

**Comment by ZodiacShadow** [comment]
As far as I can tell, all basic non-oral vore messages still have it. At least as late as yesterday.

**Comment by Arokha** [comment]
I believe a PR has fixed this. I'll test it and comment when I get a chance.

**Comment by Arokha** [comment]
> SharkGuy has grabbed HumanSnack passively!
> SharkGuy has grabbed HumanSnack aggressively (now hands)!
> SharkGuy is attempting to push HumanSnack up his rear!
> SharkGuy schlorps HumanSnack into his rump!

This is fixed in production, though I do not know which PR contained the fix for it. This can be closed.
