### ISSUE TITLE
Toggle digestiability broken / digestable var setting to null

### ISSUE THREAD

**Issue by DemicusMaximus** [SpadesNeil/VOREstation#720]
After using the new vore panel, a person's digestibility seems to be setting itself to 'null' rather than 1 or 0.

"(R)Jade Heartfeelia/(Lknecross)(JMP): side note i set to undigestible once and the option vanished on me"

Has been encountered at least three documented times now. Could be an issue with the saving system, as it seems to work fine when you set it, but the next shift it appears to be 'null'. Will test.

**Comment by SpadesNeil** [comment]
This causes a variety of things to break. This needs to be fixed. It breaks vore mobs.

**Comment by SpadesNeil** [comment]
@Arokha please fix this ASAP.

**Comment by SpadesNeil** [comment]
There appears to be no way to toggle digestibility. It should start as 1 at roundstart.
