### ISSUE TITLE
Shrinkshrooms are not in the code yet

### ISSUE THREAD

**Issue by OrbisAnima** [SpadesNeil/VOREstation#73]
Tiny and grow mushrooms are not in the new code yet, although the reagents do exist.

**Comment by SpadesNeil** [comment]
Okay so I can't assign two people.

@nightwingthedragon @ShadowLarkens You guys were messing with the shrink code so I'll let you two fix the missing things.

**Comment by SpadesNeil** [comment]
@nightwingthedragon , was this resolved in your recent PR? You did not reference this issue.

**Comment by nightwingthedragon** [comment]
I didn't reference this specifically, but from the title of the PR and the description, you'd know that I re-added shrink rays, but the plants are almost impossible because of how much the botany code has changed and now I literally can't find where fruit is defined.

**Comment by SpadesNeil** [comment]
I'mma edit the title, then.

**Comment by OrbisAnima** [comment]
I will try my hands at fruits, see if I can make them usable, work has been a bit heavy these days, so I can't say when I will finish
