### ISSUE TITLE
Voidsuit not showing up on character

### ISSUE THREAD

**Issue by JemliRoivas** [SpadesNeil/VOREstation#730]
![novoidsuit](https://cloud.githubusercontent.com/assets/19252303/15448757/591d347a-1f38-11e6-92be-db6f606aefd7.png)
The refitted voidsuit doesn't actually show up on the character model

**Comment by SpadesNeil** [comment]
This version of the code is no longer supported. If this is an issue on the new code, please go to the new Github page.

https://github.com/VOREStation/VOREStation
