### ISSUE TITLE
Runtime mauls mice

### ISSUE THREAD

**Issue by Razerwing** [SpadesNeil/VOREstation#732]
Was fiddling around in CMO's office as a mouse, went to ventcrawl expecting Runtime to do the vore stuff and give me a chance to escape, instead I got chomped. I think the Mob Vore feature may have been left out.

**Comment by Arokha** [comment]
Wasn’t left out, but maybe it prioritizes splatting mice. We’ll look at it.

**Comment by SpadesNeil** [comment]
This version of the code is no longer supported. If this is an issue on the new code, please go to the new Github page.

https://github.com/VOREStation/VOREStation
