### ISSUE TITLE
Drone manufactory broken?

### ISSUE THREAD

**Issue by ZodiacShadow** [SpadesNeil/VOREstation#75]
I've tried several times to join as a drone from spectating; even had an engineer try to enable the function in the machines beforehand - nothing seems to cause the "Join as Drone" verb to do anything. That said, I DID just see an issue-report about drones... so was this issue resolved, or was that drone admin-spawned?

**Comment by SpadesNeil** [comment]
That should have been fixed by d7d8a91 and I updated the server last night. Please only report issues which you can still reproduce in the latest server version.
