### ISSUE TITLE
Stun gloves

### ISSUE THREAD

**Issue by ZodiacShadow** [SpadesNeil/VOREstation#76]
While not a bug, per se, it still bugs me. The ability to create stun gloves was removed. Any chance that'll be re-added?

**Comment by OrbisAnima** [comment]
I vote no, I like my weapons visible and in hand, and if they are insconspicuous, let them be some high tech gear, not something an assistant can do :P

**Comment by SpadesNeil** [comment]
No. Stun gloves were OP in that they were impossible to detect. You can build stun prods now instead.
