### ISSUE TITLE
TeleScience

### ISSUE THREAD

**Issue by ZodiacShadow** [SpadesNeil/VOREstation#77]
I know not a lot of people used it, but /I/ did and know quite a few others that did. The room is now Misc science, which is used even more rarely, but has the same layout, minus the actual TeleSci gear. Any chance this'll be re-added? Do I improve the chances if I scavenge for the old telescience-code?

**Comment by OrbisAnima** [comment]
I will support Zodiac in this one, there were some fun scenes made with this machine, even if it was ultimately used for evil... maybe a reconcepting of this should be used?

**Comment by SpadesNeil** [comment]
Marking wontfix for now, but don't be discouraged from checking the code for the parts and getting them to work in test servers. If you're successful, we just need to find a new place to build it. I'm thinking we actually move telescience to a section of xenoarcheology.

The old telescience room is the new miscellaneous research room, and we can't get rid of that.
