### ISSUE TITLE
Re add Clothes Machine

### ISSUE THREAD

**Issue by OrbisAnima** [SpadesNeil/VOREstation#78]
I will be honest, I didn't checked yet if we have the code and sprites for it, but even if we do we still need to add it to the map, so first half of the issue is finding/adding the clothes machine, second is to add it to the map

**Comment by SpadesNeil** [comment]
It never needed special sprites but I do like the clothing machine we had. Furthermore the spawn options need more selection.

**Comment by SpadesNeil** [comment]
Done.
