### ISSUE TITLE
Digestion speed vs Nutriment must be rebalanced.

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#80]
Players are getting waaaaaaaaaaaaaaaaaaaay too much nutriment because digestion now takes substantially longer than it used to.

I have no interest in speeding digestion up, but nutriment gain must be nerfed to compensate.

**Comment by SpadesNeil** [comment]
Someone has to figure out how much nutriment they gain from fully digesting a full sized person.

**Comment by ShadowLarkens** [comment]
Fully healthy human, fed to a skrell who has precisely 0 nutrition:
Took roughly 10 minutes.
It ended up giving the skrell *1044* nutrition.

**Comment by SpadesNeil** [comment]
http://forum.vore-station.net/viewforum.php?f=26 We're voting here on how to resolve this.
