### ISSUE TITLE
Micro collision does not ignore larger players

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#83]
@nightwingthedragon 

Micros collide with large players and stepping on them doesn't have the same effects as before. This feature needs to be ported from the old code.

**Comment by SpadesNeil** [comment]
@ShadowLarkens may also wish to help.

**Comment by nightwingthedragon** [comment]
This should be an easy enough fix once I get my head around the new system; human collision code has been merged with all carbon collision code. On the down side, this means it'll be a lot more work to try to work out where to put my code. On the plus side, I should be able to get it working with all carbon mobs.
