### ISSUE TITLE
Booze to do [enhancement]

### ISSUE THREAD

**Issue by OrbisAnima** [SpadesNeil/VOREstation#86]
We need both soda fountains and booze dispensers to have an empty glass option, if it's viable.

We also have missing the Catnip drink

**Comment by SpadesNeil** [comment]
You can do this if you like.

**Comment by Arokha** [comment]
Yeah, I'd like that. Add it to chem dispensers too please. Annoying to make a mistake in the ORDER of things going into the beaker and making something else. Would like to dump it without going over to chemmaster and putting it all into the disposal or ejecting it and dumping it (not always the best idea).
