### ISSUE TITLE
Chaplain Job Titles, new code missing things, 

### ISSUE THREAD

**Issue by Molenar** [SpadesNeil/VOREstation#87]
Molenar wrote:
we lost at least some of the alternate job titles on code swap. I noticed a lot less available under the chaplain options. Used to use 'Priestess' all the time. Haven't looked through all of them to find others that were lost.
Aces wrote:
Chaplain is one job that should get its alt titles back.

Other jobs, especially those in command, are sticking with what they have now and I'm not changing it back because it broke things and caused confusion.

But Chaplain can get its alt titles back. Submit an issue on Github.

**Comment by HawkerTheGreat** [comment]
If you could give me some ideas for alt titles, I'll add them... Or for any other job. We should stick to not giving heads titles, though. I agree with Ace.
