### ISSUE TITLE
Cloner Room Clothing

### ISSUE THREAD

**Issue by Arokha** [SpadesNeil/VOREstation#90]
I'm aware we don't have clothing vendors coded yet (separate issue), but meanwhile there's a need for spare clothing in the cloner room.

**Comment by Arokha** [comment]
There is a locker in there already for doctor clothing for no apparent reason (genetics has a clothes locker, doctors have lockers in medical storage. Why is this one there?). Repurpose into just a locker with like 10 black jumpsuits?

**Comment by ZodiacShadow** [comment]
Remember shoes. Maybe add some pyjamas and bunny slippers, too. Some people liked that.

**Comment by Arokha** [comment]
I at least just want a bare minimum of something to avoid them having to run naked from medical to the locker room or their department or the HoP or wherever. I'll be honest in that I've been spawning clothing/under/black uniforms for people en masse on the table.

**Comment by ZodiacShadow** [comment]
Hah, that's fair. I'd still recommend shoes, though, as they considerably increase movement speed. Not to mention that, in the off chance that there's glass shards in the hallway, it'll keep 'em safe en route to the locker room.

**Comment by Arokha** [comment]
True, though most nonhumans can't wear shoes. Maybe a few sandals too.

**Comment by SpadesNeil** [comment]
Wrong topic labeled. Ignore that.

**Comment by Leshana** [comment]
Fixed by PR #124
