### ISSUE TITLE
Merecnary Shuttle: Rear Windows

### ISSUE THREAD

**Issue by Arokha** [SpadesNeil/VOREstation#91]
The merc shuttle needs rear windows to keep the air from escaping, like other shuttles. 'Engine' tiles do not block air. Blue circled rooms are always vented when the map starts. Additionally, due to the fact that the middle room is connected to unsimulated hallways, it is always a constant source of ZAS updates, moving the crowbar and torch around at the back there as well.

![mercshuttle](https://cloud.githubusercontent.com/assets/15028025/10359936/d9236746-6d6a-11e5-88ef-6c8a4cd90c1a.PNG)

**Comment by SpadesNeil** [comment]
Was fixed several commits ago.
