### ISSUE TITLE
Mercenary Shuttle: Moving Issue

### ISSUE THREAD

**Issue by Arokha** [SpadesNeil/VOREstation#92]
The shuttle does not move. You can order it to relocate, the drive 'charges', and then the status changes to 'moving' forever. It never actually changes positions, and further interaction with the console is not possible.

**Comment by SpadesNeil** [comment]
Should check if the Vox skipjack has the same issue.

**Comment by Arokha** [comment]
Ok, it actually looks like this is an issue that there are TWO "Merecenary Base" areas. One is a weird unfinished crappy one and one is the legit one. It picks randomly between the two when you Jump-to-Area. Can the crappy one be removed or renamed?

**Comment by Arokha** [comment]
What was changed? The other one is still named 'Mercenary Base' and the air still bounces everything around the whole shift.

**Comment by SpadesNeil** [comment]
Deleted the whole area on the map. It's not in the server yet. It's fixed, though.
