### ISSUE TITLE
Chemistry Scanner

### ISSUE THREAD

**Issue by Arokha** [SpadesNeil/VOREstation#94]
The scanner that starts on the table in chemistry is the almost-useless mass spectrometer instead of a reagent scanner, which would be far more suitable for chemistry. This may have been an accident as the sprites are identical.

**Comment by SpadesNeil** [comment]
I think this is intentional actually, because chemist PDAs start with reagent scanners built in, but frankly I think it's stupid anyway so I changed it for next map pull.
