### ISSUE TITLE
Armory Inventory sucks

### ISSUE THREAD

**Issue by ZodiacShadow** [SpadesNeil/VOREstation#97]
We're given a list of objects without amounts listed and without designating whether the items are in the armory, the secure armory or in tac storage. Not to mention that several items aren't listed, including *all* ammo. I wrote up a draft for an alternative; it's got what the armory currently contains.
Since I can't seem to attach it here, I threw it onto pastebin. http://pastebin.com/6ytwPeNx

**Comment by SpadesNeil** [comment]
This doesn't belong here. This belongs on the suggestions forum. This is not a bug nor a coding issue. Just an opinion about the map.
