### ISSUE TITLE
Wiggle cooldown/randomness is much too sparse.

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#99]
I know we got the cooldown working but now we have the opposite problem as before.

Now it's so hard to make wiggle emotes appear that it's almost as if the feature doesn't exist.

Wiggle emotes should be more responsive, though a cooldown should still be in effect.

**Comment by nightwingthedragon** [comment]
Whoever has the code for this, find out what it currently says, and think of a reasonable delay between squirms. Perhaps a random number between 3 and 5 seconds.

**Comment by Arokha** [comment]
The cooldown is 2 seconds, and has a 40% chance of emoting. It appears that only stomachs have this feature, though. There's no struggle emotes for wombs or balls or whatever.

**Comment by SpadesNeil** [comment]
Remove the % chance please? If it has a cooldown for 2 seconds then the 40% chance is redundant. That was just my hacky-ass fix for not knowing how to do cooldowns at the time.
